### ISSUE TITLE
Android browser throws out handleOutOfMemory when deploy Readium-JS with local NanoHTTPD

### ISSUE THREAD

**Issue by minhld** [readium/readium-js-viewer#136]
I tried the Readium-js on Android with a local NanoHTTPD installed. It looks good at first but after running through about 10 more pages (sometimes less than) I got the memory problem "handleOutOfMemory" which browser reported 280MB was used
...
I/VENKAT(14889): V8Proxy::handleOutOfMemory() : memoryUsageMB [269] 
...
Then browser displayed a white page and navigation buttons were disable. This test was performed on Galaxy Note2 and Nexus 7; on Galaxy Tab 10 this caused a crash. It happened all the time, not just some times.   

This problem is not from NanoHTTPD because after browser threw out memory exception, I can still access the readium-js from outside.

**Comment by danielweck** [comment]
Please try to reproduce this with the latest version from develop. I am closing this issue (too vague, not actionable), but feel free to re-open with more details. Many thanks!
PS: please test with opening of expanded / exploded EPUBs, not zipped EPUBs.
