### ISSUE TITLE
Trouble opening cloud reader on iOS 7 iPad

### ISSUE THREAD

**Issue by Kathybluefire** [readium/readium-js-viewer#139]
I have a site up with tons of test books. Have switched to the Cloud Reader, vs JS Viewer as it is more compact and loads quicker. 

Here's the URL to one of the libraires: /plasmacore.net/cloud-reader-layout

It opens fine, to the library, from my Windows 7 machine and books open and preform correctly. 

From the iPad the library opens, but when you open a book it hangs once the small type at the very top appears. 

The same epub-content files work well on the iPad in the JS Viewer. Check it out: /plasmacore.net/Readium_Layout

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/readium-js-viewer/issues/352
