### ISSUE TITLE
Shift-tab within Bootstrap dialogs does not cycle around

### ISSUE THREAD

**Issue by becka11y** [readium/readium-js-viewer#146]
With the Settings dialog open, press tab to cycle focus around all of the elements in the settings pane.  Note that focus will circle from the Save Changes button at the bottom right to the close button in the upper right of the dialog.  Shift-tab should work the same in the opposite direction.  However, with focus on the close button, pressing shift-tab appears to do nothing, focus leaves the close button and seems to go no where. 

Tested with VoiceOver on OS X 10.9.4 with Chrome Extension readium-js-viewer sha = eedd52eb (Tue, Aug 5, 2014)

**Comment by danielweck** [comment]
Thanks @becka11y for the initial fix. I replicated your method into the other dialogs:
https://github.com/readium/readium-js-viewer/commit/1a777550a295589436c6fcfafa14ccc16dff1340
https://github.com/readium/readium-js-viewer/commit/1fae05c70d02e3c2d51bc43072da99a2a1dfb829
