### ISSUE TITLE
packagePath seems redundant in epub_library.json

### ISSUE THREAD

**Issue by Kathybluefire** [readium/readium-js-viewer#169]
Hello!

I have a bunch of books which I use in testing the JS Viewer, and saw something that makes me very curious. All the directories are structured exactly the same for 15 or so books:

![ebook directory](https://cloud.githubusercontent.com/assets/4503010/3956817/912f36b0-270f-11e4-880d-8d5c2924e737.png)

The JSON Library uses a different directory for the opf path, consistently in all the files. 

![json library](https://cloud.githubusercontent.com/assets/4503010/3956830/b3561c72-270f-11e4-951d-7a316632c557.png)

Why does this work? Shouldn't the two need to match?

Kathy

**Comment by danielweck** [comment]
Addressed here: https://github.com/readium/readium-js-viewer/commit/78de0db0245042a30668a4559fbb6cc270921e44
`packagePath` is sometimes not statically hard-coded inside the library data (JSON or OPDS), so the path to the OPF file (which is necessary to view ebook metadata in the details popup dialog) must be extracted from META-INF/container.xml at runtime

**Comment by danielweck** [comment]
Note: EPUB3 Multiple Renditions => multiple OPF package files per `META-INF/container.xml`, but the detail metadata popup dialog only shows the first "root file".
https://github.com/readium/readium-js-viewer/tree/feature/epub3MultipleRenditions
