### ISSUE TITLE
Add a LICENSE in the repo root dir

### ISSUE THREAD

**Issue by pettarin** [readium/readium-js-viewer#193]
Issue: deciphering which license applies to the code in the repo is not trivial. (I believe it is the "3-clause/New BSD license".)

Suggested Fix: Add a LICENSE file in the repo root directory, and maybe mention it in the README

Thanks.

**Comment by danielweck** [comment]
Was fixed some time ago: https://github.com/readium/readium-js-viewer/blob/develop/license.txt
