### ISSUE TITLE
Running readium on a custom application server

### ISSUE THREAD

**Issue by alper** [readium/readium-js-viewer#197]
I'm trying to get readium running as part of a django (i.e. non-Node, non-Apache) application server. For this I can host the css/js files with the rest of mine, but I'm not sure which folders to host where and how to get started.

The current index and simpleviewer examples are simple but they seem rather tightly coupled with a specific way of serving the files.

The chrome app index.html includes 
```
<script src="scripts/readium-all.js" type="text/javascript"></script>
```
but when I copy that it can't find the rest of the javascript files or locales for instance.

**Comment by dmitrym0** [comment]
FWIW, I have this relatively stale copy of readium-js-viewer checked out: https://github.com/readium/readium-js-viewer/commit/277478c145f4cc578405ccf8fff23c8856a97392 and zip reading is working fine with bundled node server. 

@danielweck i believe this can be closed.

**Comment by danielweck** [comment]
@mahag asked:
https://github.com/readium/readium-js-viewer/issues/266
"
I did try the steps on web server for basic ebup reader.
I placed content inside reader-js-viewer folder on server and try to open url
yourdomain/readium-js-viewer/simpleviewer.html?epub=epub_content/moby_dick

But it is nt showing anything since i didnt configure web server for http byte serving.
I have windows server 2012 with IIS version 8 . How can I acheive that ?
"

**Comment by danielweck** [comment]
Related: https://github.com/readium/readium-js-viewer/issues/243

**Comment by danielweck** [comment]
This is a server-side issue. For example, `DivShot.io` produces incomplete HTTP headers that would be needed for Readium to consume zipped EPUBs ( https://github.com/divshot/superstatic/issues/169 ), whereas `Surge.sh` works fine. On another Apache test server I had to disable gzip:
```
SetEnv no-gzip 1
<ifModule mod_gzip.c>
  mod_gzip_on No
</ifModule>
```

**Comment by danielweck** [comment]
PS: we wrote a document to cover HTTP CORS use cases: https://docs.google.com/document/d/1RK_59-75OSE0PA6wexD9rYHQLnNYfoKIpsnH3SmDpUc/
..and the latest `readium-js-viewer` actually makes use of two separate HTTP server addresses (app vs. ebook library)
