### ISSUE TITLE
Readium-js-viewer not loading on iOS correctly

### ISSUE THREAD

**Issue by softroots** [readium/readium-js-viewer#220]
I have been dealing with an issue with the readium-js-viewer being installed as an iOS app on the iPad.
It appears to start loading an epub (tried many different unzipped epubs in the epub_content dir.) and will display the title correctly, but then will continue indefinitely spinning with a blank page. 

In some initial debug, I do not see any event being triggered for ReadiumSDK.Events.CONTENT_DOCUMENT_LOADED for the reader. This works on a desktop, but not on my iPad. I working with release 0.15 and have tried the others as well with the same result. The app is a Cordova app and I am using the InAppBrowser (but have also tried Safari with the same result) Any idea on what I not doing correctly or if this is a known problem?

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/readium-js-viewer/issues/352
