### ISSUE TITLE
Readium Chrome: Themes cause issues with readability

### ISSUE THREAD

**Issue by Kathybluefire** [readium/readium-js-viewer#226]
While doing some comparative analysis between Readium and other readers I really gave the themes a workout, and found some issues. 

Repro
Open cc-shared-culture.epub
Change the theme to night mode

**Comment by danielweck** [comment]
Fixed as part of https://github.com/readium/readium-shared-js/issues/336
via: https://github.com/readium/readium-shared-js/commit/5fbf279dbabc35131922553a8c09701c9cc120f4
