### ISSUE TITLE
MathML does not display in Firefox

### ISSUE THREAD

**Issue by becka11y** [readium/readium-js-viewer#227]
In both Windows 7 and OS X 10.10, MathML content is not displayed when using the cloud reader in Firefox.  I tested with the Linear Algebra book.

**Comment by rkwright** [comment]
Re-test with 2.5.1

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/readium-js-viewer/issues/360
(closing the other one)

See linear-algebra
http://development.readium.divshot.io/?epub=epub_content%2Flinear-algebra

See MathJax update
https://github.com/readium/readium-js-viewer/issues/262

**Comment by pkra** [comment]
MathJax has trouble accessing its global SVG object (which serves the role of a font by storing paths corresponding to character glyphs for re-use across the document).

In the console of the divshot demo try:

```javascript
cd(document.getElementById("epubContentIframe"));
MathJax.Hub.Config({SVG:{useFontCache:false}});
MathJax.Hub.Queue(["Rerender",MathJax.Hub]);
```

This should fix the issue.

To make that permanent add

```javascript
window.MathJax = {
    SVG: {useFontCache: !MathJax.Hub.Browser.isFirefox}
};
```

somewhere **before** MathJax.js is loaded.

I think the next release might fix this but it won't hurt either way.

**Comment by danielweck** [comment]
@pkra `MathJax.Hub.Browser.isFirefox` does not exist *before* MathJax.js is loaded, so there is a race condition :)

**Comment by danielweck** [comment]
@pkra I used `MathJax.Hub.Config({SVG:{useFontCache:false}});` before our existing `mathJax.Hub.Queue(mathJaxCallback);`. This fixes Firefox MathML rendering. Thanks!

**Comment by danielweck** [comment]
Fixed: https://github.com/readium/readium-js/commit/f9c0d228341292952a25b8ceaa78d2dcc1ed3968

**Comment by becka11y** [comment]
Great, thanks! Let's see what other issue I can ask for help on and have Daniel fix ;-)

**Comment by danielweck** [comment]
@becka11y well, I just incorporated @pkra 's suggested fix in a way that works in Readium ;)

**Comment by pkra** [comment]
> MathJax.Hub.Browser.isFirefox does not exist before MathJax.js is loaded, so there is a race condition :)

That's why I wrote to push it into MathJax configuration (the `window.MathJax = ...` part in my previous posting). Running that line before MathJax.js is loaded, configure MathJax correctly. But you seemed to have found another way so that's great.

**Comment by pkra** [comment]
The first set of instructions was for live debugging in the console -- sorry for the confusion.

**Comment by danielweck** [comment]
@pkra MathJax.Hub is undefined before loading MathJax.js, so I had to use a different method.

**Comment by pkra** [comment]
@danielweck d'oh! Yes, you're right -- sorry about that. I was mixing ways of configuring MathJax. 

If the problem still occurs with MathJax 2.6, then we should just move that configuration part into MathJax.js.

**Comment by danielweck** [comment]
@pkra Looking forward to MathJax 2.6, good luck with the release! :)
