### ISSUE TITLE
Missing dependency encryption_handler, breaks chrome

### ISSUE THREAD

**Issue by lambdafu** [readium/readium-js-viewer#242]
Firefox ignores this, but chrome chokes up: encryptionHandler in require_config.js points to non-existing file ../readium-js/epub-modules/epub-fetch/src/models/encryption_handler.

I changed this to encryption_handler and copied the file from the readium-js repo to lib/.  All dandy.

**Comment by danielweck** [comment]
The recent AMD-RequireJS refactoring consistently uses dependency injection across the entire source tree, so this is now an obsolete issue.
