### ISSUE TITLE
HTTP requests continue when 403 error returned (should gracefully degrade)

### ISSUE THREAD

**Issue by lambdafu** [readium/readium-js-viewer#245]
Accessing a non-exploded epub file that is forbidden (HTTP 403) causes a steady (endless?) stream of HTTP requests that hammer the server.

**Comment by danielweck** [comment]
Related: https://github.com/readium/readium-js-viewer/issues/243

**Comment by danielweck** [comment]
I am not able to reproduce in the latest version. Please check and report with more details. Many thanks!
