### ISSUE TITLE
Swipe gestures not working properly

### ISSUE THREAD

**Issue by marcelomiura** [readium/readium-js-viewer#246]
I'm testing the cloud-reader wrapped on Cordova Application and I'm having troubles with swipe gestures to change the book page. The problem occurs with pre-paginated books. I'm able to change to page only at the first time.
When removing the tag, the swipe works fine on the demo book (page-blanche)
I'm working on Android 4.4.4, on develop branch.

**Comment by danielweck** [comment]
Existing issue: https://github.com/readium/readium-js-viewer/issues/221
