### ISSUE TITLE
Loading an incompatible file hangs the application

### ISSUE THREAD

**Issue by rfilmyer** [readium/readium-js-viewer#247]
When I accidentally load a file that's not compatible with readium (eg. a PDF or JPEG), readium hangs at "examining EPUB content" and must be shut down & reopened to work.

![screenshot 2014-12-14 at 9 13 23 pm](https://cloud.githubusercontent.com/assets/5913205/5430165/3070016e-83d6-11e4-94b7-de76fce5beb1.png)

I imagine a fix would be to have an error message or a cancel dialog box.

**Comment by rkwright** [comment]
Long since fixed.  Closing.
