### ISSUE TITLE
Failed to load readium-worker.js

### ISSUE THREAD

**Issue by silviolorusso** [readium/readium-js-viewer#25]
Hello, when I try to add an epub file to the library using the "+" button, the progress bar get stuck and I have the following error in the console:

`Failed to load resource: the server responded with a status of 404 (Not Found) - readium-worker.js`

**Comment by maxfarseer** [comment]
@ryanackley - is it possible to copy uploaded epub from chrome-app (which folder?) to local copy?

**Comment by danielweck** [comment]
Hello Max, when an EPUB file is imported into the Readium Chrome app's publications library, the contents of the zip archive are extracted into a internal filesystem specific to the Chrome web browser. Users do not have direct access to the original EPUB publication. There is currently no "export" functionality in the Readium Chrome app. I created a new issue here: https://github.com/readium/readium-js-viewer/issues/699

**Comment by maxfarseer** [comment]
Hi, Daniel! Thx for replay!

My point is: I have local copy (by git clone) and I would like to inject my epub to this copy. I would like to dig into the codebase and see how you work with not easy epubs books. So, probably I will have some contribute things in future.

Do you know any way, how I can achieve this?

**Comment by danielweck** [comment]
I'm not sure exactly what you mean by "I would like to inject my epub to this (git clone) copy". Let me try to answer:

* With the cloud reader, the `epub_library.opds` index can be edited and uploaded to the server: https://github.com/readium/readium-js-viewer/tree/develop/epub_content
* With the Chrome app, "pre-loading" EPUBs in the library (at build time) is not currently possible.

Is that what you mean?

**Comment by maxfarseer** [comment]
Sorry.
My target - open custom epub book locally. Is it any way to achieve this?

**Comment by danielweck** [comment]
Ok, so your goal is to load an EPUB file from your filesystem directly into the *reader* view of the Readium Chrome app, right? (you do not want the EPUB to be imported into the app's publications library)

This is not possible. Instead, you can use the cloud reader with a local HTTP server (`npm run http`).

**Comment by llemeurfr** [comment]
or use Readium Desktop -> https://github.com/edrlab/readium-desktop which will soon be moved to the readium repo.
