### ISSUE TITLE
Generic Tooltips for page turn arrows

### ISSUE THREAD

**Issue by larsvoigt** [readium/readium-js-viewer#252]
Small cosmetics: 
At the moment it uses the native tootip but it should also use the zoomable generic tooltips like the other menu items.

**Comment by becka11y** [comment]
I believe this because the page turn arrows are not bootstrap based buttons.

**Comment by danielweck** [comment]
Suggested fix: 

Update the selector `nav *[title]` to match the arrow buttons, for example by adding `, button.page-switch-overlay-icon` (needs testing, that's just from the top of my head):

https://github.com/readium/readium-js-viewer/blob/develop/lib/ReadiumViewer.js#L61

https://github.com/readium/readium-js-viewer/blob/develop/lib/ReadiumViewerLite.js#L39

https://github.com/readium/readium-js-viewer/blob/develop/templates/reader-body-page-btns.html

**Comment by becka11y** [comment]
Closing - The fix was committed on Feb 16, 2016.
