### ISSUE TITLE
Chrome Extension Windows 7: Pagination is not correct, according to spec

### ISSUE THREAD

**Issue by Kathybluefire** [readium/readium-js-viewer#255]
Spec: 
When a Reading System renders a Synthetic Spread, the default behavior is to populate the spread by rendering the next EPUB Content Document in the next available unpopulated viewport, where the next available viewport is determined by the given page progression direction or by local declarations within Content Documents.

I created a very simple reflowable book using all property defaults. The result is that the first XHTML file (which is short) is rendered on a left-hand page and is followed by a blank right-had page. The first Chapter (second XHTML file) begins on the next left-hand page. Seems that each XHTML file is starting on a left-hand page, rather that the next available slot, as the spec says it will.

**Comment by danielweck** [comment]
That's correct, the reflowable viewport spans the entire available width, even if (visually) only the left hand side "column" of the synthetic spread is populated by content (are you aware of other reading systems implementing this correctly?). I am pretty confident that this restriction will remain for a long time in Readium, as fixing this would require very significant changes in how the reflowable view functions.

Note that as a byproduct of this limitation, Readium currently does not support mixing reflowable and fixed-layout viewports within the same visual space (I am not aware of any reading system that does though).

**Comment by Kathybluefire** [comment]
Here are JPGs which illustrate this issue. 

![pagination1](https://cloud.githubusercontent.com/assets/4503010/5963420/f0c007c8-a7a0-11e4-87d4-c5058ae54eff.jpg)
XHTML File 1

![pagination2](https://cloud.githubusercontent.com/assets/4503010/5963429/fba077c2-a7a0-11e4-801f-da33382c5363.jpg)

XHTML File 2
 
According to the spec, File 2 should start on the right hand slot next to File 1 Page Description. But, Chrome is inserting a blank right and forcing Chapter 1 to start on the next left.

**Comment by danielweck** [comment]
Closing as duplicate: https://github.com/readium/readium-js-viewer/issues/256
