### ISSUE TITLE
Toolbar Problem On Startup

### ISSUE THREAD

**Issue by nate2squared** [readium/readium-js-viewer#263]
Hi, Just wondering how I can stop this coming up every time.  Pressing X makes it go away temporarily but it always comes back.  This is happening in every browser I try it in.  Thanks.

![screen shot 2015-01-12 at 4 28 19 pm](https://cloud.githubusercontent.com/assets/8920945/5713327/115afb04-9a78-11e4-944b-573b7b8a805f.png)

**Comment by ryanackley** [comment]
Interesting. I haven't seen this before. What git branch are you using? What kind of device are you trying this on (i.e. PC, tablet, phone)?

**Comment by nate2squared** [comment]
I used the latest Git version - https://github.com/readium/readium-js-viewer.git
& Have tried on Firefox, Chrome and Safari (on the desktop, and the last two on an iPhone).

Here is the live page:
http://nclivegerard.com/cotton-reader/simpleviewer.html?epub=epub_content/cotton/

**Comment by ryanackley** [comment]
You're missing at least one of the required css files for your deployment. library.css.

Assuming you have a dev environment set up, you can create a fully deployable distribution for the web by running `grunt cloudReader` in your source directory. This will output all the required files into the build/cloudReader (or build/cloud-reader can't remember) directory. 

We have a live deployment here http://readium-cloudreader.divshot.io/index.html.

**Comment by nate2squared** [comment]
I used the "Clone into your own web server" install, I thought that might be enough like pub.js.

But this time I will use the Node method instead. Thanks for the help.

**Comment by ryanackley** [comment]
"Clone into your own web server" should work. If you used those directions, something went awry because as I mentioned before, you're missing a key file (library.css). 

I only suggested using `grunt cloudReader` because it reduces the number of files required for doing your own deployment.

**Comment by nate2squared** [comment]
Hmmm ... strange - library.css is in ./css
The Moby Dick example has the same problem.

**Comment by danielweck** [comment]
simpleviewer.html (which does not expose the library view) is broken in the master branch, have you tried the develop branch? This was fixed 3 months ago, but not yet released to master.

Also, as Ryan said, consider using the Grunt build script, but remember that unlike simpleviewer.html, the index.html application bootstrapper includes the library view (which in your case may only contain a single ebook).

**Comment by nate2squared** [comment]
Thank you for clearing this up.

**Comment by danielweck** [comment]
FYI, I added a new "cloudReaderLite" Grunt task to generate a minified / optimised build of simpleviewer.html (ReadiumViewerLite):

https://github.com/readium/readium-js-viewer/pull/264

It's just like "grunt cloudReader", but without the library view (the EPUB path must be specified directly in the URL, just like when using simpleviewer.html).

**Comment by nate2squared** [comment]
Thats great - That'll really come in handy!
