### ISSUE TITLE
ZIP download on "release" page for cloudReader(Lite) + non-minified build needs missing version.json file

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#268]
Hello @ryanackley 
The issue arose here:
https://github.com/readium/readium-js-viewer/issues/266#issuecomment-70835088

I guess the zip archive download link on the "release" page is pretty much the same as the one available on the "tree" page (I assume that the Travis Continuous Integration script uses a standard "source code package" GitHub feature?):

https://github.com/readium/readium-js-viewer/releases
https://github.com/readium/readium-js-viewer/archive/0.16.0.zip

https://github.com/readium/readium-js-viewer/tree/develop
https://github.com/readium/readium-js-viewer/archive/develop.zip

Right now, there does not seem to be an easy way for a visitor / user to download a ready-to-use build artefact. They are forced to pull the source code using git, install npm, grunt via the command line etc. in order to (at least) generate the `build/version.json` file required by `index.html` and `simpleviewer.html`. Of course, if they are able do that, they can also easily invoke `grunt cloudReader` or `grunt cloudReaderLite` to generate a minified build...

...but for non-technical users, it would be nice to provide a ready-built package, perhaps on the release page alongside the green "Readium.crx" download button?

I would suggest that the new zip file contains everything the existing source-code archive already contains, plus a pre-built `cloudReader` and `cloudReaderLite` in the `build` folder. This way, users would have the option to use the non-minified `index.html` and `simpleviewer.html`, as well as the optimised deploy-friendly builds (`build/cloud-reader/index.html` and `build/cloud-reader-lite/index.html`).

UPDATE: as @ryanackley pointed out, no need for the `readium-js` > `readium-shared-js` submodules source code, as the `lib/Readium.js` file aggregates the whole tree in minified form.

What do you think?

**Comment by ryanackley** [comment]
It probably isn't too much work. What is the purpose of including the rest of the source code? Seems like technical people would go the normal route through git and initialize the tooling. I would also do separate artifacts for cloudReader and cloudReaderLite. 

Does just cloning (without submodules) and running a web server not work anymore? If it doesn't, we should fix that first since this is a gotcha for technical people as well. Also, pre-packaging `grunt cloudReader` just increases performance. The same technical hurdles still exist:

1. Run webserver in a directory
2. open browser to correct page.

**Comment by danielweck** [comment]
Ah yes sorry, I forgot about the giant `lib/Readium.js` pre-built `readium-js` artefact which is persistent in the git repository. There should indeed be no need for the `readium-js` `readium-shared-js` submodule(s).
However, the non-minified versions of readium-js-viewer (`index.html` and `simpleviewer.html`) require `version.json` in the `build` folder, which is generated by a simple `grunt` command ... but non-technical users will not go through the hassle of installing NodeJS, Grunt, etc. so we need to decide whether to include `version.json` in the git repository, or only in the zipped releases.

I agree about separating cloudReader(Lite) into two distinct build artefacts. We should probably offer  only these two downloads, excluding the non-minified version(s) of Readium which should only be used by developers (who therefore know how to setup git+Node+grunt, etc.).

**Comment by danielweck** [comment]
Ah, @ryanackley reminded us of "UnpackagedVersioning" (I'll check this, to see if there's a bug there, potentially a regression bug):
https://github.com/readium/readium-js-viewer/blob/develop/lib/versioning/UnpackagedVersioning.js

**Comment by danielweck** [comment]
(sorry about the verbosity of this message, that's for future reference when someone revisits the issue :) )

Thanks @ryanackley , `UnpackagedVersioning` is now correctly used, specifically in the case of the non-minified `index.html` and `simpleviewer.html` app launchers (only they include `extend_require_config.js`, the optimised/aggregated builds do not):
https://github.com/readium/readium-js-viewer/commit/f61c934f9a0ec2ac881f9344e2774f1fa99b1f7d

Thanks to the pre-generated `lib/Readium.js` single-file (Git-versioned) build of `readium-js`, and thanks to `UnpackagedVersioning`, Readium developers / testers do not need to initialise the submodules (deep dependencies `readium-js` -> `readium-shared-js`), they can just work directly from a shallow clone of the `readium-js-viewer` repository.

Note that the *proper* `cloudReader`, `cloudReaderLite` and `chromeApp` builds still use `PackagedVersioning`, via RequireJS configuration overrides in the Grunt scripts:
https://github.com/readium/readium-js-viewer/blob/develop/grunt/requirejs.js#L33

**Comment by mahag** [comment]
Still not being to open .zip file from cloud-reader with new build folder. It still doesnt contain lib folder, could it be from it?

**Comment by danielweck** [comment]
Readium only supports the `*.epub` file extension, not `*.zip`.
That being said, I tested your HTTP server URL and it still does not work :(

Okay (expanded / uncompressed EPUB):
`http://www.xxxxx.com/Readium_Build/cloud-reader/?epub=epub_content/dana`

Fail (single-file / compressed EPUB):
`http://www.xxxxx.com/Readium_Build/cloud-reader/?epub=epub_content/dana.epub`
There are no messages in the console, and the minified code is quasi-impossible to debug/step-through. I wonder if the problem stems from your HTTP server configuration? (mime type? "application/epub+zip" ? I'm not sure...)

**Comment by danielweck** [comment]
With the AMD-RequireJS refactoring and the NPM build workflow ('node_modules' dependencies), it is quite clear that the zipped Git source tree does not provide a runnable app. Only `readium-shared-js` contains pre-built libs (for use in native app launchers):
https://github.com/readium/readium-shared-js/tree/develop/build-output
