### ISSUE TITLE
missing lib/thirdparty/inflate.js in cloud reader builds

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#270]
Can we put in epub_content zipped files or .epub files without unzipping them and pass them to readium to show content of the ebook ?

**Comment by danielweck** [comment]
Yes, this works fine:

`http://IP_ADDRESS:PORT/?epub=epub_content/ebook.epub`

(I have just successfully tested this with several EPUBs)

Note that your HTTP server must support the "byte range" protocol. Most do, including the one used during `readium-js-viewer` development (Node Express) which is started when invoking the `grunt` command without parameters.

**Comment by mahag** [comment]
Does it work for domain.com instead of ipaddress:port ?

**Comment by danielweck** [comment]
Are you able to privately share your EPUB?
`daniel.weck@gmail.com`

**Comment by mahag** [comment]
readium pagehttp://www.neelwafurat.com/ReadiumCloudReader_Full-Lite/cloud-reader/index.html?epub=epub_content/dana.epub
epub file
http://www.neelwafurat.com/ReadiumCloudReader_Full-Lite/cloud-reader/epub_content/dana.epub

Date: Mon, 26 Jan 2015 04:15:47 -0800

**Comment by ryanackley** [comment]
@danielweck looks like the cloudreader distro needs to add files for the unzip webworker. Not super familiar with how readium-js/readium-shared-js does unzipping but I assume it's similar to viewer. The unzip happens in a web worker and this uses a separate file. i.e. it can't be part of the one minified file.

**Comment by danielweck** [comment]
Thanks @ryanackley !
@mahag thank you for sharing the EPUB. It loads fine via the Node-Express development server (`grunt` build task), using the default `index.html` or `simpleviewer.html` apps. However, as @ryanackley pointed out, it looks like some files are missing from `build/cloud-reader/index.html` and `build/cloud-reader-lite/index.html` (which are minified builds). I am seeing this in the console:
```
lib/thirdparty/inflate.js
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by mahag** [comment]
Can you plz send me missing files? I did already use zipped build of Readium from your side sent by mail since am not being able to use grunt

**Comment by danielweck** [comment]
@mahag as a temprary measure, you can manually copy the missing file into `cloud-reader/lib/thirdparty/inflate.js` on your server:
`https://github.com/readium/readium-js-viewer/blob/develop/lib/thirdparty/inflate.js`

**Comment by danielweck** [comment]
I am about to publish a Pull Request that fixes the Grunt build.

**Comment by danielweck** [comment]
Hello @ryanackley could you please review this Pull Request? (feel free to edit the code in the feature branch). Thanks!

https://github.com/readium/readium-js-viewer/pull/271/files

**Comment by mahag** [comment]
I did copy the file  into cloud-reader/lib/thirdparty/inflate.js on my server, but still not working

**Comment by danielweck** [comment]
Fixed in Pull Request: https://github.com/readium/readium-js-viewer/pull/271

**Comment by danielweck** [comment]
@mahag I am sending you an updated zipped build of both cloud-reader and cloud-reader-lite (separate email), containing this fix.

@ryanackley , any thoughts on how to move forward with this: https://github.com/readium/readium-js-viewer/issues/268#issuecomment-70848059 ? I think we only need to upload the minified builds `cloudReader` and `cloudReaderLite` to the release page https://github.com/readium/readium-js-viewer/releases (generated via Travis CI), no need to include the missing `build/version.json` for `index.html` and `simpleviewer.html` as in this case people are likely to know how to install + use Grunt anyway.
