### ISSUE TITLE
Search in readium over book

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#275]
Is there an option to search for text over book content,over all pages in all chapters?
Currently i don't have this option.

**Comment by danielweck** [comment]
We already have an issue recorded for that:
https://github.com/readium/readium-js/issues/17

We do not have a concrete plan / schedule for implementing this feature though. It all depends on programmer resources (+ developer contributions). Right now there are a bunch of other high-priority issues to address, so watch this space!

**Comment by naveen1941** [comment]
How to implement text search over entire book using norch.js?

**Comment by alaghusun60** [comment]
How to implement text search over entire book on readium. Which version previosly integrated. I checked all version. Still i cant able to check that
