### ISSUE TITLE
Installation error?

### ISSUE THREAD

**Issue by acepub** [readium/readium-js-viewer#277]
Hi,

We're trying to setup readium.js for our site.

We create ebook for independent authors so would like to have an easy way through which clients can preview their ebooks. However, readium does not seem to be loading up - we get a spinning dotted wheel, and the navigation controls appear to be broken: http://acepub.com/readium-js-viewer/simpleviewer.html

The site is hosted on HostGator. What are we doing wrong?!

Team acepub

**Comment by ryanackley** [comment]
See https://github.com/readium/readium-js-viewer/issues/263

Use the develop branch. Sorry this isn't easier to figure out.
