### ISSUE TITLE
Unable to highlight text fragments inside the "epubContentIframe"

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#278]
Submitted by Lars Voigt: <lars.voigt@dzb.de>

Platform/Browser:  CloudReader, All platforms.

I try to highlight text fragments (single words) inside the
"epubContentIframe".

$("#epubContentIframe").contents().find('body').highlight("text");

I use the  jQuery highlight plugin and I think it works fine.
Because I have debug the iframe dom manipulation and it looks good.
But at the viewport I can see that the text should be highlighted is lost.

Should I do more to update the viewport?
Or there a cleaner way to do that?
Readium-JS API?

**Comment by danielweck** [comment]
@larsvoigt the jQuery highlight plugin inserts spans in the markup in order to "select" character ranges. These spans are not blacklisted by the CFI backend, so this is a strongly discouraged practice (e.g. it potentially breaks bookmarks, etc,). So, ideally you would be able to customise the CFI blacklists with your own "highlight" class, but as it turns out there is no easy way to do this (plus, there are blacklist API "holes" in the current Readium codebase). More information here: https://github.com/readium/readium-cfi-js/issues/30

What you could do is use Readium's existing highlighting mechanism, which does not rely on additional / interspersed span markup. Instead, semi-transparent divs are overlaid on top of the document text, and the positions/dimensions are updated automatically when the page is reflowed (window resized, font enlarged, etc.). See ` addHighlight(CFI, id, type, styles)`:
https://github.com/readium/readium-shared-js/blob/develop/lib/annotations_module.js#L565

**Comment by larsvoigt** [comment]
Thank you @danielweck for your fast response and help. The facts sounds good.
I will give you feedback as far as possible.

**Comment by danielweck** [comment]
Using the new plugins architecture:

https://github.com/readium/readium-js/blob/develop/dev/index.js#L109

```javascript
            ReadiumSDK.on(ReadiumSDK.Events.PLUGINS_LOADED, function(reader) {

                reader.plugins.annotations.initialize({annotationCSSUrl: readerOptions.annotationCSSUrl});

                reader.plugins.annotations.on("annotationClicked", function(type, idref, cfi, id) {
                    console.log("ANNOTATION CLICK: " + id);
                    reader.plugins.annotations.removeHighlight(id);
                });

                reader.plugins.annotations.on("textSelectionEvent", function() {
                    console.log("ANNOTATION SELECT");
                    reader.plugins.annotations.addSelectionHighlight(Math.floor((Math.random()*1000000)), "highlight");
                });

            });
```

**Comment by rkumar2236** [comment]
I am able to highlight text in reflowable epubs but not for fixed layout, please help.

**Comment by hajarghaem** [comment]
Dear Daniel,
I can highlighted selected text. But it is not save or stored in Readium.
I have been working on a way to somehow save my annotations in a separate file (in a right position using CFI ) that can be shown as a layer on top of each visible content of the epub3-based book in Readium.
Could you please let me know what is your suggestion?

Thanks in advance,
Kind regards,
Hajar

**Comment by danielweck** [comment]
At this stage there is no proper built-in "annotation" feature in Readium. You would need to extend the "highlight" plugin, or even better: create a new plugin that would implement a persistence backend (save to / load from IndexedDB, LocalStorage etc.) and you would also need a front-end to handle user interaction / edits (delete annotation, change text, etc.)
This project is very keen to receive open-source contributions, so let us know if you would like to participate.

**Comment by hajarghaem** [comment]
Thank you very much Daniel.
We are interesting to contribute to this project. Please provide me more information.
Could you  please let me know if yo have started this project? I saw somewhere else a comment that Readium is going to make the highlight feature by the end of the year (2016), is this right?

Thanks in advance,
Kind regards,
Hajar

**Comment by danielweck** [comment]
Hello, regarding your potential open source contributions, please ask Ric Wright @rkwright
Regarding highlights, the plugin is available in the develop branch of readium-shared-js, but it is still experimental in the sense that it hasn't been tested enough to be considered production-ready. We are not able to commit to a firm deadline because this is an open source project mostly run by volunteers. We are aware that commercial vendors who use Readium as the foundation / engine for their reading systems usually implement their own annotation framework as "value add" / unique product selling point (when that's the case, the code is likely to remain proprietary).

**Comment by danielweck** [comment]
Regarding copy/paste disabling, this could be a cross-platform generic readium-shared-js plugin, and native apps developers could choose to use their own solution if they wanted to. We are aware that existing Readium-based vendor apps implemented their own protection measures to secure the contents. No open-source code as far as I know, but it probably is pretty trivial JavaScript event handling (preventDefault()).

**Comment by hajarghaem** [comment]
Hi @danielweck  and @larsvoigt 
I have been working on highlighting text based on CFI.
I could integrate epub-search engin in Readim, as search function.
Now I can extract CFI of a search keyword in json format.
Now I need to highlight my search keyword in the readium. So it is not based on selected text.
The only guidance that I could find is https://docs.google.com/document/d/1O8V0C2XaynobpDApnQvGcfgE4aCDj7BiZ5W-4eOupIk/edit#heading=h.nlvujjtmpl2m. But I could not use it to highlight my searched keyword.
For example my extracted information in jsn format is:
{
    "filename" : "accessible_epub_3",
    "epubTitle" : "Accessible EPUB 3",
    "href" : "ch01.xhtml",
    "baseCfi" : "/6/16[id-id2611884]!",
    "id" : "id-id2611884",
    "cfis" : ["/6/16[id-id2611884]!/4/2[introduction]/4,/1:22,/1:23"]
}
and I tried to work on cloud-reader.
Could you please let me know how should be the right code in order to highlight my example:
I tried to adopt "S.reader.plugins.highlights.addSelectionHighlight(Math.floor(1e6 * Math.random()), "test-highlight")" from
"        r(".icon-annotations").on("click", function () {
            S.reader.plugins.highlights.addSelectionHighlight(Math.floor(1e6 * Math.random()), "test-highlight")
            //S.reader.plugins.highlights.addSelectionHighlight('id-id2611884', "/4,/1:22,/1:23", 123, "highlight");
        });"

But my problem is how do I need to make a link between Math.floor(1e6 * Math.random()) and  'id-id2611884', "/4,/1:22,/1:23", 123,
Or if you could propose me know other ways!

**Comment by danielweck** [comment]
@hajarghaem you want to use `addHighlight()`, not `addSelectionHighlight()`.
See function parameters:
https://github.com/readium/readium-shared-js/blob/develop/plugins/highlights/manager.js#L155
...and for your information, here is the function logic for a given spine item document:
https://github.com/readium/readium-shared-js/blob/develop/plugins/highlights/controller.js#L151

PS: the `Math.random()` call creates some kind of unique identifier for the newly-created highlight (see the `id` parameter of both "add highlight" functions).

**Comment by hajarghaem** [comment]
@danielweck 
Thank you very much Daniel.
When use "S.reader.plugins.highlights.addHighlight("/4/2/1:22,/1:23", 'id-id2611884', 123, "test-highlight");" inside:
r(".icon-annotations").on("click", function () {
		//S.reader.plugins.highlights.addSelectionHighlight(Math.floor(1e6 * Math.random()), "highlight")
		S.reader.plugins.highlights.addHighlight("/4/2/1:22,/1:23", 'id-id2611884', 123, "test-highlight");
		});
It does not annotate the text.

Could you please let e know if I need to change other parts?
Thanks in advance,
Hajar

**Comment by hajarghaem** [comment]
Hello @danielweck,

I tried to enable or disable addSelectionHighlight function via "manager.js and/or controller.js", but nothing changed. It seems that there is not connection between "controller.js and manager.js" with cloud-reader (readium-js-viewer_all.js). 
I can controller my annotation when I use "npm run http", but not when I use "node node_modules/http-server/bin/http-server -a 127.0.0.1 -p 8080 -c-1 .."

**Comment by danielweck** [comment]
hello, did you build readium-js-viewer from source, and from the develop branch? remember, you need to ensure that the configuration in readium-shared-js/plugins/plugins.cson includes the highlighter plugin.

**Comment by hajarghaem** [comment]
I followed instruction "https://github.com/readium/readium-js-viewer".
as I said I can control when I use "npm run http". But I cannot control highlights in cloud reader.

**Comment by danielweck** [comment]
what branch?
what is your plugins.cson configuration?

**Comment by hajarghaem** [comment]
my plugins.cson includes:
# You may add the plugins that should be included here.
plugins: [
 # 'highlights'
 # 'example'
]

# you may override this configuration by creating a file called plugins-override.cson, e.g.:
#plugins:
#    include: [
#        'example'
#    ]
#    exclude: [
#      'highlights'
#    ]

**Comment by hajarghaem** [comment]
I can highlight in cloud reader but the problem is I cannot control or manage it!

**Comment by danielweck** [comment]
#
the sharp character indicates a comment in the CSON syntax. you must uncomment the line for the highlights plugin.
then use "npm run http" to try the cloud reader from the raw source tree, or "npm run dist+sourcemap" to build the app so you can upload it to your HTTP server.

**Comment by danielweck** [comment]
PS: the highlighter plugin does just that: it highlights text selections. you must implement your own logic on top of this basic functionality, for example to support annotations.

**Comment by hajarghaem** [comment]
Thanks I try your solution and then update you.
For the highlight, I extract CFI via epub-search engine ( fetch this information in a json file). Then in the cloud-reader I added an even in order to activate addHighlight function with my CFI information. Something like we have already had for addSelectionHighlight() in:
 r(".icon-annotations").on("click", function () {
		S.reader.plugins.highlights.addSelectionHighlight(Math.floor(1e6 * Math.random()), "highlight")
		});

**Comment by danielweck** [comment]
When you add your code, do you edit the original (raw) files in the source tree, or do you patch the JavaScript bundles created by RequireJS (build-ouput folder)?
Or, do you just add JS code in reader.html?

My recommendation is to customise the original codebase, iteratively test with "npm run http", and compile the final application with "npm run dist+sourcemap" (to deploy / upload to a real HTTP server)

**Comment by hajarghaem** [comment]
for the moment I just add my code into dist/cloud-reader/script/readium-js-viewer_all.js

**Comment by hajarghaem** [comment]
I am going to start everything from scratch and "develop" branch.

**Comment by hajarghaem** [comment]
@danielweck 
The readium-js-viewer_all.js is created after "nppm run dist". Could you please let me know where can I add my code (instead of  readium-js-viewer_all.js) before building dist?

**Comment by danielweck** [comment]
Obviously, the answer to your question depends on what you are trying to achieve, but assuming you want to add behaviours after a document (spine item) is loaded and paginated / rendered, then a good starting point would be listen to the `PAGINATION_CHANGED` event, as done here in the "reader" view:
```javascript
readium.reader.on(ReadiumSDK.Events.PAGINATION_CHANGED, function (pageChangeData) {
...
```
https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L451

**Comment by hajarghaem** [comment]
Thanks @danielweck , 
What I want to do is for example: I want to add a button as search button, something like highlight button or library button in readium navbar. (I then am going to define some event for these buttons). So far I added such codes directly in my dist/cloud-reader/scripts/readium-js-viewer_all.js
In fact I want  now to add my code that will be shown again in dist/cloud-reader/scripts/readium-js-viewer_all.js, after build.

**Comment by hajarghaem** [comment]
I added my codes in different files: src/css/viewer.css , \src\templates\reader-navbar.html, ...

**Comment by hajarghaem** [comment]
Hi @danielweck and @larsvoigt ,
I integrated epub-search in cloud-reader (from the original (raw) files in the source tree ). I also can simply highlight my search keywords.
There are still an issue:
1- this is related to PAGINATION_CHANGED. When I am in a page that includes my search word then I can it is highlighted but not other same words that are in other pages (not current page). I have been looking for a way to highlight my search words even in other pages (not current visible page). 

Thanks in advance,
Hajar

**Comment by danielweck** [comment]
@hajarghaem "pages" for reflowable documents, or fixed layout?
If fixed-layout, then of course only the visible page (or two pages) can display highlights.
If reflowable documents, then there may be several "pages" (CSS columns) within the same spine item document, and any number of text highlights can be created, even in pages that are not visible.

**Comment by larsvoigt** [comment]
@hajarghaem. 
``` javascript 
// open the "page" with the cfi of your keyword
readium.reader.openSpineItemElementCfi(...); 
// see daniels hint
readium.reader.on(ReadiumSDK.Events.PAGINATION_CHANGED, function (pageChangeData) {
...
hightlight(cfi)
});
```

**Comment by danielweck** [comment]
@hajarghaem , as @larsvoigt said, you can navigate to any CFI location using `readium.reader.openSpineItemElementCfi()`, or at the time the EPUB is loaded. See here for a more complete answer:
https://github.com/readium/readium-js/issues/143

**Comment by hajarghaem** [comment]
Thanks @danielweck
regarding you previous comment "If reflowable documents, then there may be several "pages" (CSS columns) within the same spine item document, and any number of text highlights can be created, even in pages that are not visible." 
I cannot highlight anything in reflowable documents! Even with the simple highlight button?

**Comment by danielweck** [comment]
Yes, unfortunately there is a bug preventing the highlights plugin to function properly in the scroll and fixed layout views. See:
https://github.com/readium/readium-shared-js/issues/280
and
https://github.com/readium/readium-shared-js/issues/315

**Comment by hajarghaem** [comment]
Hi @danielweck, 
Thanks for your time and responses.
I am going to create a table of content based on my search results. 
I tried different files (e.g., package_document.js, manifest.js, content_document_fetcher.js ) and functions (e.g., generateTocListDOM) to change the order of table of content based on my conditions. But I have find the right place to apply my codes. Could you please let me know where I can change the order of table of content, and linking the TOC and their corresponding  html page of the book?
Thanks in advance!

**Comment by claudebaking** [comment]
@danielweck https://csser.space/questions/emphasize-the-active-page-in-the-main-menu
