### ISSUE TITLE
How to protect the epubs

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#281]
Since Readium doesnt support DRM-protected epubs, is there a way to protect epubs opened through cloud-reader-lite basic view ?
Epubs are place on my server and user will be able to view them on google chrome through index.html provided by readium. With a little work around user can download epub file, since it is a bit clear in url provided.Is there a way to prevent it from being downloaded?or get it protected?

**Comment by danielweck** [comment]
The C++ native ReadiumSDK has an API to handle encrypted media resources, but ReadiumJS does not provide anything out-of-the-box. DRM is out of scope in ReadiumJS, a far as I know.

You may implement some kind of basic obfuscation mechanism by using random file names/paths, but ultimately a "clever" user can easily write an automated script to retrieve the contents of the entire ebook, just by scanning the OPF manifest items.

**Comment by mahag** [comment]
I tried to check ReadiumSDK for windows but couldnt find any tutorial on how to use it.
This is the file i was checking
https://docs.google.com/document/d/1DphaTO2fu7mQoBKalzyfphIlOB2Ncp7yHbIbbti92CE/edit?pli=1#heading=h.hm94u5pkvviu

**Comment by danielweck** [comment]
Have you tried this branch?

https://github.com/readium/SDKLauncher-Windows/tree/feature/feature_revised_launcher

**Comment by mahag** [comment]
After downloading .zip of this branch, what should i do ?

**Comment by danielweck** [comment]
I strongly recommend using Git to clone the main repository as well as its submodules. I doubt that the zip archive contains the required dependencies.
Then, simply use Visual Studio to compile + run the app.

**Comment by rkwright** [comment]
This is a github deficiency.  If your repo contains submodules, then the automatically created zip lacks the submodules.  This deficiency was confirmed by github support.  We have notices in the readme alerting users to this problem, but clearly the alert must be missing from some of the repos.  I will check.

**Comment by rkwright** [comment]
I have updated the repos with a warning about not using the zip archive. However, this is in the release/0.17 branch and the Windows feature branch, so it won't be in master or develop until the release is complete.
