### ISSUE TITLE
Bookmarks and highlights

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#282]
Does readium solution provide the ability to place a bookmark or highlight over a book while reading it ? Currently with what i have , i dont have the option to do so. Do i need to change anything ?

**Comment by danielweck** [comment]
Hello @mahag , see:

`ReadiumSDK.Views.ReaderView.bookmarkCurrentPage()`:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L959

`ReadiumSDK.Views.ReaderView.addSelectionHighlight ()`:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L1202
