### ISSUE TITLE
Optimisation: Hogan Mustache templates precompiled at build time (hgn! RequireJS processor)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#297]
It looks like we should be able to optimize the build by using the `stubModules` and `excludeHogan` directives?

https://github.com/readium/readium-js-viewer/blob/develop/grunt/requirejs.js

```
    stubModules : ['text', 'hgn'],

    pragmasOnSave : {
        excludeHogan : true
    }
```

Official `requirejs-hogan-plugin`:
https://github.com/millermedeiros/requirejs-hogan-plugin/blob/master/test/build.js

Readium's `hgn.js`:
https://github.com/readium/readium-js-viewer/blob/develop/lib/thirdparty/hgn.js

Readium's `hogan.js`:
https://github.com/readium/readium-js-viewer/blob/develop/lib/thirdparty/hogan.js

**Comment by ryanackley** [comment]
This is already done seamlessly by hgn.js. It's a requirejs plugin. When you run everthing in the browser expanded, the templates are compiled on the fly. When you run requirejs (or run it via grunt in our case), it precompiles the template into javascript. 

Is that what you had in mind or am I missing something?

**Comment by danielweck** [comment]
The `stubModules` and `excludeHogan` configuration directives are recommended by `hgn.js` (see links in the descripton above). It looks like we can trim the Readium app payload by telling the `r.js` optimizer to skip the unnecessary Hogan bits (given that the templates are already compiled). In the expanded case (no RequireJS optimization / aggregation), naturally these `r.js` settings have no effect, and the full Hogan compiler needs to be part of the runtime.

**Comment by danielweck** [comment]
Fixed in RequireJS refactoring:

`stubModules: ['hgn', 'i18n']`

https://github.com/readium/readium-js-viewer/blob/develop/build-config/RequireJS_config_single-bundle.js#L32

https://github.com/readium/readium-js-viewer/blob/develop/build-config/RequireJS_config_single-bundle_LITE.js#L32
