### ISSUE TITLE
Why MathML dose not work ? 

### ISSUE THREAD

**Issue by wzhsunn** [readium/readium-js-viewer#298]
I remember I ask this question and you answer it that [readium-js-viewer](https://github.com/readium/SDKLauncher-Android/issues/57) (ReadiumJS  ?) support mathml or maybe I am wrong ?

**Comment by danielweck** [comment]
MathML rendering is supported via MathJax, and as you can see it works fine here:
http://readium-cloudreader.divshot.io/?epub=epub_content%2Flinear-algebra
(public deployment of the Readium "cloud reader", built from the 'develop' branch)
Please feel free to reopen this issue if MathML still fails on your end, so we can try to help.
Thanks!

**Comment by rkwright** [comment]
Note that MathML does NOT work on Windows as the Windows platform is lagging behind the other platforms.  We are working to resolve this.

**Comment by danielweck** [comment]
Good point @rkwright , here is the existing issue in the correct repository: https://github.com/readium/SDKLauncher-Windows/issues/8

@wzhsunn feel free to file a new issue if you need to, or otherwise please add comments in the existing issue's discussion thread. Thanks!

**Comment by becka11y** [comment]
Note the MathML is not working in Firefox - I suspect because Firefox supports MathML natively?  I thought there was an issue for this, I will go look.

**Comment by wzhsunn** [comment]
Thank you all replay so quickly. 
I try the develop branch it work well .
Last time I used the master that dose not work .
