### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by asethia** [readium/readium-js-viewer#299]
This is not an issue, but I am not sure where I can find feature list provided by readium-js or readium-js-viewer.

Regards,
Arun

**Comment by rkwright** [comment]
In the past, we used Trello, but maintaining both Trello and a parallel list in the github issues has proved more time than I have.  Still working to find a reasonable solution.

**Comment by asethia** [comment]
thanks

I am not able to find how I can run simple demo from my laptop, similar to http://readium.github.io/readium-js-viewer/?epub=epub_content%2Faccessible_epub_3 

I could able to run simple viewer http://localhost:8080/simpleviewer.html?epub=epub_content/linear-algebra 

Regards,
Arun

**Comment by danielweck** [comment]
There are setup instruction in README.md:
https://github.com/readium/readium-js-viewer/blob/master/README.md

Once you have NodeJS, Grunt, and npm install'ed, just invoke `grunt cloudReader` (check out the output in the build folder), and run `grunt` if you want to use the dev HTTP server ( http://localhost:8080/build/cloud-reader/index.html )

**Comment by asethia** [comment]
Thanks Daniel for your help.

I run following commands:

git clone https://github.com/readium/readium-js-viewer.git 
npm install -g grunt-cli
npm install
grunt cloudReader

I could able to see build directory having following folders:

1. css
2. fonts
3. images
4. scripts
and index.html.

I could not find readium-all.js file any where, so when I browse index.html it is not giving any output.


Regards,
Arun

**Comment by danielweck** [comment]
`readium-all.js` should be in the `build/cloud-reader/scripts` folder.
Don't forget to add EPUBs in `epub_content` and to populate `epub_library.json` (or just copy/paste https://github.com/readium/readium-js-viewer/tree/develop/epub_content from your local `readium-js-viewer` git clone), and remember that you can edit the URL by hand to point to another folder, e.g. `http://localhost:8080/?epub=PATH/TO/EPUBS/my-ebook.epub` or `http://localhost:8080/?epub=PATH/TO/EPUBS/my-ebook-expanded`

**Comment by davedmiller** [comment]
I too have been trying to get a local copy of Readium working on my Windows 8.1 desktop machine.  I have Node.js v12 installed, I also have grunt-cli installed, I have cloned the Readium-JS-Viewer Project and run the commands:
1. npm install
2. grunt

When I point my browser at:  

http://localhost:8080/simpleviewer.html?epub=epub_content/moby_dick

I get this:

![c](https://cloud.githubusercontent.com/assets/689057/6741760/83e48bba-ce47-11e4-978c-495075096c00.png)

The Chrome Browser console gives me this:

![c1](https://cloud.githubusercontent.com/assets/689057/6741921/cfb81416-ce48-11e4-8150-b611e7c146e5.png)

I must be missing something in the directions.  Any ideas?  

Thanks

**Comment by danielweck** [comment]
Hello @davedmiller this doesn't look like the develop branch, am I correct?

`jquery.js` vs. `jquery-1.11.0.js` naming convention, see:

https://github.com/readium/readium-js-viewer/blob/develop/lib/thirdparty/jquery.js

**Comment by davedmiller** [comment]
@danielweck, you are correct...it is the 'master' branch.  Which branch would you recommend for a good stable experience?

**Comment by asethia** [comment]
@danielweck , I could find readium-all.js in  build/cloud-reader/scripts folder, copied same from http://readium.github.io/readium-js-viewer/?epub=epub_content%2Faccessible_epub_3 

What could be reason for not having this part of grunt cloudReader?

**Comment by asethia** [comment]
one more thing, we have index.html along with simpleviewer.html, why that index.html is not giving output similar to build/index.html.

**Comment by asethia** [comment]
@danielweck  awesome I was using master branch, went through previous issue list and now tried with develop branch ... it is working thanks .. this is awesome work

**Comment by danielweck** [comment]
@davedmiller as per the link I posted (develop branch). Let us know if you still run into problems. I am successfully using the Git/Node/NPM/Grunt toolchain under Windows8.1, and I use GitShell as my main terminal (although I also tested GitBash, Cygwin, and PowerShell in addition to the default DOS box).

**Comment by danielweck** [comment]
@asethia good to hear that you got it working. FYI:
`index.html` is the same as `build/cloud-reader/index.html` (`grunt cloudReader`)
`simpleviewer.html` is the same as `build/cloud-reader-lite/index.html` (`grunt cloudReaderLite`, no library functionality, just the reader)
...except that the `build/**` options are better because they are minified/optimized builds of readium-js-viewer, ready for uploading to proper web server.

**Comment by davedmiller** [comment]
@danielweck, after several more attempts to get this working, I am still getting the same result.  

I have been following these steps, as enumerated on github under the 'develop' branch readme.md.

    Initialize your repository
    
    ReadiumJS uses git submodules to embed other repositories and it uses Node.js and associated tools and libraries. Do the following steps to be up and running:

    Install Node.js (details depend on your operating system)
    Install the Grunt build tool using the command line: npm install -g grunt-cli (requires at least version 0.4.4)
    From the command line run git clone https://github.com/readium/readium-js-viewer.git
    From the command line run cd readium-js-viewer
    From the command line run git submodule update --init --recursive
install Node.JS
    From the command line run npm install -g grunt-cli
    From the command line run npm install (in the readium-js-viewer directory)
    From the command line run cd readium-js
    From the command line run npm install (a second time in the readium-js directory)
    From the command line run cd ..
    You should now be able to run the grunt commands specified below.

At this point I run grunt and launch the page with: 

 http://localhost:8080/simpleviewer.html?epub=epub_content/moby_dick 

After cloning the repository I am in the 'master' branch.  So I have inserted a 

    git checkout -b develop 

into the above steps, just after cloning.  But this seems to make no difference.

Maybe there is something wrong with my node install...I can try that next.  Any other ideas are appreciated.

Thanks,

@davedmiller

**Comment by asethia** [comment]
@danielweck  Please let me know if I can make use bookmark,  scroll pages, "go to specific page", highlight text, etc. If yes how I can get same via toolbar.

**Comment by davedmiller** [comment]
With some persistence, and I suppose I should have known this all along, it seems like the key is to switch to the 'develop' branch for both the readium-js-viewer and readium-js modules.  Cloning the repositories leaves one in the 'master' branch which seems to have some issues.

At least, this is why I think it is now up and running :-)

Thanks.

**Comment by danielweck** [comment]
@davedmiller yeah, git submodules are super useful, but they also introduce some pain points. You have to switch to the desired branch in *all* repositories (e.g. `git checkout develop`):

**readium-js-viewer**
>
readium-js-viewer/**readium-js**
>
readium-js-viewer/readium-js/epub-modules/epub-renderer/src/**readium-shared-js**

(this deep-nested folder structure also adds some overhead when navigating into the repos)

**Comment by danielweck** [comment]
@asethia 
Get bookmark / current reading location:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L959
Open page request:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L729
Create selection highlight:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L1202

(please search the `readium-js-viewer` codebase to figure out how to invoke those API methods)
