### ISSUE TITLE
Chrome / Opera video problems

### ISSUE THREAD

**Issue by duanwalker** [readium/readium-js-viewer#310]
When Layout Scroll Mode set to auto no video is visible above the player(just white space) and the player itself does not respond to anything. However, if Scroll Mode is set to Continuous the videos work correctly.

![in continuous](https://cloud.githubusercontent.com/assets/7536426/6943473/576048bc-d85c-11e4-807d-19bd07c99d47.PNG)
![in auto](https://cloud.githubusercontent.com/assets/7536426/6943476/592bbcda-d85c-11e4-822d-fd423ae18eb8.PNG)

**Comment by duanwalker** [comment]
Note: this was discovered by one of our interns testing the cloud reader and seems to occur in win 8.1 and Android 4.4.4

**Comment by rkwright** [comment]
Is this different that the issue here:   https://github.com/readium/readium-js-viewer/issues/265

Or just a manifestation of the same bug?

**Comment by duanwalker** [comment]
seems like the same issue. 
ill be sure to check if an issue has been posted already in the future.

**Comment by rkwright** [comment]
Closing as duplicate
