### ISSUE TITLE
Cloud reader is not supported in Safari for Windows

### ISSUE THREAD

**Issue by duanwalker** [readium/readium-js-viewer#311]
does not work at all...

![safari](https://cloud.githubusercontent.com/assets/7536426/6968886/47d9a1f4-d938-11e4-8c90-e7c4f0097fc0.PNG)

**Comment by ryanackley** [comment]
@duanwalker  Apple no longer maintains Safari for Windows. The last available version of Safari for Windows is 5.1.7 released in 2012. By contrast, the Mac version is up to 8.x.
