### ISSUE TITLE
Question: embedded reader, off-line reading.

### ISSUE THREAD

**Issue by davedmiller** [readium/readium-js-viewer#312]
Is there a way to specify for simpleviewer.html that an epub can be found in the browsers local storage?  I am looking for a way to enable 'off line' reading.  Other suggested approaches may be fine.

**Comment by danielweck** [comment]
What about this?
https://github.com/readium/readium-js/pull/82

**Comment by davedmiller** [comment]
Thank you, that might work...I will have to study it.

**Comment by danielweck** [comment]
Answered: https://github.com/readium/readium-js/pull/82
