### ISSUE TITLE
Chrome packaged app icon, label depending on branch name (release => RC, master => no label, others (develop, feature, etc.) => test/dev)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#314]
Request from @rkwright:
Would it be possible to have “release” have a “RC” label while only ‘master’ has no label?

Right now, the special icon is *not* used when the branch name starts with "release/", see:

https://github.com/readium/readium-js-viewer/blob/master/grunt/versioning.js#L39

https://github.com/readium/readium-js-viewer/blob/master/grunt/versioning.js#L104

**Comment by rkwright** [comment]
Additional datum:  When I build from master, I get the "Test" text on the icon and the title of the app (in the OSX titlebar says "Readium (Development Build)".  We need to have the builds such that the "Test" and "Development" decorations do not get placed in a master branch build at all. SO the behaviour would be:
- master branch - no decorations
- release/x.xx branch - "RC" text and "Release Candidate" in the title
- all other branches: "Test" in the icon and "Development Build" in the title

**Comment by ryanackley** [comment]
Keep in mind that we currently cut the actual release from the release branch. With this approach, we will need to merge release into master *then* perform the release from master so the icon is correct in the product. Just something to be aware of.

**Comment by rkwright** [comment]
This is a good point and makes me think that tying the decoration to the branch name may not be the right approach. Perhaps some more explicit approach like a build argument?

**Comment by danielweck** [comment]
Note the location of the script that handles this:
https://github.com/readium/readium-js-viewer/blob/develop/build-config/updateChromeManifest.js#L25

```javascript
if (!version.readiumJsViewer.release){
    manifest.name = 'Readium (Development Build)';

    var mediumStream = fs.createReadStream('src/chrome-app/icons/devBuild/medium.png');
    mediumStream.pipe(fs.createWriteStream('dist/chrome-app/icons/medium.png'));
    mediumStream.on('end', function(){
        var largeStream = fs.createReadStream('src/chrome-app/icons/devBuild/large.png');
        largeStream.pipe(fs.createWriteStream('dist/chrome-app/icons/large.png'));
        largeStream.on('end', finish);
    });
}
```

**Comment by rkwright** [comment]
Long ago implemented.
