### ISSUE TITLE
Is paging available?

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#319]
I am currently using index.html page of readium project to didplay my .epub files. Does it provide any paging feature? If so how to add it ?

**Comment by danielweck** [comment]
Short answer: yes (assuming you mean "pagination").
Are you having problems navigating dynamic pages in reflowable content, or pre-paginated documents in the case of fixed-layout EPUBs?

**Comment by mahag** [comment]
I need to show for example on bottom the page number or page 5 out 450.Is it the same?

**Comment by danielweck** [comment]
The "page count" feature is currently not implemented for reflowable EPUBs (dynamic pagination). It is implemented partially for fixed-layout ebooks (pre-paginated) but there is no user interface to display / choose page numbers. Here is the "backend" API that partially implements support for this feature:
https://github.com/readium/readium-shared-js/blob/develop/js/models/current_pages_info.js#L37
(it is used in native application launchers such as OSX and iOS, but this remains an incomplete feature)

See: https://github.com/readium/readium-shared-js/issues/105 and https://github.com/readium/readium-js/issues/16
