### ISSUE TITLE
Full screen mode not working when using embedded epub viewer

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#320]
I have an iframe as follows inside my webpage
 <iframe src="http://www.mywebsite.com/cloud-reader-lite/index.html?epub=epub_content/2369.epub" id="mybook" width="100%" height="550px"></iframe>

Once i click on my webpage on full screen mode it is not working.
But if i go directly to link http://www.mywebsite.com/cloud-reader-lite/index.html?epub=epub_content/2369.epub in browser instead of using iframe and click on full screen module it is working.

Any idea how can this be fixed ?

**Comment by danielweck** [comment]
You need to set the HTML5 `AllowFullScreen` attribute on your iframe, otherwise the web browser's fullscreen API will not allow the switch to full screen mode (this is an HTML security measure).

**Comment by mahag** [comment]
Adding AllowFullScreen solved the issue. But it seems there is a wrong behavior on IE 11 it opens full mode but text or book content isnt correctly displayed. Is it  a bug ?

**Comment by danielweck** [comment]
@mahag could you please file a separate issue about the IE11 fullscreen display / layout bug, if possible with a screenshot attachment? Does this happen only when Readium is embedded in an iframe?

**Comment by JDias** [comment]
Hi,

I have issue with fullscreen dunno where to dig.
https://www.sisdipe.com.br/i-educar/interno/ereader.php

(I will try to use the readium opds support and add swipe to navigate, but atm this fullscreen issue just traped me :/ )

**Comment by Praveen188** [comment]
Hi ,
In Readium cloud reader FullScreen is not working in chrome.

**Comment by Praveen188** [comment]
Hi ,
Please check the below URL.
https://readium.firebaseapp.com/?epub=epub_content%2Fmoby_dick&goto=epubcfi(/6/44!/4/2/2/2/1:0)
