### ISSUE TITLE
Change Settings menu

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#321]
Is it possible to change the settings options showing ? For example remove some options, rename some texts displayed  into a different language?
I checked the could reader folder I only have readium-all.js file under scripts and readium-all.css under css folder

**Comment by danielweck** [comment]
Yes you can customize the application's user interface, but you have to makes changes to the actual source code, not to the aggregated / minified build output.

See:
https://github.com/readium/readium-js-viewer/blob/develop/templates/settings-dialog.html
https://github.com/readium/readium-js-viewer/blob/develop/lib/ReaderSettingsDialog.js

**Comment by mahag** [comment]
but i dont have templates folder or lib folder do i create them and place file underneath them ?

**Comment by danielweck** [comment]
If you want to modify the source code, you need to learn to use Git to clone the Readium repositories
(from the command line or from a GUI utility). Then you need to compile / build your own fork of Readium. There are how-to instructions in the README:
https://github.com/readium/readium-js-viewer/blob/master/README.md

**Comment by rkwright** [comment]
But do note that we welcome people who will help us localize the strings for the existing UI.  We only ask that you do so carefully and only in your own native language (to minimize errors).  Also, you need to localize all the strings (not just some or most).  Then submit the localized strings as a pull-request and we will review it.

The current strings are here
https://github.com/readium/readium-js-viewer/tree/master/i18n/_locales
which demonstrates the proper format.
