### ISSUE TITLE
Is there an online readium-js-viewer demo ?

### ISSUE THREAD

**Issue by wzhsunn** [readium/readium-js-viewer#322]
I test it on my local pc .

When I add a file when I using it as cloudReader,
Running 
```
grunt
```
visit localhost:8080
add a file failed.

When I using it as chrome app, it works whell .

Is there an online demo so that I can test it ?

Thank you !

**Comment by danielweck** [comment]
At the moment, the feature "add an EPUB to the library" only works with the Chrome extension/app, not the 'cloud reader'. In the future, Readium could manage ebooks "in the cloud" (i.e. remote storage location + HTTP CORS), but right now ; as far as I know ; this is not on the development roadmap. Would you be intersted in creating a protoype for this feature?

**Comment by danielweck** [comment]
Issue already exists: https://github.com/readium/readium-js-viewer/issues/82

**Comment by wzhsunn** [comment]
Thank you for your reply.
I has such an requirement:
Make an independent windows software to reading epub3( supports mathml).
First time I try that using readium-js-viewer + node-webkit .

Could you give me some better advice?  thank you so much !
