### ISSUE TITLE
[Question] Is it possible to load external epub file?

### ISSUE THREAD

**Issue by landvibe** [readium/readium-js-viewer#325]
I want to build multiple web-servers and one data source.
But it seems that the epub parameter parses only local path.
http://localhost/readium-js-viewer/simpleviewer.html?epub=epub_content/moby_dick

Is it possible to parse remote path? (like below)
http://localhost/readium-js-viewer/simpleviewer.html?epub=http://www.something.com/epubFile1

**Comment by danielweck** [comment]
That's correct, the parser for the `epub` parameter currently does not check for absolute URLs, if I remember correctly. Also, XMLHttpRequest is used to fetch and extract data from the referenced EPUB archive, so same-origin policy come into play, which means that your server would have to support HTTP-CORS. In the case of expanded EPUBs (already unzipped), similar cross-origin restrictions must be considered.

**Comment by danielweck** [comment]
Also see: https://github.com/readium/readium-js/issues/51#issuecomment-71647089

**Comment by landvibe** [comment]
Could you give me any idea for building multiple web-servers and one data source with readium-js?

**Comment by danielweck** [comment]
Unfortunately I have no spare time to address this issue personally, but I am very interested in contributors' pull requests. I would love to see a working example of cross-origin Readium, separated app-content domains.

**Comment by danielweck** [comment]
@landvibe you should reach out to the developer involved in this discussion thread, to find out more about their HTTP CORS solution: https://github.com/readium/readium-js/issues/51#issuecomment-71647089

**Comment by landvibe** [comment]
I think relay can be a solution for this question.
client -> web-server -> data server -> web-server -> client
