### ISSUE TITLE
zipped epub is not working on iOS

### ISSUE THREAD

**Issue by landvibe** [readium/readium-js-viewer#326]
Zipped epub is not loaded on my iPhone5S (ios 8.1.3).
both browser (chrome and safari) is not working.
The indicator is animating forever.

additional info:
- unzipped epub is loaded well.
- ios simulator(iPhone6) shows same results
- android(4.4.2) works well on both (zipped and unzipped)

**Comment by danielweck** [comment]
I believe this is the same issue: https://github.com/readium/readium-js/issues/72#issuecomment-60201123

**Comment by landvibe** [comment]
Adding two lines of code fixes this issue.

zip-ext.js -> HttpRangeReader -> init (add below line after request.open)
request.setRequestHeader("If-None-Match","webkit-no-cache");

zip-ext.js -> HttpRangeReader -> readArrayBuffer (add below line after request.open)
request.setRequestHeader("If-None-Match","webkit-no-cache");

**Comment by danielweck** [comment]
Reopening, as seems different issue to I believe this is the same issue: https://github.com/readium/readium-js/issues/72#issuecomment-242793007

**Comment by danielweck** [comment]
This should be fixed by PR https://github.com/readium/readium-js/pull/193 for the general case.
There should be no need to patch `zip-ext.js` with respect to fetching byte ranges (HTTP 1.1 partial requests).
