### ISSUE TITLE
Review DivShot cache control

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#327]
https://github.com/readium/readium-js-viewer/blob/develop/divshot.json#L4

```json
"cache_control": {
  	"epub_content/**" : 31536000
  }
```

http://docs.divshot.com/guides/performance
"
If you supply an Integer value, the Cache-Control header is set to public, max-age=YOURVALUE.
If you supply false, no Cache-Control header is set.
If you supply a String, the Cache-Control header is set to the exact value you pass (e.g. no-cache, no-store).
"

**Comment by ryanackley** [comment]
This caches the epub books for 31536000 seconds (1 year). I think this is what we want since the library content rarely changes

**Comment by danielweck** [comment]
DivShot.io is shutting down ( https://github.com/readium/readium-js-viewer/issues/445 ) but Firebase.io also provides a cache control directive.

We will probably move the `epub_content` to a proper CDN at some point soon. EPUB testsuite already migrated, only Readium's own test ebooks remain.

**Comment by danielweck** [comment]
No cache control directive in Firebase now:
https://github.com/readium/readium-js-viewer/blob/develop/firebase.json

We now use a CDN for epub-testsuite, and may (or may not) migrate the Readium built-in EPUBs to CDN as well (not high priority, as they are not high-traffic tested ebooks, unlike the epub-testsuite).
