### ISSUE TITLE
Is there a button to enter fullscreen?

### ISSUE THREAD

**Issue by mrmayfield** [readium/readium-js-viewer#330]
I'm using the embedded js viewer, and am wondering if there is a button to enter fullscreen since, for example, mobile users can't press 'h' on their keyboard. Thanks!

**Comment by danielweck** [comment]
Could you please clarify which build of ReadiumJS you are using? Did you build the web application using `grunt cloudReader / cloudReaderLite`, or are you just pointing your web browser to `https://github.com/readium/readium-js-viewer/blob/develop/index.html` / `https://github.com/readium/readium-js-viewer/blob/develop/simpleviewer.html`?

**Comment by mrmayfield** [comment]
That's correct, I am using the Simple Viewer in an iframe.

**Comment by mrmayfield** [comment]
Would be nice if there was a button to zoom in and out as well. :)

**Comment by danielweck** [comment]
I've just tried the "cloud reader lite" and I can see the fullscreen button in the upper right corner in the top toolbar. However, if your iframe is narrower than __768px__, the fullscreen button is hidden. You can modify this CSS rule to change this behaviour:

https://github.com/readium/readium-js-viewer/blob/master/css/viewer.css#L570

```css
@media (max-width:768px){
  .navbar .btn-group > .btn.icon-full-screen
  {
    display:none;
  }
}
```

**Comment by mrmayfield** [comment]
Okay wicked, I can see it now thank you. I haven't dug into the JS but is there a way I could port Zoom In and Zoom Out functionality to another icon in that top toolbar?

**Comment by danielweck** [comment]
What do you mean by "zoom in/out"? Fixed layout percentage / fit ratio?

**Comment by mrmayfield** [comment]
In the Settings section, in the Style tab, there is a slider to adjust font-size, either making it larger or smaller. Could I port an icon to the top toolbar that when clicked simulates a movement up the slider, and either make the font smaller or bigger?

**Comment by mrmayfield** [comment]
Looks like there is a save() function in ReaderSettingsDialog.js that uses Jquery to pull the fontSizeSlider.val() and then return that (presumably to another function which resizes the font).

And there is also a Jquery function which changes the fontSizeSlider value when its used. Maybe for a hack I could throw the Icons in the toolbar and have them resize the fontImageSlider value when clicked and then trigger the save function?

**Comment by Praveen188** [comment]
Hi ,
Fullscreen not working chrome .
