### ISSUE TITLE
External links cause Chrome Extension to freeze

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#337]
A user reported this issue:
http://idpf.org/forum/topic-2478
Not yet verified

"
Good morning,

We have an e-book with mostly internal links to other pages within the document. A few links, however, lead to external webpages. These used to work perfectly when Readium operated in-browser. However, since the recent Readium update, once you click on an external link the EPUB "freezes" and loses all functionality. It does not load the external link, and subsequently clicking on any other link, including back/next buttons, fails to work.

This is a fixed layout EPUB3, and the problem is new since updating to Readium 2.18.1.

Is this a known issue? Is there a different way we should create the links in InDesign in order to avoid this problem?

If someone could please advise me of any solutions or workarounds, it would be much appreciated.

Thank you,
Mary
"

**Comment by danielweck** [comment]
I wonder if/how this ties-in with this WebView-related issue (external links, jQuery event handler):
https://github.com/readium/SDKLauncher-iOS/issues/52

**Comment by rkwright** [comment]
Not sure this is a separate issue, but see this forum post:
http://idpf.org/forum/topic-2479
Links in the About box don't work.

**Comment by danielweck** [comment]
Fixed: https://github.com/readium/readium-js-viewer/commit/b3763d5e9f66768ab40b4db6da184c15b0f1d9a6
