### ISSUE TITLE
MathJax context menu contains empty strings in Chrome extension  / app

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#346]
Right-click on MathML expression => the popup menu is all squashed (empty strings)

**Comment by danielweck** [comment]
TODO: test with v2.5
https://github.com/readium/readium-js-viewer/issues/262

**Comment by danielweck** [comment]
Follow-up: problem still exists with MathJax v2.5 (note that the menu displays fine in Chrome - Cloud Reader, but not Chrome - Package App)

**Comment by danielweck** [comment]
TODO: test with develop branch now with MathJax 2.6

**Comment by pkra** [comment]
Do you have a screenshot? All I see is a z-index problem (the menu is only visible on the first page of a chapter but opening it and going back to the front page shows it, too; see also https://github.com/pkra/MathJax-single-file/issues/6).

**Comment by danielweck** [comment]
I am not able to reproduce this bug anymore. Closing.
MathJax "about" dialog box:

```
MathJax v2.6.0
using web SVG fonts

MathJax.js v2.6.0
MathML Input Jax v2.6.0
SVG Output Jax v2.6.0
mml Element Jax v2.6.0
AssistiveMML Extension v2.6.0
Help Extension v2.6.0
MatchWebFonts Extension v2.6.0
MathEvents Extension v2.6.0
MathML/mml3 Extension v2.6.0
MathMenu Extension v2.6.0
MathZoom Extension v2.6.0
mml2jax Extension v2.6.0
Chrome v48.0.2564.97
```
