### ISSUE TITLE
cfi exceptions 

### ISSUE THREAD

**Issue by larsvoigt** [readium/readium-js-viewer#349]
Hallo @danielweck, 

I tried to highlight the following fragment identifier:

``` /6/20[id-id2635343]!/4/2[building_a_better_epub]/10/36/22,/2/1:0,/2/1:4 ```

but the two functions raised the following exceptions:
 ``` 
readium.reader.openSpineItemElementCfi() -> CFIAssertionError {expectedAssertion: "building_a_better_epub", targetElementAssertion: undefined} Id assertion failed

readium.reader.addHighlight() -> Cannot set property 'idref' of undefined
```

I think the cfi is alright. It should reference the text location "EPUB" in element ```<a>``` 
https://github.com/readium/readium-js-viewer/blob/master/epub_content/accessible_epub_3/EPUB/ch02.xhtml#L419 

Do you have a hint for me what is going wrong?
thanks 
Lars

**Comment by dmitrym0** [comment]
Hi Lars, it looks like you're missing the idref parameter to addHighlight. Readium uses a two part cfi that consists of idref, and content cfi. I see the content CFI but not the idref.

**Comment by larsvoigt** [comment]
Thank you @dmitrym0 for your hint. I think I have pass the idref parameter to addHighlight. Okay it is possible that the parameter is not defined. I will test it tomorrow.

**Comment by larsvoigt** [comment]
Hi Dmitry, I found the issues. The ```partialCfi```is referencing a location in another  spineitem (```idref```) than I pass to the highlighting function.  Or more specifically I had pass a wrong idref value. 

Your documentation:
https://github.com/readium/readium-shared-js/blob/master/js/views/annotations_manager.js#L31
was also useful :-)

**Comment by dmitrym0** [comment]
Glad it worked :+1:
