### ISSUE TITLE
Readium Issue in Android Browser View

### ISSUE THREAD

**Issue by davedmiller** [readium/readium-js-viewer#351]
I have implemented a Readium viewer on an IIS hosted web site.  At this point, it is working wonderfully in several browser environments, including: Safari/Firefox/Chrome on Mac, IE/Firefox/Chrome on Windows, Safari/Chrome/embedded View on iOS, and Safari/Chrome on Android.  However, it is not working in and embedded view in Android, specifically in the Facebook embedded browser.  I am currently running the readium 0.20 pre-built release.  However this issue exhibits whether I am using a pre-built release or running on the head of the readium dev tree.

We have implemented access to the epubs through a rest api.  We can see Readium open an xhtml file, and then it never calls again, and never progresses off the spinner.  Remote debugging in this environment will take some time to learn and setup.  I am heading down the path of installing the Android SDK and emulator to set up a test case.  Does anyone have any ideas how to better isolate the issue?  I am not a backbone expert and am wondering if there are tools at that level that would allow me to figure out what is going on?  

Any help/thoughts would be appreciated.

**Comment by danielweck** [comment]
On my iPad, Google Chrome fails to load EPUBs (the cloud reader ebook library displays fine, but clicking on a given EPUB results in infinite spinning loader icon). Apple's own Safari browser loads them fine.

See:
https://github.com/readium/readium-js-viewer/issues/352

Could you please try again on your device and let me know what you see?
Thanks!

**Comment by danielweck** [comment]
Secondly, could you please try this feature build (not from the develop branch):
http://development.readium.divshot.io

PS: when you say "I am currently running the readium 0.20 pre-built release", do you mean:
https://github.com/readium/readium-js-viewer/releases/tag/0.20.0
?

**Comment by davedmiller** [comment]
I have tried http://development.readium.divshot.io by creating a facebook post containing the link and clicking on it.  I do get an error message "Page can't be loaded".  I don't know what page is being referred to though. This is what I get.
![errorimage](https://cloud.githubusercontent.com/assets/689057/7941339/67825372-090b-11e5-8fd7-36938c5d9bbf.png)


On the P.S. above, yes...but I find it strange that the date at that location is now June 2...unless I have a time machine, it seems the automated builds are posting with the same version for some period of time.  I last downloaded 0.20.0 on 5/29/2015 @ 4:33pm PDT.

**Comment by danielweck** [comment]
Please try the following fix from this Pull Request: https://github.com/readium/readium-js/pull/73
(in fact, to make things simpler in your tests, just force `var isIE = true;`, and check the results)
