### ISSUE TITLE
Scrollable div is not updated properly

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#355]
From Ric Wright:
I am making progress with my widget (when I get time).  I got the messages starting to work.  I have two scrollable “windows”.  One is the iFrame the other is a div.

The controller’s div is:

    <div id="controllerDiv" style="width:90%; height:400px;overflow:scroll; 
             border-style:solid;border-width:1px;border-color:gray">

    </div>

The controller div gets updated thusly:

		// Update the div element to display the sent-message.
		var newMsg = document.createTextNode("Message Sent: " + new Date());
		controllerDiv.appendChild(newMsg);
		controllerDiv.appendChild(document.createElement("br"));
		controllerDiv.scrollTop = controllerDiv.scrollHeight;

It almost works except that it only scrolls PART of the div:
![scrollerr](https://cloud.githubusercontent.com/assets/3025864/8014077/86381602-0b82-11e5-8750-d5b14ce7a6d2.png)
The part below 13:25:01 never gets updated.  It’s like its scrolling only the upper part?

**Comment by rkwright** [comment]
Ryan replied:
I can't reproduce the problem. See this jsfiddle that tries and emulates it. http://jsfiddle.net/mh06peg1/1/. Seems to work fine.

**Comment by rkwright** [comment]
Ric replied:
Yes, in the browser is works fine.  In our RS it doesn’t.  See my email of a few minutes ago.  That snippet also works fine in the browser, but the equivalent doesn’t in our RS.  There is something about our implementation that causes problems. I’m not saying it is a bug, but it is a limitation. 
 
The code has been pushed to the IDPF github repository here:
https://github.com/IDPF/scriptable-components/tree/feature/logger-widget/Samples/readium/logger-demo/embedded/logger-demo
Note that in iBooks there are no rendering artifacts in the controller window (unlike us) but the logger window doesn’t scroll “right” which I take to mean that I misunderstand how it should work.

**Comment by rkwright** [comment]
Additional note: It works fine in the SDKLauncher-OSX.  That is, the left hand pane scrolls seamlessly. The right hand pane doesn't scroll properly but I assume that is because there is something I don't understand about iFrames and scrollTop.

**Comment by rkwright** [comment]
Poked at this a bit more and it gets stranger.  What in  fact is not being updated is an area of the div.  And that area varies depending on what is being written, i.e how long the line is. In this example, the area outlined in red doesn't get updated.  UNTIL the button ("Send Message") loses the focus.  Then the scrollable div gets updated correctly...
![scrollerr](https://cloud.githubusercontent.com/assets/3025864/8067018/d984f774-0e9f-11e5-8794-ccd931170875.png)
Appears that this is a Chrome bug?

**Comment by rkwright** [comment]
Ok, good news, bad news.  I noticed that when I adjusted the width of the window way down - to where the actual pixel width of the containing window was smaller than the fixed layout specified width, then it all worked fine. So I switched from the release version (2.18.1) to the develop branch.  And the scroll artifacts disappeared and the scrolling was fine.
BUT...  the right side of the page was clipped to the point that the scroll bars disappeared:
![scrollerr2](https://cloud.githubusercontent.com/assets/3025864/8067916/af523042-0ea5-11e5-8edc-964ca4e1f428.png)
And it gets worse.  The clipping of the right side begins as soon as the width of the containing window is larger than the width of the fixed layout page.

**Comment by ryanackley** [comment]
I can only reproduce the update issue when the zoom level is above 100%. 

There is nothing wrong with the extension or your html. It's definitely a chrome bug. It happens if I try to scroll the div without pressing the button. It may be related to this [bug](https://code.google.com/p/chromium/issues/detail?id=441671)

I am unable to hide the scrollbars of the scrollable div. The containing frame either produces scrollbars or shrinks the content.

**Comment by rkwright** [comment]
Right.  I only see the issue when the zoom level exceeds 100%.  In the released version, I see this scrolling artifact.  In the development branch, no scrolling artifact, but it gets clipped on the right.  Sounds like scaler-div land to me.

BTW, it's a fixed layout EPUB and the layout settings don't make any difference.

**Comment by ryanackley** [comment]
In the current version in the web store, the scroll mode affects fixed layout epubs. Not by much but it does change the html on the page that is displaying the content. Not sure if that is intentional

**Comment by danielweck** [comment]
So this is a browser bug, right? Shall we close this issue?

**Comment by rkwright** [comment]
Closing since it is out of our hands.
