### ISSUE TITLE
"columnized" view causes problems for keyboard only users

### ISSUE THREAD

**Issue by becka11y** [readium/readium-js-viewer#358]
This is similar to #62 for screen readers. The solution there was to have screen reader users select continuous mode. I don't think that is an acceptable solution for keyboard users but would like feedback from others.

The problem is if there is a keyboard actionable item (link, etc) within the content that is within a non-visible column. The keyboard user may press tab to attempt to navigate to a prev/next page button but focus will go to the next tab-focusable item - bringing that into focus and disrupting the columnize view.

Here are some explicit scenarios:
Works as expected:
-Scroll mode is auto, display mode is document
-Load the Accessible EPUB 3 book
-Open the ToC and navigate to Introduction
-Close the ToC - focus should be on the ToC button in the toolbar
-Tab forward 6 times until focus in on the next page button (there are extra tab stops in there - that is a different issue).
-Press enter to activate button. Behavior is as expected - next page is displayed.

Not working as expected:
-Scroll mode is auto, display mode is document
-Load the Accessible EPUB 3 book
-Open the ToC and navigate to The Sound and the Fury
-Close the ToC - focus should now be on the Toc Button in the toolbar.
-Press tab 5 times - focus goes to the link in this chapter (epubReadingSystem) and that link is brought into focus. This ruins the columnized view. The user must navigate to a page that requires a document load in order to fix the view.

View in FF in Windows 7- Safari on OS X is similar:
![fflinkruinscolumnview](https://cloud.githubusercontent.com/assets/318987/8163722/d2908e1c-1352-11e5-892b-3fe8bbf0f373.jpg)

**Comment by danielweck** [comment]
Thanks Becky! Duplicate issue: https://github.com/readium/readium-js-viewer/issues/309
I am copy-pasting your detailed report into the original issue.

**Comment by becka11y** [comment]
Thanks, Daniel, as I was writing it I thought it sounded familiar - I'll have to learn to search better!

**Comment by danielweck** [comment]
No problems at all Becky, that's team work :)
Your bug report + screenshot is more descriptive, definitely worth copying across to the original issue.
