### ISSUE TITLE
annotations.css background images are missing (unused)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#359]
The CSS should be cleaned-up to remove unused asset dependencies:

https://github.com/readium/readium-js-viewer/blob/master/css/annotations.css#L3

`/images/comment_clickable_icon.png` and `/images/comment_clickable_icon.png`.

**Comment by danielweck** [comment]
CSS classes are used here:
https://github.com/readium/readium-shared-js/blob/develop/lib/annotations_module.js#L1322
```javascript
    setHoverBookmark : function (event) {

        event.stopPropagation();
        if (this.$el.hasClass("comment")) {
            this.$el.removeClass("comment");
            this.$el.addClass("hover-comment");
        }
    },

    setBaseBookmark : function (event) {

        event.stopPropagation();
        if (this.$el.hasClass("hover-comment")) {
            this.$el.removeClass("hover-comment");
            this.$el.addClass("comment");
        }
    },
```

**Comment by danielweck** [comment]
Addressed in "plugins" feature branch: https://github.com/readium/readium-js-viewer/commit/aaf6c6a5fe5955d11f95df2c42acca0217d15c4f

Still needs fixing in native apps:

https://github.com/readium/SDKLauncher-OSX/blob/master/LauncherOSX/ReaderScripts/annotations.css#L2

https://github.com/readium/SDKLauncher-iOS/blob/master/Resources/annotations.css#L2

https://github.com/readium/SDKLauncher-Android/blob/master/SDKLauncher-Android/assets/reader-payloads/annotations.css#L2

**Comment by danielweck** [comment]
Fixed in native apps via:

https://github.com/readium/SDKLauncher-Android/commit/81d1a8a7351523db4ea5c5e4fc2681b64debdd4c

https://github.com/readium/SDKLauncher-iOS/commit/000329f3bdc38d67664619d07ac4a4e35bfe9e04

https://github.com/readium/SDKLauncher-OSX/commit/1f2f01573163ac870f064bddca96c80c62959a89

**Comment by charlieanna2013** [comment]
[Uploading 60459480.obml16…]()

**Comment by charlieanna2013** [comment]
[Uploading MMS_Folders.bin…]()

**Comment by charlieanna2013** [comment]
[Uploading (R)Pay For It.vbm…]()
