### ISSUE TITLE
Re-structure repo in develop branch does not build without errors

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#370]
Well, to sort of worked, to a point.  I cloned a new sandbox.  Initially, I did

    git clone —recursive https://github.com/readium/readium-js-viewer.git –b develop readium-js-viewer-New

This worked so I ran

    git submodule update --init --recursive
    git submodule foreach --recursive 'git checkout develop’

All OK.  Then I ran

    npm run prepare

And got a ton of errors (see attachment).

Then I tried deleted the first sandbox and did 

    git clone —recursive https://github.com/readium/readium-js-viewer.git –b develop readium-js-viewer-New

(No develop branch)

Then when I ran 

    git submodule update --init —recursive

OK.  Then ran 

    git submodule foreach --recursive 'git checkout develop’

I got 

    Entering 'readium-js'
    warning: unable to rmdir epub-modules/epub-renderer/src/readium-shared-js: Directory not empty
    Previous HEAD position was 9e09854... Merge branch 'release/0.19' into develop
    Branch develop set up to track remote branch develop from origin.
    Switched to a new branch 'develop'

This is all on my MBP with OSX 10.10.4

Suggestions?

**Comment by rkwright** [comment]
From @JCCR 
Looking at your log, it appears that your ~/.npm folder might have improper permissions.
Here’s mine for comparison:
    $ ls -ld ~/.npm
    drwxr-xr-x  755 juanc  staff  25670 22 Jun 14:55 /Users/juanc/.npm

**Comment by rkwright** [comment]
Unfortunately:

    Gort:~ rkwright$ ls -ld .npm
    drwxr-xr-x  449 rkwright  staff  15266 Jul 10 10:18 .npm

**Comment by rkwright** [comment]
From @danielweck 
It looks like you already have `chmod 755 .npm`:

    user
    r+w+x
    4+2+1
    
    group
    r+x
    4+0+1
    
    world
    r+x
    4+0+1
    
    = 755

...so 449 seems to be some OSX-specific "thing" (max total is 7 for
each field, to 9 does not make sense!)

**Comment by ryanackley** [comment]
Ran fine for me. I did have to update to the latest version of Node for an unrelated problem.

try running 

```
sudo chown -R $USER:$GROUP ~/.npm
npm cache clean
```

Taken from here https://github.com/npm/npm/issues/5869

-Ryan

**Comment by rkwright** [comment]
OK, got it to work.  I basically followed Ryan's advice (above) then the instructions Daniel posted:
    Gort:~ rkwright$ sudo npm cache clean -f
    npm WARN using --force I sure hope you know what you are doing.
    Gort:~ rkwright$ sudo npm install -g n
    /usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
    n@1.3.0 /usr/local/lib/node_modules/n
    Gort:~ rkwright$ sudo n stable

     install : node-v0.12.7
       mkdir : /usr/local/n/versions/node/0.12.7
       fetch : https://nodejs.org/dist/v0.12.7/node-v0.12.7-darwin-x64.tar.gz
   installed : v0.12.7

    Gort:~ rkwright$ node -v
    v0.12.7
    Gort:~ rkwright$ sudo chown -R $USER:$GROUP ~/.npm
    Gort:~ rkwright$ npm cache clean
    Gort:~ rkwright$ git clone --recursive https://github.com/readium/readium-js-viewer.git -b develop readium-js-viewer-New

    Gort:readium-js-viewer-New rkwright$ git submodule update --init --recursive
    Gort:readium-js-viewer-New rkwright$ git submodule foreach --recursive 'git checkout develop'
    
    Gort:readium-js-viewer-New rkwright$ npm run prepare

After a fairly long time (circa 3-4 minutes) it completed.  I then ran    

    npm run chromeApp

And it worked.  Phew, there are a lot of steps and output...

**Comment by danielweck** [comment]
About `npm run prepare`: this pre-build task (which does not need to be invoked every time, although I personally run it at least once a week, usually every couple of days) checks for latest versions of library dependencies, at the NPM registry as well as at some GitHub repositories. Thus why it can take some time (plus, NPM package management is generally slow).

About command line verbosity: the current build system (chain of NPM-driven script / tasks) outputs lots of information so that when there's a failure ; i.e. Travis CI ; we can investigate effectively. Maybe we need a verbosity command line parameter?

**Comment by larsvoigt** [comment]
Phew phew. I try to set up the new readium architecture/infrastructure. But the following install part won´t work for me.  
``` 
node readium-build-tools/gitHubForksUpdater.js
danielweck/http-server
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```
I'm use linux and behind a proxy.
Any ideas? Thanks

**Comment by danielweck** [comment]
It looks like either 1) GitHub is down (which I experienced yesterday) or 2) there's some other kind of problem preventing access to `https://api.github.com` (proxy?)

However, you can start using Readium anyway. This is just a stage in `npm run prepare` that checks for latest versions of NPM packages hosted at GitHub.

**Comment by larsvoigt** [comment]
GitHub is up :-). I think also it's point 2. After a lot of debugging and testing it is still not working.
Good to hear that readium runs anyway.

**Comment by danielweck** [comment]
`https://api.github.com` runs on port `443`, if you want to configure your Linux proxy / firewall accordingly.

**Comment by larsvoigt** [comment]
Sorry other issue, it will not run. 
I would like to test the tasks:
```npm run chromeApp``` and 
````npm run build```.
Both break up their work. The cause is they
look for a file that not exit.
``` 
Error: Error: ENOENT, no such file or directory
 '/workspace/readium-js-viewer/readium-js/
readium-shared-js/node_modules/eventemitter3/_rjs/index.js'
```
The eventemitter3 folder is present and contains files.

?
Thanks

**Comment by danielweck** [comment]
@larsvoigt it looks like `npm run prepare` did not complete / was interrupted. Can you please try again?

**Comment by larsvoigt** [comment]
Thank you @danielweck. 
Okay ```npm run prepare``` has the same problem that I post yesterday.
It is really curious, if I open the url  
``` api.github.com:443/repos/danielweck/http-server?access_token=fb424e90e36242ab9603034ea906a070c9ce2646
```
in the browser all works fine. I get the json doc. If I do the same via node 
the request will be blocked (assumption). It looks like I need to dig deeper for this problem.

**Comment by danielweck** [comment]
I placed a try/catch around the offending GitHub API HTTPS request (SSL, not plain HTTP, by the way).
https://github.com/readium/readium-cfi-js/commit/2dbb3bb727c800575233f322b3f10e8c9edf3a7a
Does this solve your problem?

**Comment by danielweck** [comment]
Try:
`cd readium-js-viewer/readium-js/readium-shared-js`
`node readium-cfi-js/node_modules/requirejs/bin/r.js -convert node_modules/eventemitter3/ node_modules/eventemitter3/_rjs/`
What happens? Can you `ls -als` `node_modules/eventemitter3/_rjs/` please.

**Comment by larsvoigt** [comment]
Command convert works without errors. 
```ls -als node_modules/eventemitter3/_rjs/ ```
```
4 drwxrwxr-x 2 albert albert 4096 Jul 14 16:31 .
4 drwxrwxr-x 3 albert albert 4096 Jul 14 16:31 ..
8 -rw-rw-r-- 1 albert albert 7219 Jul 14 16:31 index.js
4 -rw-rw-r-- 1 albert albert 1082 Jul 14 16:31 LICENSE
4 -rw-rw-r-- 1 albert albert 2145 Jul 14 16:31 package.json
4 -rw-rw-r-- 1 albert albert 3685 Jul 14 16:31 README.md
```

**Comment by larsvoigt** [comment]
Great @danielweck  now the build was successful.

**Comment by danielweck** [comment]
Great. So the try/catch for the GitHub HTTPS API did not prevent the fatal script error. I would be interested to know where/how to intercept the error. I would appreciate if you could investigate that yourself, as you are able to reproduce the behaviour with your proxy. Just place `console.log()` messages in the file where I put the try/carch. Many thanks! :)
