### ISSUE TITLE
Update to Chrome Browser breaks EPUB uploads

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#377]
Apparently, the latest update to the Chrome Browser (44.0.2403.107m) has broken EPUB uploads.  I have verified this on my wife's Windows 8.1 Lenovo laptop.  Tried to upload "Accessible EPUB" and it hangs almost immediate with the message "Examining EPUB..."  Browser window has to be closed.

Now verified on OSX as well.  Same version of the browsr.

**Comment by rkwright** [comment]
Additional info.  Happens with the latest build in develop as well.  Verified on OSX.

**Comment by rkwright** [comment]
Console dump when error occurs:

     readium-js-viewer_all_CHROMEAPP.js:11577 RequireJS ... cfi_instructions
     readium-js-viewer_all_CHROMEAPP.js:12014 RequireJS ... cfi_interpreter
     readium-js-viewer_all_CHROMEAPP.js:12520 RequireJS ... cfi_generator
     readium-js-viewer_all_CHROMEAPP.js:12667 RequireJS ... cfi_API
     requirejs-config.js:25 chrome-extension://eafhhobkochaioojdidffhllaimjfdkk/index.html
     requirejs-config.js:29 chrome-extension://eafhhobkochaioojdidffhllaimjfdkk
     readium-js-viewer_all_CHROMEAPP.js:26950 'Range.detach' is now a no-op, as per DOM      (http://dom.spec.whatwg.org/#dom-range-detach).
     readium-js-viewer_all_CHROMEAPP.js:29664 Discontiguous selection is not supported.(anonymous function) @ readium-js-viewer_all_CHROMEAPP.js:29664
     readium-js-viewer_all_CHROMEAPP.js:12654 #######################################
     readium-js-viewer_all_CHROMEAPP.js:21901 Globals...
     readium-js-viewer_all_CHROMEAPP.js:21907 ReadiumSDK set.
     readium-js-viewer_all_CHROMEAPP.js:55924 'KeyboardEvent.keyLocation' is deprecated. Please use 'KeyboardEvent.location' instead.
     requirejs-config.js:25chrome-extension://eafhhobkochaioojdidffhllaimjfdkk/scripts/readium-js-viewer_CHROMEAPP-WORKER.js
     requirejs-config.js:29 chrome-extension://eafhhobkochaioojdidffhllaimjfdkk
     ZipFileLoader.js:29 Uncaught TypeError: Cannot set property 'mimetype' of undefined(anonymous function) @ ZipFileLoader.js:29(anonymous function) @ zip.js:670reader.onload @ zip.js:180
     WorkerProxy.js:96 [ErrorEvent]0: ErrorEventcallee: ()length: 1Symbol(Symbol.iterator):      ArrayValues()__proto__: Objectworker.onerror @ WorkerProxy.js:96

**Comment by ryanackley** [comment]
A lot of unfamiliar logging happening in the console. Did we update the chrome extension recently?

**Comment by rkwright** [comment]
I do not know.  Most likely Juan or Daniel.  AFAIK, we did not modify or update the Chrome Extension per se.  But I don't think that has anything to do with this.  Users are reporting the problem in the production version (2.18.1) and I am seeing it in the latest (20) code in the develop branch.  Appears to be some exception thrown from the unzipping process.  But that area is a foreign country to me... :-)

BTW, the new release of Chrome came out on Friday.

http://googlechromereleases.blogspot.com/

**Comment by rkwright** [comment]
from @ryanackley 
So it seems that 'self' references the global scope when you are inside a worker. The equivalent of 'window'.  I didn't realize this. It must have been made read-only in the latest version. I changed the name to avoid any future confusion.
