### ISSUE TITLE
 Incorrect mathjax copy path at cloudreader(lite) dist task

### ISSUE THREAD

**Issue by larsvoigt** [readium/readium-js-viewer#378]
https://github.com/readium/readium-js-viewer/blob/develop/package/package_scripts_dist_cloudReader.cson#L54

https://github.com/readium/readium-js-viewer/blob/develop/package/package_scripts_dist_cloudReaderLite.cson#L54

**Comment by danielweck** [comment]
Thank you!
Fixed: 
https://github.com/readium/readium-js-viewer/commit/b842722c7680df846ba650103c05b0e13f7ec7f3
https://github.com/readium/readium-js-viewer/commit/b842722c7680df846ba650103c05b0e13f7ec7f3

**Comment by larsvoigt** [comment]
Thank you too.
