### ISSUE TITLE
Absolute positioning.

### ISSUE THREAD

**Issue by benfinn** [readium/readium-js-viewer#379]
I'm working with Readium on a project where we're trying to have dialogs appear. The positioning is a bit odd. I'm trying to get my dialog appear in a specific place on the page, based on hovering over an originating link. When I check the dimensions with various Javascript methods, I get unusual results. 

Here's what I get on a typical page, and the method I used to get them:

Screen width: 1920 -- Screen height: 1080 (accurate) - standard Javascript `screen.width`
Viewport height: 150 -- Viewport width: 300 (I have no idea what this is measuring) - `window.innerWidth`
Window height: 150 -- Window width: 300 (again, no clue) - `window.innerHeight`
Offset of the original <a>: top: 275.25, left: 200.0703125  - jQuery `$(link).offset()`
Position of the original <a>:  top: 275.25, left: 200.0703125  - jQuery `$(link).position()`
Document height: 6020 -- Document width: 3756 (this seems to have no relation to the page or document) - jQuery `$(document).height()` and `$(document).width()`
Page height:: 847 -- Page width: 894 - pulling out the `style` attribute from the `html` element

So, my question is this: How do you absolutely position something on a given page in a document?

Sorry if this isn't the right place to post this. I saw on the IDPF forums that very technical questions are best posted here.

**Comment by dmitrym0** [comment]
Are you working with a fixed layout epub? When we render fixed layout epubs we have to scale the book container to fit everything on screen. There're a bunch of transformations that take place to make everything appear correctly. As far as I know there's no public API to translate "book coordinates" into "screen coordinates". 

Reflowable epubs have a similar problem because we columnize the output to paginate it.

**Comment by benfinn** [comment]
No, it's reflowable.

So, are you saying it's essentially impossible to determine locations in the reflowed content? I'm not trying to say, "On page 3, do this." I'm saying, "At this point in the book, as defined by the presence of an <a> link, regardless of how the content has been reflowed, do this within the current context." The problem I'm having is determining the current context -- i.e. the boundaries of the current page.

**Comment by JCCR** [comment]
Are the dialogs supposed to be created from a script embedded in the EPUB..
Or some sort of script that runs in the same context of Readium?

**Comment by benfinn** [comment]
Scripts running in the EPUB.

**Comment by ryanackley** [comment]
@benfinn I would highly recommend using a 3rd party javascript library to handle this simply because they handle all the edge cases and nitty gritty. Google 'modal dialog javascript library'. They generally require you to use a UI framework like jquery or bootstrap. 

If you have to build one yourself, then you should be using `position:fixed` not `position:absolute`. This places it in relation to the screen not the document.

**Comment by benfinn** [comment]
`position: fixed` solves my problem, but I haven't been using it because EPUB3 doesn't support it. Is there an alternative?

According to the EPUB3 spec:

"Note that the fixed value is not included in the EPUB 3 Style Sheets profile and its use is not recommended (see the oeb-page-head and oeb-page-foot custom properties for including static headers and footers)"

http://www.idpf.org/accessibility/guidelines/content/style/reference.php

**Comment by ryanackley** [comment]
I wasn't aware of that. For your particular use-case, the benefits may outweigh the risk.

Readium paginates by changing the relative position of the content document. Therefore you need to take this into account when calculating the necessary absolute position of the dialog. Also, Readium is one implementation of the EPUB3 spec. There are several others. I don't know if they paginate the same way.

I went through your list and checked each one in Readium.

window.innerWidth/window.innerHeight - These are accurate when I tested and represent the size of the content iframe on the screen. Not sure why yours are so small. This should be the size of the current page
Offset/Position of the original : the original what? 
Document heigh/widtht: Width seems accurate for the entire content document. Height looks like the sum of all columns. I think this is just a blink/webkit bug. The DOM is reporting the body height to be this large.

**Comment by benfinn** [comment]
Of the original link. In my use case, you hover over the link and the dialog appears.

window.innerHeight and innerWidth: I'm checking this with the latest Readium on Windows 7. Not sure if that makes a different.

However, if there's no other alternative than fixed, I'll go with that. Thank you!

**Comment by rkwright** [comment]
BTW, excluding fixed from EPUB 3 is one of my pet peeves which I am going to raise again for 3.1

**Comment by benfinn** [comment]
Honesty, Ric, I don't know if it really matters. Reading system compliance is so all over the map that you can pretty much operate on "What works in Webkit?" and it'll likely work in any reading system that handles Javascript at all.

**Comment by rkwright** [comment]
Oh, it works OK.  That isn't really the issue (to me) but the fact that EPUBCheck, for example, whines about it and it makes people reluctant to use if for (as far as I can see) no particularly good purpose.

**Comment by danielweck** [comment]
Can this issue now be closed? :)

**Comment by benfinn** [comment]
It can!
