### ISSUE TITLE
Can't get download of full, zipped .epub files to work

### ISSUE THREAD

**Issue by ddeheer** [readium/readium-js-viewer#382]
I have readium-js-viewer embedded in a page in my website, and I can successfully use it to read epubs that I've unzipped into their full directory structure. But when I try to access a .epub file that isn't unzipped, readium appears to just spin and doesn't ever display the contents.

I've looked at the network console in Chrome whilst doing this, and it appears that there aren't any errors in the requests/responses. And I'm not seeing any messages in the console window that gives me information on what's failing.

Is this a known problem? If not, is there a demo system that shows this functionality working? 

I'm not sure how to move forward with debugging the issue I'm seeing, so any pointers are appreciated.

**Comment by JCCR** [comment]
I believe uploading an .epub is only meant to work when readium-js-viewer is built as a chrome extension. I might be wrong though. @danielweck Do you know something about this?

**Comment by ryanackley** [comment]
Looks like a recently introduced bug. See #381. This definitely worked at some point.

**Comment by ddeheer** [comment]
It appears to be a problem associated with some device/browser combinations. I am able to get his to work on a PC on Chrome, but not on an iOS device with Chrome. It does not work on a Kindle on Silk.

**Comment by rkwright** [comment]
I am seeing this on both Chrome and Firefox on OSX 10.10.4

**Comment by danielweck** [comment]
Is your HTTP server providing adequate headers? See https://github.com/readium/readium-js-viewer/issues/381#issuecomment-128845837

**Comment by ddeheer** [comment]
I'm pretty sure this isn't a cross-site scripting issue since in my instance the epub is on the same server as the website. So that doesn't appear to be the problem.

**Comment by danielweck** [comment]
@ddeheer this isn't about HTTP CORS headers, just about `Content-Length`, see https://github.com/divshot/superstatic/issues/169

**Comment by ddeheer** [comment]
I see. I looked at the packets using the Chrome dev tools, and the correct  content length is coming back from the server when I use Chrome on my PC (which is the case that works), so this implies to me that the server is doing the right thing. 

I don't really know how to bring up the developer tools on Chrome on iOS, but the client behavior there is definitely different.

**Comment by danielweck** [comment]
Just to clarify: are you testing using the `develop` branch?
The `master` branch contains an older version of Readium that may not include the latest improvements in the "cloud reader" configuration.

**Comment by danielweck** [comment]
PS: on my corporate HTTP server, I had to modify the gzip Apache directive for EPUB loading to work correctly on the client / browser side:
```
SetEnv no-gzip 1
<ifModule mod_gzip.c>
  mod_gzip_on No
</ifModule>
```
As you can see, it works fine (this is `./dist/cloud-reader/` generated from `npm run dist`):
http://development.readium.divshot.io/?epub=http://www.daisy.org/projects/tobi/readium/epub_content/internal_link.epub

**Comment by ddeheer** [comment]
@danielweck  - I believe we're currently using the master branch. We'll try the develop branch.

**Comment by ddeheer** [comment]
@danielweck  - just for completeness, I did make sure that content compression was turned off on my server - but there's no difference in the behavior on iOS using Chrome - the .epub still doesn't render.

**Comment by danielweck** [comment]
@ddeheer Chrome-iOS EPUB loading failure is a known issue: https://github.com/readium/readium-js-viewer/issues/352

**Comment by ddeheer** [comment]
@danielweck  - I see that that issue #352 is not the highest priority, which I understand. 

At this point it is a high priority for us, and we're not familiar enough with the Readium codebase to fix the issue quickly. Is there anybody that you know of who is familiar with the code that we could pay on a consulting basis to look at this issue for us?

**Comment by danielweck** [comment]
@ddeheer just out of interest: why not recommend the use of the default Safari browser on iOS, instead of Chrome?

**Comment by ddeheer** [comment]
@danielweck - We don't have control of which browser our users choose, so we need to have a coherent experience across browsers.

**Comment by danielweck** [comment]
This was fixed here:
https://github.com/readium/readium-js-viewer/issues/381#issuecomment-139771326
