### ISSUE TITLE
Is there a way to turn off readium-js-viewer calls to readium-js-viewer/.git/HEAD ?

### ISSUE THREAD

**Issue by ddeheer** [readium/readium-js-viewer#383]
When I run readium-js-viewer on my website it makes an HTTP GET call to <mydomain>/readium-js-viewer/.git/HEAD. Of course this call always fails on my site. And, instead, it gets caught by the security service we use and it's flagged as an attempt to access a resource illegally.

Is there some way I can turn off the apparently unneeded HTTP GET call to readium-js-viewer/.git/HEAD so that I don't receive all the security alerts resulting from it?

**Comment by rkwright** [comment]
This definitely sounds like a bug.  We will take a look and fix it.

**Comment by danielweck** [comment]
Are you using a build created by `npm run dist`? (it sounds like you are using the raw source tree, which is designed to run locally on your development machine, not to be uploaded as-is on a HTTP server). If not, then this indeed looks like a new bug.

**Comment by davedmiller** [comment]
daniel, I work with ddeheer.  To build readium I followed the directions at: https://github.com/readium/readium-js-viewer
I first followed the steps in section "Initialize your repository" and then followed the steps in "Custom EPUB management and viewer application", but substituted "cloudReaderLite" for "cloudReader" to eliminate the "library" button in the UI.

**Comment by danielweck** [comment]
Hello @davedmiller I suggest you use the develop branch (master is not in sync yet): https://github.com/readium/readium-js-viewer/blob/develop/README.md#development

**Comment by danielweck** [comment]
Follow-up to above comments: I am unable to reproduce this behaviour when using "proper" builds (`npm run dist` ==> `./dist/cloud-reader/` or `./dist/cloud-reader-lite/`). Only the "no-optimize" development-time `./dev/*.html` RequireJS browser-based runtime utilizes XmlHTTPRequests to figure-out the Git versioning information from the local filesystem (well, through the HTTP server root folder structure, to be precise). In all other build cases, the version info is "baked" into the app bundles themselves, via `version.json` (which is pre-computed by a NodeJS build-time process).

For example, `npm run http`, then open the URL (you probably need to replace the LAN IP):
http://192.168.1.93:9090/dist/cloud-reader/?epub=http%3A%2F%2F127.0.0.1%3A8080%2Faccessible_epub_3
(this uses the baked `version.json`, so no HTTP requests)

Conversely:
http://192.168.1.93:9090/dev/index_RequireJS_no-optimize.html?epub=http%3A%2F%2F127.0.0.1%3A8080%2Faccessible_epub_3
(this "live" browser runtime has to access the Git info from the local folder structure, no pre-built `version.json`)

**Comment by danielweck** [comment]
Follow-up on this? As I said above, I am unable to reproduce this behaviour in a deployed packaged app (the Git SHA1 HTTP requests are only made in development mode, with the exploded app source tree).

**Comment by danielweck** [comment]
Please do not upload the raw source from the Git repository (un-optimized version of the code) to your HTTP server.
Instead, either download `Readium_cloud-reader.zip` from https://github.com/readium/readium-js-viewer/releases , or follow the instructions in the `README` to build the cloud reader yourself https://github.com/readium/readium-js-viewer/blob/develop/README.md
