### ISSUE TITLE
"annotations" plugin should be disabled by default (excluded from RequireJS build system)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#386]
CSON plugins config:
https://github.com/readium/readium-shared-js/blob/develop/plugins/plugins.cson

CSS `display:none` for highlighter icon (`.icon-annotation`):
https://github.com/readium/readium-js-viewer/blob/develop/src/css/viewer.css#L19

CC @JCCR who found out that the annotations plugins may in fact create memory leaks (when testing @dmitrym0 's prefetch implementation), and that the highlighting mechanism is out-of-date (unmaintained) compared to other forks / extensions (e.g. EvidentPoint).

**Comment by JCCR** [comment]
As I commented in the PR:

... I also spotted a large amount of growth with the JS + DOM nodes heap snapshots when switching back and forth between two of the same spine items. When doing a comparison of before and after I noticed the biggest items on the list were objects on the EpubAnnotations namespace, and some of Backbone's internals. After disabling the annotations plugin and repeating the same actions the memory growth lowered substantially, going from 5-10mb per spine item switch, to just 0.1-1mb

**Comment by danielweck** [comment]
Fixed:

https://github.com/readium/readium-shared-js/commit/4a8db2e841ca0054a6f5d199d887f2cac328c1aa#diff-e8c5eaf889e895e2bc68aef5eb21a4ac

https://github.com/readium/readium-js/commit/3c461cc3564425711b3410c2e5bde37b76e6b4af
https://github.com/readium/readium-js/commit/555d5043e2adc9a755552f6c0baf1803568b3007

https://github.com/readium/readium-js-viewer/commit/ece41a411eab89d53a5a6b2852db64f542bb2eaa

**Comment by danielweck** [comment]
Follow-up:
https://github.com/readium/readium-shared-js/issues/201
