### ISSUE TITLE
ESC Test Fails in Readium

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#387]
A prototype EPUB Test Suite test for the Embeddable Scriptable Components (ESC) fails.  The first (passive) test passes, but the second test (with the button) does not work.

The bugfile is [here](https://drive.google.com/drive/folders/0BzaNaBNAB6Fjfk8tdGJXcDB0d01HSFNwdjZoR1NrSjJEQlhFemRhQUoyUnZ0Ymg1VVY3N0U?hl=en)

**Comment by rkwright** [comment]
Further testing shows that it works fine in the preliminary version of 2.20.1 (out of the develop branch).  This is understandable, but will test a bit more to ensure we understand the net problem.

**Comment by danielweck** [comment]
@rkwright I believe this is now fixed, could you please check at your end?

**Comment by rkwright** [comment]
Yes, tested with latest build from master and it worked fine.  Closing
