### ISSUE TITLE
Distracting flashing title bar

### ISSUE THREAD

**Issue by gbitzes** [readium/readium-js-viewer#389]
Hi, I am having trouble reading comfortably on readium because of the flashing title bar. Here is what I mean - readium starts out with a solid black title bar:

![screenshot from 2015-08-22 16 56 12](https://cloud.githubusercontent.com/assets/3705326/9424268/176f24a4-48ef-11e5-9daf-4fb2dfb3f9bb.png)

After a few seconds of not moving the mouse, the bar turns white and shows the title of the book I'm reading:
![screenshot from 2015-08-22 16 56 20](https://cloud.githubusercontent.com/assets/3705326/9424271/29c612fc-48ef-11e5-8c07-0a2f146876e7.png)

Once I move the mouse, the bar turns black again. This happens several times per minute, making my reading experience pretty bad, it's very distracting.

I managed to disable this behavior by commenting out the following in css/viewer.css, and rebuilding the chrome extension - now the title bar is always black.
```
    -webkit-transition: all 10s ease-out;
    opacity:0;
```
in both 
```
    .hide-ui .navbar { ... }
```
and
```
    .hide-ui #left-page-btn, 
    .hide-ui #right-page-btn,
    .embedded .toc-visible #left-page-btn, 
    .embedded .toc-visible #right-page-btn { ... }
```

Would you consider fixing this permanently? Thanks

**Comment by dmitrym0** [comment]
@gbitzes the rationale for this feature is an uncluttered reading experience. I can see how the flashing would be annoying. As a data point, iBooks on iOS toggles controls with a longpress. Something to think about.

Offtopic, what window manager are you using? It really reminds me of ion3.

**Comment by danielweck** [comment]
Thank you @gbitzes for reporting this! It is a known problem, however:
https://github.com/readium/readium-js-viewer/issues/182
I am closing this issue, but cross-referenced it.

**Comment by gbitzes** [comment]
Thanks for the responses! I'll be keeping an eye on the other issue for updates.

@dmitrym0, my window manager is called i3wm, it is quite awesome.
