### ISSUE TITLE
git flow and submodule workflow problems

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#392]
We have run into a number of problems that *SEEM* to be related to our use of submodules and git-flow.  This issue is simply providing a place to discuss these issues.  Note that this is in readium-js-viewer, but could have been in any repo as it affects all of them.

Currently, Ric tried to push the 0.20 release but somehow, the changed folder structure in the 0.20 release (where readium-js changed significantly and readium-shared-js is a in a different folder and other parts of the folder structure changed) caused git flow to throw errors and abort - sort of (being a bash script, it's error handling is minimal at best).  Result is that when the dust settled, readium-shared-js in master had been nuked.  This has been reverted but the bad commit is still there.  However, that is a separate problem.  More generally it is not easy to see how git-flow can be used seamlessly with submodules.  The following threads are exploring this.

**Comment by rkwright** [comment]
Some random notes as I work through this:

* SourceTree.  
     * Seems to see some submodules but not all.  For example, it doesn’t see the readium-cfi-js submodule in readium-shared-js as a submodule.  Git does if you do ‘git submodule status’ from the command line but ST doesn’t.  Bug, one presumes.
* Daniel’s documentation says do:  git submodule foreach —recursive “git checkout develop”
    * Note the use of double-quotes.  If you use single-quotes (as the doc does) it works in the terminal on OSX but NOT in a bash script.  Has to be double-quotes.
    * Note that this does NOT operate on the root folder where the command is executed.  So the status of the root folder doesn’t change
    * There is a gotcha here because in order to use git-flow, one has to do 'git flow init’ in each folder to be part of the release.  BUT git flow init doesn’t work unless the “master” branch has been initialized (checked out) in each folder.

**Comment by rkwright** [comment]
git flow init
* This really puzzles me.  If you look at the git-flow [decomposition](https://gist.github.com/JamesMGreene/cdd0ac49f90c987e45ac):
* git flow init becomes “git init”, “git commit —allow-empty –m 'Initial commit', "git checkout –b develop master”
* This last command makes no sense to me.  Why would I want to create a new “develop" branch based on master?
* OTOH, git flow release start is:  “git checkout –b release/n.n develop
* This makes more sense as I am now creating the new release branch by cloning develop
* Also, note that the action of “git flow init” in the submodule folders causes them to be changed, so that each parent of the submodule now detects that the underlying submodule has changed and the parent now needs to be updated.

**Comment by rkwright** [comment]
Seems like the right flow (just plain git commands) is: 
**Initialization**

     None
**Start**

    git checkout develop                               # develop has to exist locally first
    git checkout –b release/0.20.1 develop  # create the release by cloning develop
    git push origin release/0.20.1                 # push the local changes to the remote to make them public
**Finish**

    git checkout master		             # switch to the master branch
    git merge —no-ff release/0.20.1	     # merge into master from the release branch
    git tag –a 0.20.1				     # tag that location in the master branch
    git checkout develop			     # now switch to the develop branch
    git merge —no-ff release/0.20.1	     # merge the release branch back 
    git branch –d release/0.20.1	     # finally, delete the release branch

With these commands, one can start at the bottom (readium-js-cfi) and create a new release branch.  When all 4 (e.g. for readium-js-viewer) repos are good with the right submodule pointers, repo is clean.
One still has the issue that various changes (including merging the previous release to master) may have made "master" ahead of develop (and hence the release branch).
To resolve this:

     git checkout release/0.20.1
     git merge --no-ff master

**Comment by danielweck** [comment]
Just a clarification:

@rkwright quote:
> Daniel’s documentation says do: git submodule foreach —recursive “git checkout develop”
> Note the use of double-quotes. If you use single-quotes (as the doc does) it works in the terminal on OSX but NOT in a bash script. Has to be double-quotes.

The documentation was updated a while ago to replace single with double quotes (thank you by the way for pointing this out): https://github.com/readium/readium-js-viewer/blob/develop/README.md#git-initialisation

> Note that this does NOT operate on the root folder where the command is executed. So the status of the root folder doesn’t change

True, but that's exactly why the *full* command stated in the documentation is: `git checkout BRANCH_NAME && git submodule foreach --recursive "git checkout BRANCH_NAME"`, not just the second part :)

**Comment by danielweck** [comment]
Just a note about `git merge --no-ff`: this is useful as it forces Git to record a separate merge commit for a given *feature* branch when it gets merged into *develop*, or for when a *release* branch is finalised and gets merged into *master* (typically, *feature* and *release* branches are deleted afterwards, so it helps to have some identifiable standalone merge commit in the Git history). However, there is another use of the `git merge` command in the context of maintaining a ongoing *feature* branch up-to-date with the latest changes from *develop*. In this case, fast-forward is the default behaviour of `git merge`, which I think makes sense because we do not want a new "intermediary" commit everytime this happens. We just want to be able to "mark" the finalisation of a *feature* or *release* branch.

<img width="504" alt="gitmergenoff" src="https://cloud.githubusercontent.com/assets/625201/9561260/858c3288-4e35-11e5-9766-b5728ead3a95.png">

**Comment by danielweck** [comment]
We're not using GitFlow -style branching anymore, see updated release process documentation:
https://docs.google.com/document/d/17-1k__eJUqeK0GWcH9eYqz8i-2U6CWj88_u7LTZHxwc
