### ISSUE TITLE
Building error 

### ISSUE THREAD

**Issue by 127** [readium/readium-js-viewer#393]
recursive checkout fails
```
Checking connectivity... done.
fatal: reference is not a tree: ca022b361d987b5088db9f386305f63f9dc89480
Unable to checkout 'ca022b361d987b5088db9f386305f63f9dc89480' in submodule path 'readium-js/readium-shared-js'
Failed to recurse into submodule path 'readium-js'
```

**Comment by ryanackley** [comment]
Release 0.20 is broken. You will need to work from master.

**Comment by danielweck** [comment]
The `master` branch is broken as well, please work from `develop` until a new clean `release` branch is created and merged into `master`.
Example of out of sync history:
https://github.com/readium/readium-cfi-js/commits/master
https://github.com/readium/readium-shared-js/commits/master

**Comment by 127** [comment]
thx!

**Comment by rkwright** [comment]
Re-opening this issue as a flag until we have master back in proper shape (tomorrow, we hope).

**Comment by danielweck** [comment]
The master branch works fine now (has been for some time, but we forgot to update this issue).
