### ISSUE TITLE
Cloud reader on Microsoft Edge, failed HTTP CORS header when fetching from browser cache

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#408]
This looks like an Edge-specific bug, as Internet Explorer, Chrome and Firefox work fine.

`SEC7120: Origin XYZ not found in Access-Control-Allow-Origin header. SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, Could not complete the operation due to error 80700013.`

The error goes away when the browser cache is cleared, or bypassed via the developer tools F12 (network tab). I am closing this issue immediately as I don't think we can do anything about it. We use regular Ajax / jQuery-wrapped XMLHttpRequest.

http://readium.surge.sh/?epub=https://dl.dropboxusercontent.com/u/38631221/CircularFLO_Published_EPUBs/JigsawPlaced

http://readium.surge.sh/?epub=https://dl.dropboxusercontent.com/u/38631221/CircularFLO_Published_EPUBs/CircularFLO_v5_1_promo

http://readium.surge.sh/?epub=https://dl.dropboxusercontent.com/u/38631221/CircularFLO_Published_EPUBs/baby_jigsaw

**Comment by wfahmy** [comment]
Hi
  I am experiencing same issue you explained in this post, has there been any fix for that?
Thanks

**Comment by danielweck** [comment]
Do you compile the Readium cloud/web reader yourself, or do you use an off-the-shelf ready-to-use build?

Which GitHub revision are you using? Latest code from the `develop` branch? ( https://readium.firebaseapp.com or https://readium.surge.sh )

**Comment by wfahmy** [comment]
I am not using Readium. I have an issue with a 3rd party component when I use it from my web app I keep getting the same error that you get and the only fix is to force the browser to get resources from the browser on the dev tools which is obviously is not a fix I can tell my users to do. The error happens with IE but with Chrome things are fine
