### ISSUE TITLE
MathJax inclusion not occurring when namespace'ed math tags are present

### ISSUE THREAD

**Issue by cene-co-za** [readium/readium-js-viewer#418]
I have many epub's that use a namespace'ed **math** tag.
Like so ...
```html
<html xmlns:m="http://www.w3.org/1998/Math/MathML" ...
...
<m:math ...
```

The following line

https://github.com/readium/readium-js-viewer/blob/e60209a41940c6c48ed02b828f9a3d5973661465/src/js/workers/ContentTransformer.js#L65

Doesn't catch the math tag in my example above.
A possibly solution is something like

```javascript
(contentDocumentHtml.search(/\<([\w\d]+\:)?math\s/) > -1)
```

Or... am I missing something completely here?

**Comment by danielweck** [comment]
Thank you @cene-co-za 
Duplicate: https://github.com/readium/readium-js-viewer/pull/414 and https://github.com/readium/readium-js/pull/117
