### ISSUE TITLE
test books give error when first opening on latest build 2.22.0-alpha

### ISSUE THREAD

**Issue by duanwalker** [readium/readium-js-viewer#420]
https://mail.google.com/mail/u/0/?ui=2&ik=ce4ec53148&view=fimg&th=150495ea69fd0b72&attid=0.1.1&disp=emb&attbid=ANGjdJ_WI7h5IpMaMBJxWOQwhUaSVYkssTqzvOQKGkTeGfoNoxAM_x7XSI2mbuxrvmNLtSYDvJSDmmbDS7Nq1FBaXbf4G2llVSKeH814YNmiFL5S-PiGGVTgUB9EpBo&sz=w1244-h778&ats=1444402143660&rm=150495ea69fd0b72&zw&atsh=1

student intern reports this error when opening "epub-test-0101-20150521"  also "0102" in latest build. i also was able to reproduce this error. 
book finally opened on 2nd or 3rd attempt to open.

**Comment by rkwright** [comment]
I cannot open the above link (Google wants me to create yet another gmail account).  Is the link just a screen-shot of the error?  If so, can you please simply drag the image into the issue tracker?  Then github will manage the image storage.

**Comment by duanwalker** [comment]
i did a click and drag for the original link above. below is a copy paste and the next was a file upload.

![image](https://cloud.githubusercontent.com/assets/7536426/10398312/63976dfe-6e7a-11e5-95b9-1ecb7ea5fbff.png)
![19-9-15](https://cloud.githubusercontent.com/assets/7536426/10398320/6aa4d258-6e7a-11e5-8a9d-e16ad183ac39.png)


can you see these?

**Comment by rkwright** [comment]
Yes, thank you.

**Comment by danielweck** [comment]
Works fine at my end on Windows 10, Chrome, Firefox, Edge, but fails on Internet Explorer.

http://development.readium.divshot.io/?epub=epub_content%2Fepub30-test-0101-20150521.

http://development.readium.divshot.io/?epub=epub_content%2Fepub30-test-0102-20150521.

Thanks for reporting this!

**Comment by larsvoigt** [comment]
Hmm @danielweck  if I click at your links I get the reported error.
But thats only an issue of the link layout or markdown or whatever :). 
The last dot of the link url will be ignored or deleted.

With this "fixed" link:
[http://development.readium.divshot.io/?epub=epub_content%2Fepub30-test-0101-20150521.](http://development.readium.divshot.io/?epub=epub_content%2Fepub30-test-0101-20150521.)
 it works fine for me on win7(chrome, ff41, ie11) and also on linux(chrome,ff) .

**Comment by danielweck** [comment]
Ah, `window.location.origin` needs to be shimmed to `window.location.protocol + '//' + window.location.host` on Windows 10 + Internet Explorer 11. This should work on Safari as well (as per above screenshot). I'm about to push a fix.

**Comment by danielweck** [comment]
Fixed: https://github.com/readium/readium-js-viewer/commit/0cc99192b5fdba527caf57bc032dd892a8cfb2ed
Please let me know if it works (allow 15 minutes for the `divshot.io` deployment, as TravisCI has only just kicked-in)

**Comment by danielweck** [comment]
@larsvoigt thanks, I fixed the links in my message (Markdown parser didn't pick-up the end-of-line dot)
