### ISSUE TITLE
test books still will not open on iPad chrome

### ISSUE THREAD

**Issue by duanwalker** [readium/readium-js-viewer#421]
student intern Ivana reports not being able to open test books in iOS chrome and firefox. I was able to reproduce this error on iOS chrome.
works fine on safari for iOS and windows browsers. 
may be related to issue #420 

![image](https://cloud.githubusercontent.com/assets/7536426/10487494/3c396190-7262-11e5-9c0d-2aad5f88b619.png)

**Comment by danielweck** [comment]
Thanks @duanwalker !
Duplicate: https://github.com/readium/readium-js-viewer/issues/352
