### ISSUE TITLE
PaginationChanged is triggered twice on spine item changes

### ISSUE THREAD

**Issue by lmvco** [readium/readium-js-viewer#422]
I am doing tests to viewer events when turning a page and I noticed that:

1) When I am in the middle of a spine item and I turn page, the PaginationChanged is correctly triggered and the paginationData attached to the event seems to be correct

2) However, when I am in the last page of a spine item and I turn page, the PaginationChanged event is fired twice: the first contains information of current page (which is repeated) and the second one contains information of new spine item page.

Is this a known issue?

**Comment by danielweck** [comment]
Interesting, thanks for pointing this out. Is this with the latest code from the `develop` branch?

**Comment by lmvco** [comment]
I tested it here - http://development.readium.divshot.io/

**Comment by danielweck** [comment]
Thanks @lmvco that's the `develop` branch indeed.

**Comment by danielweck** [comment]
Note that the "CFI improvements" feature branch https://github.com/readium/readium-shared-js/tree/feature/intel-cfi-improvements includes a new "event tracer" DEBUG flag (console logging) https://github.com/readium/readium-shared-js/blob/feature/intel-cfi-improvements/js/globals.js#L30 Some redundant events were spotted and fixed, and this should be merged to develop soon.

@lmvco I'm not 100% sure whether this addresses your bug though, would you please be able to check? (to test, you must switch to the "CFI improvements" feature branch in `readium-shared-js`, `readium-js`, and `readium-js-viewer`)

**Comment by rkwright** [comment]
Note that the Intel/CFI improvements branch HAS been merged to develop as of mid-January 2016.

**Comment by danielweck** [comment]
This is an obsolete issue. Unable to reproduce.
