### ISSUE TITLE
error building output files for cloudreader

### ISSUE THREAD

**Issue by rthomas62** [readium/readium-js-viewer#427]
I am still not able to create a build-output on my windows 7 64bit pc. I tried several occasions and with different master versions like 0.20 0.21 and 0.22 alpha and the development version. Went trhough the steps from the read.me file. I Installed global cli of node, git, npm, grunt and bower 
It won't build the different versions in the output directory for the readium viewer. Why not make a full  readium Cloudreader and Cloudreader Lite version in zip package of the latest stable build available at github to deploy instantly on a static webserver. .I have the following error npm-log:

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli 'C:\\Users\\Rienk\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli 'run',
1 verbose cli 'dist' ]
2 info using npm@2.14.0
3 info using node@v0.12.7
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info predist readium-js-viewer@0.20.0-alpha
6 verbose unsafe-perm in lifecycle true
7 info readium-js-viewer@0.20.0-alpha Failed to exec predist script
8 verbose stack Error: readium-js-viewer@0.20.0-alpha predist: `npm run build && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/mkdirp/bin/cmd.js dist`
8 verbose stack Exit status 1
8 verbose stack at EventEmitter.<anonymous> (C:\Users\Rienk\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:214:16)
8 verbose stack at EventEmitter.emit (events.js:110:17)
8 verbose stack at ChildProcess.<anonymous> (C:\Users\Rienk\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
8 verbose stack at ChildProcess.emit (events.js:110:17)
8 verbose stack at maybeClose (child_process.js:1015:16)
8 verbose stack at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
9 verbose pkgid readium-js-viewer@0.20.0-alpha
10 verbose cwd C:\Users\Rienk\readium-js-viewer
11 error Windows_NT 6.1.7601
12 error argv "node" "C:\\Users\\Rienk\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
13 error node v0.12.7
14 error npm v2.14.0
15 error code ELIFECYCLE
16 error readium-js-viewer@0.20.0-alpha predist: `npm run build && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/mkdirp/bin/cmd.js dist`
16 error Exit status 1
17 error Failed at the readium-js-viewer@0.20.0-alpha predist script 'npm run build && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/mkdirp/bin/cmd.js dist'.
17 error This is most likely a problem with the readium-js-viewer package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error npm run build && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/mkdirp/bin/cmd.js dist
17 error You can get their info via:
17 error npm owner ls readium-js-viewer
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]
:

**Comment by danielweck** [comment]
Hello, thanks for your feedback, and sorry to hear about your troubles (I am on Windows 10, no problems building here).
I recommend that you update your NodeJS / NPM binaries to the latest version available (4.2.1): https://nodejs.org

Regarding your suggestion to package the cloud-reader and cloud-reader-lite distributions into zip files, and upload them to the GitHub release page: I agree. I'll look into this, and I will probably decide to include the sourcemaps, plus a sample book in the library.
See: https://github.com/readium/readium-js-viewer/issues/428

**Comment by rkwright** [comment]
Agreed about the packaging.  It's something (or at least similar to) that we have discussed.

**Comment by danielweck** [comment]
Cloud reader zip now uploaded to GitHub's releases: https://github.com/readium/readium-js-viewer/releases/tag/0.23.0-alpha
We're working on a few improvements (e.g. folder structure, sample epubs, web reader lite), but you can already use this zip.

**Comment by danielweck** [comment]
Both the cloud reader full and lite are now uploaded to the GitHub release area:
https://github.com/readium/readium-js-viewer/releases/tag/0.23.0-alpha
