### ISSUE TITLE
i have an issue while initializing readium js viewer 

### ISSUE THREAD

**Issue by rohanmashiyava** [readium/readium-js-viewer#429]
here is error log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'prepare' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose stack Error: ENOENT, open '/home/theta-1-linux/Desktop/working/readium/readium-js-viewer/package.json'
4 verbose stack     at Error (native)
5 verbose cwd /home/theta-1-linux/Desktop/working/readium/readium-js-viewer
6 error Linux 3.19.0-30-generic
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prepare"
8 error node v0.12.2
9 error npm  v2.7.4
10 error path /home/theta-1-linux/Desktop/working/readium/readium-js-viewer/package.json
11 error code ENOENT
12 error errno -2
13 error enoent ENOENT, open '/home/theta-1-linux/Desktop/working/readium/readium-js-viewer/package.json'
13 error enoent This is most likely not a problem with npm itself
13 error enoent and is related to npm not being able to find a file.
14 verbose exit [ -2, true ]

**Comment by danielweck** [comment]
On your filesystem, does this file exist?

`/home/theta-1-linux/Desktop/working/readium/readium-js-viewer/package.json`

**Comment by danielweck** [comment]
If not, what are the permissions in the containing folder?
Could you try again after moving `readium-js-viewer` into your home folder?

**Comment by rohanmashiyava** [comment]
Hey Daniel

Thanks, it works for me


*Thanks & Regards*
Rohan M.

rohan@thetatechnolabs.com
www.thetatechnolabs.com

*This message and any files attached to it are intended for the use of the
addressee only and may contain private and confidential material, the
disclosure of which is prohibited by law. If you are not the intended
recipient, please note that disclosure, distribution or copying of this
message and any attachments is strictly prohibited.*
