### ISSUE TITLE
Media Overlays playback rate setting (user preference): needs finer steps

### ISSUE THREAD

**Issue by pettarin** [readium/readium-js-viewer#43]
Currently, the Media Overlays playback rate can be adjusted in 0.5x increments, from ~0x to 4x.

In many practical cases, finer steps around 1x are needed, being 1x too fast, and 0.5x too slow.  For reference, Menestrello 2.4.0. uses the following steps:

['0.5', '0.6', '0.7', '0.8', '0.85', '0.9', '0.95', '1.0', '1.1', '1.2', '1.35', '1.5', '1.75', '2.0']

**Comment by pettarin** [comment]
To close this issue, reducing the value of the `step` attribute from `0.5` to `0.1` or `0.05` in:

https://github.com/readium/readium-js-viewer/blob/c94d4c16f35839812ceb50f9ae7d485b105057ce/src/templates/reader-navbar.html#L101

suffices.

**Comment by danielweck** [comment]
Thanks @pettarin 
Fixed here: https://github.com/readium/readium-js-viewer/commit/cc767e9ad2856a9281dc75320c0dd710dfdfd8d2

Note: the cloud / web reader build from the `develop` branch is automatically deployed to these URLs (via TravisCI):
http://readium.surge.sh/?epubs=http%3A%2F%2Fdevelopment.readium.divshot.io%2Fepub_content%2Fepub_library.json
http://development.readium.divshot.io/

**Comment by pettarin** [comment]
Great, thank you!
