### ISSUE TITLE
node_module/URIjs Filename changed

### ISSUE THREAD

**Issue by akshayKrSingh** [readium/readium-js-viewer#430]
It seems that the package name has been modified in the latest release of URIjs, so when running `npm install` within readium-shared-js, the folder name is `urijs` but the Require_Config.js expects - 'URIjs'.

**Comment by danielweck** [comment]
This external change was addressed about a month ago in the develop branch:
https://github.com/readium/readium-shared-js/commit/9a3e71ac22b5e4b326c5da9fecbbe5f24f81cf27
However the master branch is out of date, sorry for the inconvenience. I will git-cherry-pick the commit, thanks for the heads-up!

**Comment by danielweck** [comment]
I created a new issue in readium-shared-js

**Comment by akshayKrSingh** [comment]
Awesome!!! I didn't go through the development branch. My bad :disappointed:

**Comment by danielweck** [comment]
@akshayKrSingh no need to apologize, it is our fault if the master is broken, because of a flaw in our current build system (major revisions of NPM external dependencies can break our builds). I filed an issue here:
https://github.com/readium/readium-js-viewer/issues/432

**Comment by akshayKrSingh** [comment]
:+1:
