### ISSUE TITLE
TOC Prompt remains on screen when TOC closed

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#434]
This was reported on the Google Chrome Store support page: 
https://chrome.google.com/webstore/detail/readium/fepbnnnkkadjhjahcafoaglimekefifl/support?hl=en-US

If one opens the TOC there is a small popup prompt ("Table of Contents (t)") but if you close the TOC using it's own affordance (checkbox in upper right), the popup prompt is not closed and cannot then be closed at all.
The same is true of the Library pane.
Verified in 2.18.2

**Comment by danielweck** [comment]
The dark tooltips pop-up for keyboard-focusable UI items (typically, buttons), when they gain focus.
The keyboard focus ring / outline is displayed around the TOC button, which suggests that upon closing the TOC pane, this button gains focus. This makes sense from a UX perspective, but let's bear in mind @beckya11y (Becky Gibson) work-in-progress feature branch, which aims to improve user interaction with the TOC panel.

**Comment by danielweck** [comment]
Related: https://github.com/readium/readium-js/issues/131

**Comment by becka11y** [comment]
I can't think of any way to improve this except to add a timer on the tooltips so they will disappear after x seconds.  The tooltip remains displayed while the button has focus.  I agree with Daniel that it makes sense that the TOC button gets focus when the TOC is closed. However, we can't assume that the user will change focus so the tooltip should be removed after some length of time. The question is, how long should it remain visible?  I would start at 5 seconds but will look for recommended times in order to accommodate different reading speeds.

**Comment by danielweck** [comment]
Note that the `delay: { show: 100, hide: 5000 }` config can be added to Bootstrap's tooltip constructor:

https://github.com/readium/readium-js-viewer/blob/develop/src/js/ReadiumViewer.js#L212

https://github.com/readium/readium-js-viewer/blob/develop/src/js/ReadiumViewerLite.js#L22


```
var tooltipSelector = 'nav *[title]';

...

    $(document.body).tooltip({
        selector: tooltipSelector,
===================>        delay: { show: 100, hide: 5000 },
        placement: 'auto',
        container: 'body'
    }).on('show.bs.tooltip', function(e){
        $(tooltipSelector).not(e.target).tooltip('destroy');
    });
```

...however, this only works for mouse enter/leave, not for keyboard focus. One other option would be manually set a timeout in the `show.bs.tooltip` event listener.

**Comment by danielweck** [comment]
As per the previous comment, adding a timeout works better than relying on Bootstrap's built-in delay:show/hide config. See code below.

https://github.com/readium/readium-js-viewer/blob/develop/src/js/ReadiumViewer.js#L212

https://github.com/readium/readium-js-viewer/blob/develop/src/js/ReadiumViewerLite.js#L22


```
var tooltipSelector = 'nav *[title]';

...

    $(document.body).tooltip({
        selector: tooltipSelector,
// delay: { show: 100, hide: 5000 },     NO NEED, SEE TIMEOUT BELOW
        placement: 'auto',
        container: 'body'
    }).on('show.bs.tooltip', function(e){
        $(tooltipSelector).not(e.target).tooltip('destroy');

// ================
        var target = e.target; 
        setTimeout(function(){
            $(target).tooltip('destroy');
        }, 5000);
// ================
    });
```

**Comment by danielweck** [comment]
Fixed in PR: https://github.com/readium/readium-js-viewer/pull/486
