### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by icegit** [readium/readium-js-viewer#441]
I am a user of Chrome extension and wanted to deploy it to my private server as a cloud reader. However, during the installation after `npm run http` I get some errors and it fails as below. It is an Ubuntu 14.04.3 LTS server. I have very little experience with NodeJS as well, does anyone know what is wrong with my setup?

+++++++ danielweck/http-server >> indexzero/http-server [master]
Up to date.
build-config  host_app_reference_files  license.txt   plugins         README.md
build-output  js                        package.cson  PLUGINS.md      static
dev           lib                       package.json  readium-cfi-js

> readium-shared-js@0.22.0 prepare:dependencies /www/private/bk/readium-js/readium-shared-js
> npm install && npm update && node readium-cfi-js/readium-build-tools/gitHubForksUpdater.js

npm http GET https://registry.npmjs.org/FontLoader
npm http GET https://registry.npmjs.org/CSSOM
npm http GET https://registry.npmjs.org/urijs
npm http GET https://registry.npmjs.org/backbone
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/domReady
npm http GET https://registry.npmjs.org/jquerySizes
npm http 200 https://registry.npmjs.org/urijs
npm http 200 https://registry.npmjs.org/underscore
npm http 404 https://registry.npmjs.org/jquerySizes
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-52-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /www/private/bk/readium-js/readium-shared-js
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm http 200 https://registry.npmjs.org/backbone
npm http 404 https://registry.npmjs.org/FontLoader
npm http 404 https://registry.npmjs.org/domReady
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-52-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /www/private/bk/readium-js/readium-shared-js
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-52-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /www/private/bk/readium-js/readium-shared-js
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm http 404 https://registry.npmjs.org/CSSOM
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-52-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /www/private/bk/readium-js/readium-shared-js
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /www/private/bk/readium-js/readium-shared-js/npm-debug.log
npm ERR! not ok code 0
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
root@XGNL001:/www/private/bk# npm run http

> readium-js-viewer@0.22.0 http /www/private/bk
> echo > open_webbrowser.js && parallelshell "npm run dowatch:plugins" "npm run http:app_ebooks"

sh: 1: parallelshell: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

**Comment by danielweck** [comment]
Your current NodeJS version is too old, could you please update and report back?
Also, you should invoke the build command `npm run dist+sourcemap` and upload the generated `dist/cloud-reader` to your HTTP server. You may add expanded EPUB files to the `epub_content` subfolder, and ideally register them in the `epub_library.json` file. However this is only to populate the library view, and you may in fact reference any EPUB HTTP location directly from the cloud reader URL parameter `epub`. All info in `README.md`.
Closing, but feel free to reopen if the problem persists.

**Comment by icegit** [comment]
Thank you for the help, I could successfully build it.
