### ISSUE TITLE
An error about JS

### ISSUE THREAD

**Issue by ccnucheng** [readium/readium-js-viewer#443]
Hello everyone, I use ReadiumSDK to develop a MFC reader, but to open the page times out of the denial of access to the error, I would like to ask how to solve, thank you very much!

row:6
char:9
error: denied access
code:0
url:http://localhost:5000/js/views/media_overlay_data_injector.js

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/SDKLauncher-Windows/issues/30
