### ISSUE TITLE
Question about embedding a YouTube video in an EPUB

### ISSUE THREAD

**Issue by da70** [readium/readium-js-viewer#447]
Hi,

This is not so much an issue report as it is a question.  One of the owners of a site we're developing would like to have a YouTube video play embedded in an EPUB being read in ReadiumJS viewer.

I looked through the EPUB specifications for versions 2 and 3.  Version 2 does not seem to mention remote resources, but EPUB 3 provides instructions for fulfilling what would seem to be our use case.  Since we don't currently have EPUB 3 books yet, I experimented with the sample *Moby Dick* that is included in the viewer github repo.

I added the following to a copy of the exploded *Moby Dick* EPUB:

`OPS/nyup-99.xhtml`, which has a standard YouTube embed `<iframe>` (YouTube is deprecating `<object>`):

```html
<iframe
 width="560"
 height="315"
 src="https://www.youtube.com/watch?v=P-cM6xo_NTU"
 frameborder="0">
</iframe>
```
Added to `OPS/package.opf`:

```html
<item id="nyup-99" href="nyup-99.xhtml" media-type="application/xhtml+xml" properties="remote-resources"/>

...

<itemref linear="yes" idref="nyup-99"/>
```

Added to `OPS/toc.xhtml`:

```html
<li class="toc-Chapter-rw" id="toc-chapter_000">
  <a href="nyup-99.xhtml">NYUP-99 test</a>
</li>
```

I navigated to the page in ReadiumJS viewer, and found the video had failed to load due to failed `XMLHttpRequest` request - no `Access-Control-Allow-Origin` header in response from server.

I noticed the `<iframe>` had been rewritten so that `src` had been changed to `data-src`.  Looked in the code and found in `readium-js/js/Readium.js`:

```javascript
 var _contentDocumentTextPreprocessor = function(src, contentDocumentHtml) {

....
            contentDocumentHtml = contentDocumentHtml.replace(/(<iframe[\s\S]+?)src[\s\S]*?=[\s\S]*?(["'])([^"']+?)(["'])([\s\S]*?>)/g, '$1data-src=$2$3$4$5');
//console.debug(contentDocumentHtml);

...
```

...and also found the code in `iframe_zip_loader.js` that loads all content of `<iframe>` elements via AJAX calls.  Since YouTube does not send back an `Access-Control-Allow-Origin` header, as per CORS rules the browser will not load it.

Rather than attempt to embed the YouTube video via some brittle hack that bypasses the ReadiumJS `<iframe>` loading mechanism, we wanted to find out if this use case is something that is allowable according to ReadiumJS security or content policies?  Does ReadiumJS have an official stance on remote resources access control?

If it turns out that our use case can't be accommodated due to security concerns, that is totally fine and understandable, and we can pursue alternatives.  The site owners just wanted me to first get an official definitive answer from Readium, though, as they consider this a top priority.

Thanks!

**Comment by danielweck** [comment]
I am about to push a fix for this, thank you for pointing this bug out!

**Comment by danielweck** [comment]
Fixed, and tested with HTTP(S) iframe@src
Test app should be deployed online soon (Travis continuous integration build in progress...):
https://readium.firebaseapp.com/?epub=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2FepubReadingSystem&

Meanwhile, this manually-deployed app demonstrates this fix:
https://readium.surge.sh/?epub=https%3A%2F%2Fdl.dropboxusercontent.com%2Fu%2F585153%2FReadium%2Febooks%2FepubReadingSystem&

(go to the last page of the EPUB)

**Comment by da70** [comment]
Thanks much for this very fast fix!

I temporarily switched our version of ReadiumJS viewer to `develop` branch HEAD and verified that the YouTube is now loading and playing correctly in our edited _Moby Dick_.  Do you have a sense of when this fix will get into `master`?  We'd prefer to run our site on that branch if at all possible.
I believe our site owner wants to have the YouTube feature available for their online EPUBs by February.  If the fix won't be in `master` by then we could probably just temporarily apply [317b926|https://github.com/readium/readium-js/commit/317b926959a664759994831b6e20358a48109792] as a patch to our version.

**Comment by da70** [comment]
Edited my original post and fixed the `src` URL in the `<iframe>` sample.  Changed
`https://www.youtube.com/watch?v=P-cM6xo_NTU` to `https://www.youtube.com/embed/P-cM6xo_NTU`.

This was not the YouTube video URL I originally tested that threw the `Access-Control-Allow-Origin` error.  The original video was for a full-length _Moby Dick_ movie made decades ago that someone had uploaded to YouTube.  To avoid potential copyright or takedown issues, I switched the URL to an official _Mody Dick_ 2010 movie trailer before writing this Github ticket, but I accidentally used the `watch` URL instead of the `embed` URL.  When using the `watch` URL in Readium, the error changes to `x-frame-options` set to `SAMEORIGIN`, which indeed YouTube does for `watch` URLs.

Luckily Daniel noticed the mistake and used the correct URL in example in [7b39cd5|https://github.com/readium/readium-js-viewer/commit/7b39cd5fb093ac1e3ca687b1ccbed3c099ee37fe].  I fixed it in my post anyway, to prevent confusion in case someone comes across this page in the future.

**Comment by danielweck** [comment]
@da70 You can indeed git-cherry-pick the relevant commits into your branch (which I assume is based upon Readium's official master), or you may use the current revision / tip of the develop branch, which I think is quite "safe" (i.e. low risk of regression bug) whilst adding a couple of useful features / bug-fixes for the cloud/web reader.
See code diff:
https://github.com/readium/readium-js-viewer/compare/develop
https://github.com/readium/readium-js/compare/develop
https://github.com/readium/readium-shared-js/compare/develop
https://github.com/readium/readium-cfi-js/compare/develop

**Comment by danielweck** [comment]
PS:
@da70 I'm sure you know that already, but here's a note for other devs who revisit this discussion thread:
YouTube uses secure HTTPS URLs, so the Readium cloud-reader app instance must be hosted on a HTTPS server as well, otherwise the web browser rejects the iframe-hosted YouTube app.

**Comment by da70** [comment]
@danielweck Thanks for the reminder about HTTP/HTTPS mixing.  I just checked our situation, and unfortunately it seems the switch to HTTPS hasn't been made on the particular (somewhat under-powered) hosts we're using.  I think it should still be more or less okay though since it is HTTPS inside HTTP as opposed HTTP inside HTTPS (which is blocked by default by modern browsers): [Why you should not mix http and https when using iframes | Advanced iframe | TinyWebGallery Blog|http://www.tinywebgallery.com/blog/iframe-do-not-mix-http-and-https] - see "2. http with https iframe".  It's bad practice, but it looks like the video will still load, with possible side effects related to cookies and sessions (which we're not really making use of for this site for the time being).  We unfortunately don't have a choice. :(
We've been discussing the timeline for switching to HTTPS only, and when we revisit the topic I'll mention this issue.  Maybe we need to focus on the infrastructure change sooner rather than later.

That is reassuring that you feel `develop` is low risk for regression.  I'll be out of the office from tomorrow until late January, but I'll leave a note for the other devs that `develop` might be stable enough to use for the near term.
