### ISSUE TITLE
Request for a simple method to test readium on an existing webserver

### ISSUE THREAD

**Issue by carbontracking** [readium/readium-js-viewer#451]
Hello Daniel,
Following up on existing issues
#266 #268 

I'm in the same boat as the OP, i.e. difficulties with the developer oriented install procedure.

Like the OP I'd just like to be able to upload the cloudReader(lite) to my webserver and publish a single ebook for test.
From the comments on the issues #266 #268 I still don't see a pre-built version of the cloudReader(lite) than can be easily installed without having to go through the steps that require dev knowledge.

Best regards,

Colm OGAIRBHITH

**Comment by danielweck** [comment]
Hello,
could you please try the `Readium_cloud-reader-lite.zip` download link from the "release" GitHub page, and report back?
https://github.com/readium/readium-js-viewer/releases

I am closing this issue for now, but feel free to re-open if I misunderstood your query. Thanks!

**Comment by carbontracking** [comment]
That's brilliant Daniel, thanks for the extremely rapid response. It does exactly what I want and I can now publish my ebooks on my webserver

Best regards / Colm

**Comment by danielweck** [comment]
@carbontracking good to hear. Do not hesitate to post your feedback on this issue tracker. Dan
