### ISSUE TITLE
Amazon AWS S3

### ISSUE THREAD

**Issue by K1N5L4Y3R** [readium/readium-js-viewer#452]
Note: this is not an actual issue anymore, I just wanted to share what I did to solve a problem I had with epubs hosted in S3. If there's other place where I should be putting this instead of in the issues please let me know.
I HAD an issue when hosting .epubs on an Amazon S3. The reader would complain about CORS and then about insecure header (content-length). The solution was to give S3 this CORS configuration:

<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
        <ExposeHeader>Accept-Ranges</ExposeHeader>
        <ExposeHeader>Content-Range</ExposeHeader>
        <ExposeHeader>Content-Encoding</ExposeHeader>
        <ExposeHeader>Content-Length</ExposeHeader> 
    </CORSRule>
</CORSConfiguration>

Hope it helps anyone having problems with S3.

**Comment by K1N5L4Y3R** [comment]
Proper CORS configuration (forgot markdown styling):

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
        <ExposeHeader>Accept-Ranges</ExposeHeader>
        <ExposeHeader>Content-Range</ExposeHeader>
        <ExposeHeader>Content-Encoding</ExposeHeader>
        <ExposeHeader>Content-Length</ExposeHeader> 
    </CORSRule>
</CORSConfiguration>

```

**Comment by danielweck** [comment]
Thanks, that's great! :)
I added your AWS S3 config example in this document: https://docs.google.com/document/d/1RK_59-75OSE0PA6wexD9rYHQLnNYfoKIpsnH3SmDpUc
(which is linked from the README https://github.com/readium/readium-js-viewer/blob/develop/README.md )

**Comment by danielweck** [comment]
Also note the Apache `.htaccess` config:

```
<ifModule mod_headers.c>

Header set Access-Control-Allow-Origin "*"

Header set Access-Control-Allow-Credentials "true"

Header set Access-Control-Allow-Methods "GET, HEAD, POST"

Header set Access-Control-Allow-Headers "Range, Content-Type, Origin, X-Requested-With, Accept, Accept-Language, Content-Language"

Header set Access-Control-Expose-Headers "Accept-Ranges, Content-Encoding, Content-Type, Content-Length, Content-Range, Content-Language, Cache-Control, Expires, Last-Modified, Pragma"

</ifModule>
```

**Comment by danielweck** [comment]
Finally, also note the (now-defunct) DivShot.io JSON configuration:
(Readium is now deployed on Firebase, which uses the same Superstatic server as DivShot, but unfortunately without support for custom HTTP CORS headers in the free version :( )

```
"headers": {
    "/epub_content/**": {

      "Access-Control-Allow-Origin": "*",

      "Access-Control-Allow-Credentials": "true",

      "Access-Control-Allow-Methods": "GET, HEAD, POST",

      "Access-Control-Allow-Headers": "Range, Content-Type, Origin, X-Requested-With, Accept, Accept-Language, Content-Language",

      "Access-Control-Expose-Headers": "Accept-Ranges, Content-Encoding, Content-Type, Content-Length, Content-Range, Content-Language, Cache-Control, Expires, Last-Modified, Pragma"
    }
  }
```
