### ISSUE TITLE
ChromeApp: Missing files

### ISSUE THREAD

**Issue by DeependraKhangarot** [readium/readium-js-viewer#454]
I was trying to setup ChromeApp but I think there is some issue with files.

In "index.html"

one JS file is referred that is "scripts/readium-js-viewer_all_CHROMEAPP.js" but there is no such file and "scripts" folder.

Favicon icons referred from "images" folder but there is no such folder exists.

CSS files referred from the folder "CSS" but the folder doesn't exist.

There is one more entry in the manifest.json "default_locale" : "en_US", but no _locale folder exists.

I have cloned the repository from "https://github.com/readium/readium-js-viewer.git".

I am using Chrome Dev Editor.

It would be great if someone can guide me to setup ChromeApp.

**Comment by danielweck** [comment]
Please follow the build instructions in https://github.com/readium/readium-js-viewer/blob/develop/README.md
(I think you are looking at the raw code, you need to compile the app first)
