### ISSUE TITLE
ChromeApp : Build failed

### ISSUE THREAD

**Issue by DeependraKhangarot** [readium/readium-js-viewer#456]
Thanks, Daniel Weck for the reply.

I have followed the build instructions in https://github.com/readium/readium-js-viewer/blob/develop/README.md.

But the build failed with some errors, below is the log file content:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prepare' ]
2 info using npm@3.3.12
3 info using node@v5.4.0
4 verbose run-script [ 'prepare' ]
5 info lifecycle readium-js-viewer@0.22.1~prepare: readium-js-viewer@0.22.1
6 verbose lifecycle readium-js-viewer@0.22.1~prepare: unsafe-perm in lifecycle true

7 verbose lifecycle readium-js-viewer@0.22.1~prepare: PATH: 
C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;
D:\Projects\HMH\ChromeBook\GIT-MASTER\readium-js-viewer\node_modules\.bin;
C:\ProgramData\Oracle\Java\javapath;
C:\Program Files (x86)\Intel\iCLS Client\;
C:\Program Files\Intel\iCLS Client\;
C:\WINDOWS\system32;C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\Program Files\TortoiseSVN\bin;
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files (x86)\WinMerge;
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;
c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;
c:\Program Files\Microsoft SQL Server\110\DTS\Binn\;
c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;
c:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;
c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;
C:\Program Files\Microsoft\Web Platform Installer\;
C:\Program Files (x86)\Kaspersky Lab\Kaspersky Security Center\Share\12.1_RU4_CleanWipe\;
C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;
C:\Program Files (x86)\Skype\Phone\;
E:\JAVA\gradle-2.10-all\gradle-2.10\bin;
C:\Program Files\Java\jdk1.8.0_60\bin;
E:\JAVA\apache-tomcat-8.0.30-windows-i64\apache-tomcat-8.0.30\bin;
C:\Program Files\nodejs\;
C:\Users\deependra.singh\AppData\Local\Programs\Python\Python35-32\Scripts\;
C:\Users\deependra.singh\AppData\Local\Programs\Python\Python35-32\;
C:\Program Files (x86)\Microsoft VS Code\bin;
E:\JAVA\gradle-2.10-all\gradle-2.10\bin\C:\Program Files\Java\jdk1.8.0_60\bin;
E:\JAVA\apache-tomcat-8.0.30-windows-i64\apache-tomcat-8.0.30\bin;
C:\Users\deependra.singh\AppData\Roaming\npm;.;

8 verbose lifecycle readium-js-viewer@0.22.1~prepare: CWD: D:\Projects\HMH\ChromeBook\GIT-MASTER\readium-js-viewer
9 silly lifecycle readium-js-viewer@0.22.1~prepare: Args: [ '/d /s /c',
9 silly lifecycle   'npm run prepare:submodule && npm run prepare:dependencies' ]
10 silly lifecycle readium-js-viewer@0.22.1~prepare: Returned: code: 1  signal: null
11 info lifecycle readium-js-viewer@0.22.1~prepare: Failed to exec prepare script
12 verbose stack Error: readium-js-viewer@0.22.1 prepare: `npm run prepare:submodule && npm run prepare:dependencies`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at EventEmitter.emit (events.js:172:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at ChildProcess.emit (events.js:172:7)
12 verbose stack     at maybeClose (internal/child_process.js:821:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13 verbose pkgid readium-js-viewer@0.22.1
14 verbose cwd D:\Projects\HMH\ChromeBook\GIT-MASTER\readium-js-viewer
15 error Windows_NT 6.3.9600
16 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare"
17 error node v5.4.0
18 error npm  v3.3.12
19 error code ELIFECYCLE
20 error readium-js-viewer@0.22.1 prepare: `npm run prepare:submodule && npm run prepare:dependencies`
20 error Exit status 1
21 error Failed at the readium-js-viewer@0.22.1 prepare script 'npm run prepare:submodule && npm run prepare:dependencies'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the readium-js-viewer package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run prepare:submodule && npm run prepare:dependencies
21 error You can get their info via:
21 error     npm owner ls readium-js-viewer
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

Please let me know if I am doing something wrong.
Please let me know if we have some forum to submit this kind of queries. 

Thanks

**Comment by danielweck** [comment]
Hello, and thank you for your feedback. This is the right place to post feature requests, bug reports, etc. :)

First of all, note that NODE 5 may be marked as "stable" on their official website, but the installer ships with NPM 3 which is clearly labelled as "beta" somewhere else. See: https://github.com/readium/readium-js-viewer/issues/453

So, I would **strongly suggest** using the latest version of NodeJS v4 instead.

Also, note that switching from 4 to 5 (or vice-versa) requires deleting the `node_modules` folders of Readium repositories / submodules, as well as Node's internal folder! (prior to installing the new version) Again, see the discussion thread in issue #453 

Let me know how it goes!
Cheers, Daniel

**Comment by DeependraKhangarot** [comment]
Thanks a ton Daniel :-)

It worked with NodeJS v4.
