### ISSUE TITLE
Good(we made), but sometimes, so slow. can I check this?

### ISSUE THREAD

**Issue by jaysbae** [readium/readium-js-viewer#457]
I (company) use this for this test site,

http://mobile.nextpub.net/dev/reader_01.html?

I think it is really good and nice viewer.
But sometimes, this is so slow and looks like stopped.

Somebody please look that page and help.

Thank you.

(My company is a member of Readium)

**Comment by danielweck** [comment]
Hello, thank you for your feedback.

How does your Readium cloud-reader deployment compares to these test servers (in terms of performance):
Firebase:
https://readium.firebaseapp.com
Surge:
https://readium.surge.sh/?epubs=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Fepub_library.opds&
?

**Comment by danielweck** [comment]
I see that you are using the latest version of Readium from the develop branch (which is fine):
http://mobile.nextpub.net/dev/reader_01.html?epub=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2FepubReadingSystem

...however you are not deploying the fast optimized distribution package of Readium cloud-reader (you uploaded the raw source code, using the "dev" folder). Please make sure to use either:
1) `Readium_cloud-reader.zip` from https://github.com/readium/readium-js-viewer/releases
or alternatively:
2) compile the Readium cloud-reader app yourself, by invoking the `npm run dist+sourcemap` command (step-by-step instructions in the README https://github.com/readium/readium-js-viewer/blob/develop/README.md )

I am closing this issue now, but please feel free to continue the discussion if needed. Let us know if you succeed in building the app yourself :)

**Comment by jaysbae** [comment]
Thank you. I will try that!

2016-01-13 15:28 GMT+09:00 Daniel Weck <notifications@github.com>:

**Comment by danielweck** [comment]
For your information, also note that you can test your ebook library using Readium's own deployed app:

EPUB library:

https://readium.firebaseapp.com/?epubs=https%3A%2F%2Fcrossorigin.me%2Fhttp%3A%2F%2Fmobile.nextpub.net%2Fepub_content%2Fepub_library.json&

Direct EPUB link:

https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcrossorigin.me%2Fhttp%3A%2F%2Fmobile.nextpub.net%2Fepub_content%2Fgachi&

(I am using https://crossorigin.me to provide HTTP CORS headers and secure HTTPS connexion)

**Comment by jaysbae** [comment]
Thank you.
But font files are embedded at these epubs. so I moved that to server path
for more speed :)

And I am checking which is better.

I will try.

And.. I wish popup footnote will be possible~ :)

Thank you. this web based ePub viewer is reall fantastic!!!!


2016-01-13 15:37 GMT+09:00 Daniel Weck <notifications@github.com>:

**Comment by danielweck** [comment]
Yes, a standard popup footnote mechanism would be nice (it would have to work in fixed-layout EPUBs, as well as paginated and scrolled reflowable documents)
Are you volunteering to contribute this feature? ;)

We are glad to hear that you are enjoying using Readium to view your EPUBs online. Thank you for your support.

**Comment by jaysbae** [comment]
Sure, I gave(supply) my ePubs (included MathML/MathJax and more enhanced
included) to Garth Conboy at last year. this mail account is personal.
My official  account is jaysbae@diypia.com  and CEO/CTO

If you want to more test for better viewer. I will do that ;)

Thank you.

2016-01-13 15:51 GMT+09:00 Daniel Weck <notifications@github.com>:

**Comment by jaysbae** [comment]
Hello,
This site is more fast and stable than yesterday.

http://m.nextpub.net/dev/reader_01.html?

Thank you for your advice

Best,
Jays Bae

2016-01-13 15:58 GMT+09:00 Jays Bae <jaysbae@gmail.com>:

**Comment by danielweck** [comment]
Hello @jaysbae when I open http://m.nextpub.net/dev/reader_01.html and check the web console, I still see the non-optimized raw source code (file tree). For example: http://m.nextpub.net/readium-js/readium-shared-js/js/globalsSetup.js
Instead, you should invoke the `npm run dist+sourcemap` build command, which generates a single minified package in the `./dist/cloud-reader/` folder. Or, you can dowload a ready-made distribution package `Readium_cloud-reader.zip` at https://github.com/readium/readium-js-viewer/releases

**Comment by jaysbae** [comment]
I really appreciate to you.

I just overwrite that you told me (a ready-made distribution package
Readium_cloud-reader.zip) to my server.

How can I check that is ok?

And still I can't see at the IE / Windows7 but almost all is ok.

Can I fix this? and I wonder when I could see the popup footnote function ;)

Thank you.


2016-01-18 21:21 GMT+09:00 Daniel Weck <notifications@github.com>:

**Comment by danielweck** [comment]
@jaysbae do you have a public HTTP URL where you deployed the "compiled" version of the Readium web-reader app? Right now, I open http://m.nextpub.net/dev/reader_01.html and I see these error messages in the browser console: "Failed to load resource: the server responded with a status of 404 (Not Found)" http://m.nextpub.net/readium-js/.git/HEAD (`.git/HEAD` files query clearly indicate that this is the raw source code, not the optimized distributable package of Readium) Another hint is the console logging at the top: The scripts like http://m.nextpub.net/readium-js/readium-shared-js/readium-cfi-js/js/cfi_API.js should not be available in their un-optimised, unpacked form. They should all be bundled as a single minified JS file.
Maybe http://m.nextpub.net/dev/reader_01.html is the old URL? Should I be looking at a different link?

**Comment by jaysbae** [comment]
I saw the messages too. but I thought that was not so serious...:)

First time I tested that in my local server (not connected to out). -
Ubuntu 14.04
course, I met many errors at first time, but after installing related
packages.
All resources are completely compiled (I thought).

So I did that to my service server that has public URL that you know.
(Ubuntu 15~)
Please check me up that I did correctly.

My processes are,

1. I download [readium-js-viewer-master] to my server.

2. There was empty [readium-js] directory. so I download
[readium-js-master] and complie(?), and copy there(follow the guide -
https://github.com/readium/readium-js)
and there (readium-js), [readium-shared-js] was empty, and so I download
that and did like before (follow the
https://github.com/readium/readium-shared-js)... [readium-cfi-js] was too..
It looks like (I thought..) no problem. but result was as you know.

I don't know the whole process correctly.
How can I find all manual(?) for readium-js-viewer included depends,
related packages...?

I hope using that successfully and wish to add slider.. popup footnote.. :)

Thank you for your help.


2016-01-19 20:02 GMT+09:00 Daniel Weck <notifications@github.com>:

**Comment by danielweck** [comment]
Please do not upload readium-js-viewer raw source code to your server.
You must first build / compile an optimized distributable application package (or download the ready-made zip from the 0.23 alpha release).
To build yourself, get the raw source code from the GitHub repository on your local machine, follow the instructions in the README: https://github.com/readium/readium-js-viewer/blob/develop/README.md
You may use the develop branch to experiment and benefit from the latest bug fixes. Otherwise you may use the master branch which is currently at 0.22
