### ISSUE TITLE
RJS_UGLY=false; build fails when attempting to copy .map files

### ISSUE THREAD

**Issue by kimtuck** [readium/readium-js-viewer#459]
Following the instructions on the home page, I cloned the master branch of readium and proceeded to build.  A normal (compressed) build works fine; but when I did this:

export RJS_UGLY="false"; npm run build > build.out 2>&1

it fails to build, because the scripts attempt to copy .map files that don't exist.  (To get this to work, I ended up patching the 'cpy' module to ignore ENOENT errors).

But it would be nice if the build would work as documented.

**Comment by danielweck** [comment]
Fixed. Thank you for reporting this.

The RequireJS multiple bundle optimizer wasn't generating sourcemaps for non-uglified single-file scripts (zip worker, deflate and inflate). Did not affect `readium-shared-js` and `readium-cfi-js`, only `readium-js` and `readium-js-viewer`.

Fix tested in Bash, MS-DOS, PowerShell, Cygwin, etc.

`readium-js`
https://github.com/readium/readium-js/commit/ef585d3d2caa4e5f4a12bead09d66ae66cd958d6

`readium-js-viewer`
https://github.com/readium/readium-js-viewer/commit/8957e4cb5c68bc59fd7c79d8bff3cf2f270815d2
