### ISSUE TITLE
CFI returns with NaN when calling getFirstVisibleCfi() in some books

### ISSUE THREAD

**Issue by jdempcy** [readium/readium-js-viewer#460]
Steps to repro:

  1. Open The Iliad
  2. Go to the next page 11 times (For me this is 4 screens from the beginning of the preface.)
  3. Call ReadiumSDK.reader.getFirstVisibleCfi()
  4. For me, this returns  "/NaN/2/2[section_77912]/4/NaN,/3:58,/3:59”

The previous and next page return the correct CFIs.

Here is the book:

[5724466092965888.epub.zip](https://github.com/readium/readium-js-viewer/files/92656/5724466092965888.epub.zip)

**Comment by JCCR** [comment]
@jdempcy 

Thanks, managed to reproduce it on Chrome.

**Comment by JCCR** [comment]
Interesting this looks to be a bug with the CFI library.

**Comment by JCCR** [comment]
Fixed in:

https://github.com/readium/readium-shared-js/commit/c94516915ea9033ccb87f5e2c7b47708fa3cbf70
