### ISSUE TITLE
Screen reader issues with certain controls

### ISSUE THREAD

**Issue by prashantverma2014** [readium/readium-js-viewer#488]
Tested with Jaws 17 and NVDA 2015.4. 
Pressing TAB key or arrow keys inside the settings or add books dialog does not speak anything.noWhen the Add Books or Settings button is pressed, the user does not get any speech feedback while navigating in these windows.

**Comment by becka11y** [comment]
What browser and version of Windows are you using?

**Comment by prashantverma2014** [comment]
Tested on two systems. 
1. Windows 8.1 with Chrome  48.
Tested with Jaws v17 and NVDA 15.4

2. The second system has Windows 10 with Chrome 48. Tested with NVDA 15.4. 

In both cases i installed Readium from the Chrome store - https://chrome.google.com/webstore/detail/readium/fepbnnnkkadjhjahcafoaglimekefifl

**Comment by becka11y** [comment]
I suspect this is a chrome issue but will so some testing.  Chrome still has some issues with screen readers.

**Comment by danielweck** [comment]
Fixed by https://github.com/readium/readium-js-viewer/pull/489
