### ISSUE TITLE
MathJax popup menu commands: remove to avoid interference with pagination layout

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#490]

**Comment by danielweck** [comment]
See: http://docs.mathjax.org/en/latest/options/hub.html?highlight=showmathmenu

**Comment by danielweck** [comment]
Fixed: 
https://github.com/readium/readium-shared-js/commit/26988df4ef4f7a615b08c56ec328a2b53d53cc8a
https://github.com/readium/readium-js/commit/9e15c7d275f74af588d1378de7108e03260d2f23

**Comment by pkra** [comment]
We're happy to help if you want to build some of its features (show source/annotations) into Readium directly.

**Comment by danielweck** [comment]
Thanks Peter.
