### ISSUE TITLE
mediaOverlays Issues

### ISSUE THREAD

**Issue by benson-jala** [readium/readium-js-viewer#495]
I have a fixed layout read along epub.
epub is loading fine.

auto play is not working until i tap on screen may be because of(mediaOverlaysEnableClick:true)
i made it false, still i have to tap on screen to play.

swipe to next spine works, but their is an option called "mediaOverlaysAutomaticPageTurn"
when i make it true autopageturn is not working.

Is their any settings i have to override?

**Comment by danielweck** [comment]
EPUB3 audio Media Overlays do not start automatically. Playback requires at least an initial user action, such as (1) clicking or touching the text, or (2) invoking the "play" command (in Readium Chrome extension / cloud reader app, there is a play/pause button, and a keyboard shortcut 'm').

'mediaOverlaysEnableClick' is an option that's turned on by default: when off, clicking or touching the text has no effect.

'mediaOverlaysAutomaticPageTurn' is an option that's on by default: when off, the audio pauses at the end of a fixed-layout page, requiring the user to explicitly resume playback. Note that this currently does not work with reflowable documents.

I hope this helps. Feel free to comment further if there are issues.
