### ISSUE TITLE
Readium Cloud Viewer Broken

### ISSUE THREAD

**Issue by dlo83** [readium/readium-js-viewer#496]
**Please use a short, but meaningful title.**

*Make sure to fill-in as much information as possible in the sections below:*

### This issue is a:

* Bug report

### Expected behaviour

Visiting the readium cloud reader(s) (previously hosted at http://readium.divshot.io/ or http://development.readium.divshot.io/) should load a page

### Observed behaviour

Instead, neither page is found.

### Steps to reproduce

1. Click on the links in the docs
2. Pages will not load

### Product

* Readium cloud reader app

### Web browser

* Chrome

### Operating system

* OSX

### Additional information

...

**Comment by danielweck** [comment]
Thanks for your feedback.
The DivShot.io service closed some time ago. Readium now deploys the cloud reader app at https://readium.firebaseapp.com (latest build from the develop branch), and at http://readium-master.surge.sh (latest build from the master branch).
We updated the README to reflect those changes.
https://github.com/readium/readium-js-viewer/blob/develop/README.md
Sorry for the confusion!
