### ISSUE TITLE
ISSUE and PULL_REQUEST template + CONTRIBUTING.md needs "porting" to other repositories

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#503]
See:
https://github.com/readium/readium-js-viewer/commit/f031308291ffeb3bf67a9f930898a3e23b5acb59

=> we need to add these to all the other Readium GitHub repositories.

**Comment by rkwright** [comment]
Done. WIll be integrated to master at end of 0.23 at which point they will be active.  Currently in develop, but the templates have to be in master.
