### ISSUE TITLE
readium js viewer npm log error

### ISSUE THREAD

**Issue by thangaraj80** [readium/readium-js-viewer#509]
**I try to configure readium-js-viewer, iam  getting the following errors**

15 error Windows_NT 6.1.7601
16 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare"
17 error node v5.8.0
18 error npm  v3.7.3
19 error code ELIFECYCLE
20 error readium-js-viewer@0.23.0-alpha prepare: `npm run prepare:submodule && npm run prepare:local`
20 error Exit status 1
21 error Failed at the readium-js-viewer@0.23.0-alpha prepare script 'npm run prepare:submodule && npm run prepare:local'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the readium-js-viewer package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run prepare:submodule && npm run prepare:local
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs readium-js-viewer
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls readium-js-viewer
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

...

**Comment by danielweck** [comment]
Please use Node v4 and NPM v2
https://nodejs.org

See the README: https://github.com/readium/readium-js-viewer/blob/develop/README.md#prerequisites

Also see existing issue: https://github.com/readium/readium-js-viewer/issues/453#issuecomment-169410695

**Comment by thangaraj80** [comment]
Thanks daniel. will check and update you.

**Comment by thangaraj80** [comment]
**console.log shows the following error**

Default URL of ebooks library: ../epub_content/epub_library.opds
Require...nfig.js (line 40)
RequireJS ... cfi_API
cfi_API.js (line 123)
**"NetworkError: 404 Not Found - http://127.0.0.1:8080/readium-js/readium-shared-js/node_modules/eventemitter3/_rjs/index.js"**
index.js
Error: Script error for "eventEmitter"
http://requirejs.org/docs/errors.html#scripterror
	

var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);

	
require.js (line 165, col 17)
RequireJS ... cfi_errors
cfi_run...rors.js (line 97)
RequireJS ... cfi_interpreter
cfi_int...eter.js (line 414)
RequireJS ... cfi_generator
cfi_generator.js (line 481)
RequireJS ... cfi_instructions
cfi_ins...ions.js (line 367)
#######################################

**Comment by danielweck** [comment]
Did the `npm run prepare` command complete successfully? It is a prerequisite step.

**Comment by thangaraj80** [comment]
yes Did Daniel. 
But there is no **_rjs folder** inside the following directory

> \readium-shared-js\node_modules\eventemitter3

**Comment by thangaraj80** [comment]
`npm run prepare` gives following error

11 error Windows_NT 6.1.7601
12 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare"
13 error node v4.4.0
14 error npm  v2.14.20
15 error code ELIFECYCLE
16 error readium-js-viewer@0.23.0-alpha prepare: `npm run prepare:submodule && npm run prepare:local`
16 error Exit status 1
17 error Failed at the readium-js-viewer@0.23.0-alpha prepare script 'npm run prepare:submodule && npm run prepare:local'.
17 error This is most likely a problem with the readium-js-viewer package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm run prepare:submodule && npm run prepare:local
17 error You can get information on how to open an issue for this project with:
17 error     npm bugs readium-js-viewer
17 error Or if that isn't available, you can get their info via:
17 error
17 error     npm owner ls readium-js-viewer
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]

**Comment by danielweck** [comment]
When you switch from one major version of NPM to another (i.e. v4 - v5), make sure to delete the `node_modules` folders inside each ReadiumJS repository:
`readium-js-viewer/node_modules/`
`readium-js-viewer/readium-js/node_modules/`
`readium-js-viewer/readium-js/readium-shared-js/node_modules/`
`readium-js-viewer/readium-js/readium-shared-js/readium-cfi-js/node_modules/`

**Comment by danielweck** [comment]
..then re-run `npm run prepare`

**Comment by thangaraj80** [comment]
I did still getting errors


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prepare' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose run-script [ 'prepare' ]
5 info prepare readium-js-viewer@0.23.0-alpha
6 verbose unsafe-perm in lifecycle true
7 info readium-js-viewer@0.23.0-alpha Failed to exec prepare script
8 verbose stack Error: readium-js-viewer@0.23.0-alpha prepare: `npm run prepare:submodule && npm run prepare:local`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at EventEmitter.emit (events.js:172:7)
8 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at ChildProcess.emit (events.js:172:7)
8 verbose stack     at maybeClose (internal/child_process.js:827:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
9 verbose pkgid readium-js-viewer@0.23.0-alpha
10 verbose cwd C:\readium-js-viewer
11 error Windows_NT 6.1.7601
12 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare"
13 error node v4.4.0
14 error npm  v2.14.20
15 error code ELIFECYCLE
16 error readium-js-viewer@0.23.0-alpha prepare: `npm run prepare:submodule && npm run prepare:local`
16 error Exit status 1
17 error Failed at the readium-js-viewer@0.23.0-alpha prepare script 'npm run prepare:submodule && npm run prepare:local'.
17 error This is most likely a problem with the readium-js-viewer package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm run prepare:submodule && npm run prepare:local
17 error You can get information on how to open an issue for this project with:
17 error     npm bugs readium-js-viewer
17 error Or if that isn't available, you can get their info via:
17 error
17 error     npm owner ls readium-js-viewer
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]

**Comment by thangaraj80** [comment]
"NetworkError: 404 Not Found - http://127.0.0.1:8080/readium-js/readium-shared-js/node_modules/eventemitter3/_rjs/index.js"
index.js
Error: Script error for "eventEmitter"
http://requirejs.org/docs/errors.html#scripterror
	

var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);

	
require.js (line 165, col 17)
RequireJS ... cfi_interpreter
cfi_int...eter.js (line 414)
RequireJS ... cfi_errors
cfi_run...rors.js (line 97)
RequireJS ... cfi_generator
cfi_generator.js (line 481)
RequireJS ... cfi_instructions
cfi_ins...ions.js (line 367)
#######################################

**Comment by danielweck** [comment]
Okay. Can you please post the `npm.log` file (I can't remember the exact name, but it should be in your `readium-js-viewer/` folder, or `readium-js-viewer/readium-js/readium-shared-js/` subfolder)
Sorry for the inconvenience (PS: I am not able to reproduce this bug)
Thanks!

**Comment by thangaraj80** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prepare' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose run-script [ 'prepare' ]
5 info prepare readium-js-viewer@0.23.0-alpha
6 verbose unsafe-perm in lifecycle true
7 info readium-js-viewer@0.23.0-alpha Failed to exec prepare script
8 verbose stack Error: readium-js-viewer@0.23.0-alpha prepare: `npm run prepare:submodule && npm run prepare:local`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at EventEmitter.emit (events.js:172:7)
8 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at ChildProcess.emit (events.js:172:7)
8 verbose stack     at maybeClose (internal/child_process.js:827:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
9 verbose pkgid readium-js-viewer@0.23.0-alpha
10 verbose cwd C:\readium-js-viewer
11 error Windows_NT 6.1.7601
12 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare"
13 error node v4.4.0
14 error npm  v2.14.20
15 error code ELIFECYCLE
16 error readium-js-viewer@0.23.0-alpha prepare: `npm run prepare:submodule && npm run prepare:local`
16 error Exit status 1
17 error Failed at the readium-js-viewer@0.23.0-alpha prepare script 'npm run prepare:submodule && npm run prepare:local'.
17 error This is most likely a problem with the readium-js-viewer package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm run prepare:submodule && npm run prepare:local
17 error You can get information on how to open an issue for this project with:
17 error     npm bugs readium-js-viewer
17 error Or if that isn't available, you can get their info via:
17 error
17 error     npm owner ls readium-js-viewer
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]

**Comment by danielweck** [comment]
Here's a thought:
1) uninstall NodeJS
2) Make sure the install directory is empty, especially: C:\Program Files\nodejs\node_modules\
3) reinstall NodeJS
4) invoke "npm run prepare" again

**Comment by thangaraj80** [comment]
I did Daniel. Not able to view epub now

**Comment by danielweck** [comment]
Okay, so the next step is to invoke the build tasks manually to see which one fails exactly. `npm run prepare` is just a utility "wrapper" for vanilla `npm install`, `npm update`, etc.
See:
https://github.com/readium/readium-shared-js/blob/develop/package.cson#L189
So, let me know how this goes (again, please upload / copy the NPM log files):
1) in `readium-shared-js`, make sure to delete the `node_modules/eventemitter3/` folder
2) invoke `npm install`
3) check that the `node_modules/eventemitter3/` folder exists
4) `node readium-cfi-js/node_modules/requirejs/bin/r.js -convert node_modules/eventemitter3/ node_modules/eventemitter3/_rjs/`
5) check that the `node_modules/eventemitter3/_rjs/` folder exists

**Comment by thangaraj80** [comment]
Npm install not creating _rjs folder inside eventemitter3. I manually
created  folder _rjs  and placed index.js inside that folder.

Now its showing the index of e pup files. Not able to view the epub

**Comment by danielweck** [comment]
The _rjs folder is created by step 4, not 'npm install'

**Comment by thangaraj80** [comment]
Thanks. Daniel. I will try and get back to  you.

**Comment by thangaraj80** [comment]
Thanks Daniel. Its working fine now. Able to view the Epub. Thanks a Lot. I try to upload my own Epub. Will Update you

**Comment by danielweck** [comment]
@thangaraj80 any idea why it wasn't working in the first place? What was the problem?

**Comment by thangaraj80** [comment]
Initially NPM not created _rjs folder inside **eventemitter3**

Later I have followed your step. Its working now.

So, let me know how this goes (again, please upload / copy the NPM log files):
1) in readium-shared-js, make sure to delete the node_modules/eventemitter3/ folder
2) invoke npm install
3) check that the node_modules/eventemitter3/ folder exists
4) node readium-cfi-js/node_modules/requirejs/bin/r.js -convert node_modules/eventemitter3/ node_modules/eventemitter3/_rjs/
5) check that the node_modules/eventemitter3/_rjs/ folder exists

**Comment by danielweck** [comment]
Okay, but I just wonder why `npm run prepare` did not successfully perform the tasks that you invoked manually. They are exactly the same steps. Anyway, good to hear you can now focus on more interesting / productive problem-solving :)
