### ISSUE TITLE
$iframe is not defined in  ReadiumSDK.Events

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#521]
In old version i was able to manipulate listener over the epub file like disallowing right click over the book by using this

`

$(document).ready(function () {

ReadiumSDK.on(ReadiumSDK.Events.READER_INITIALIZED, function()
{
ReadiumSDK.reader.on(ReadiumSDK.Events.CONTENT_DOCUMENT_LOADED, function($iframe,s) 
{

var doc = $iframe[0].contentWindow.document;

//////////////////
// REPLACE THIS WITH DESIRED LOGIC
doc.addEventListener("contextmenu", function(e)
{
e.preventDefault();
}, false);
//////////////////

});         
}, this);
});

`

but now with the new version adding this script will stop readium from working showing an error 

3405Uncaught ReferenceError: $iframe is not defined

What should i use instead of this

**Comment by danielweck** [comment]
This works just fine in the cloud reader app build from the develop branch:

https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js

readium.reader.on(ReadiumSDK.Events.CONTENT_DOCUMENT_LOADED, function ($iframe, spineItem)

https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3

Could you please explain which version you are using?

**Comment by mahag** [comment]
I am trying to add this code to index.html inside cloud-reader-lite folder from dist folder that i have cloned from github 2 days ago . It is Readium 0.22.2

**Comment by mahag** [comment]
This is what am adding to index.html page in cloud-reader-lite folder
` < script type="text/javascript">
        $(document).ready(function () {
           
            ReadiumSDK.on(ReadiumSDK.Events.READER_INITIALIZED, function () {
                ReadiumSDK.reader.on(ReadiumSDK.Events.CONTENT_DOCUMENT_LOADED, function ($iframe, s) {

                    var doc = $iframe[0].contentWindow.document;
                    doc.addEventListener("touchstart", function (e) {
                        e.preventDefault();
                    }, false);
                    doc.addEventListener("onkeydown", function (e) {
                        e.preventDefault();
                        e.returnValue = false;
                    }, false);
                    doc.addEventListener("keydown", function (e) {
                        e.preventDefault();
                    }, false);

                    doc.addEventListener("keyup", function (e) {

                        if (e.keyCode == 44) {
                            $("body").hide();
                        }
                        e.preventDefault();
                    }, false);
                    doc.addEventListener("contextmenu", function (e) {
                        e.preventDefault();
                    }, false);
                });
            }, this);
        });


</script>`

When running index.html with epub namw in url page is not displaying anything just the dark blue header. From developers tools it is showing this error

> index.html?epub=epub_content/1:74 Uncaught ReferenceError: ReadiumSDK is not defined

and referring tot his line in script
` ReadiumSDK.on(ReadiumSDK.Events.READER_INITIALIZED, function () {`

This used to work correctly before installing Readium 0.22.2 on older readium version.
What should i do to make it work? I need to disable right click over text in book and some other actions in order to protect book content

**Comment by danielweck** [comment]
Could you please try renaming ReadiumSDK to Globals.
Also, the ReadiumSDK global variable is set via the RequireJS-imported Globals module, see for example:
https://github.com/readium/readium-js/blob/develop/dev/index.js

**Comment by mahag** [comment]
Thank you it worked

**Comment by danielweck** [comment]
To be precise, the ReadiumSDK global var is set via:
https://github.com/readium/readium-shared-js/blob/develop/js/globalsSetup.js
(it references the same object as window.Globals)

**Comment by hajarghaem** [comment]
Hello @mahag,
I have the same problem. I changed ReadiumSDK to Globals. It did not work. 
I am going to disable copy-paste feature from Cloud-reader-Lite using the following code in dist/cloud-reader-lite/index.html:
<script type="text/javascript">

			$(document).ready(function () {

				ReadiumSDK.on(ReadiumSDK.Events.READER_INITIALIZED, function()
				{
					ReadiumSDK.reader.on(ReadiumSDK.Events.CONTENT_DOCUMENT_LOADED, function($iframe,s) 
					{

						var doc = $iframe[0].contentWindow.document;

						doc.addEventListener("contextmenu", function(e)
						{
						e.preventDefault();
						}, false);
						doc.addEventListener("keydown", function(e)
						{
						e.preventDefault();
						}, false);

				});         
			}, this);
			});

		</script>

Could you please help me with your solution?
Thanks in advance,

**Comment by danielweck** [comment]
If ReadiumSDK or Globals are not available in your app, then you should try to figure out why that is. Do you use a standard build of readium-shared-js , or the top-level readium-js-viewer?

**Comment by hajarghaem** [comment]
It works with my cloud reader and just does not work in cloud reader lite. I use both. for my local test I use  https://github.com/readium/readium-js-viewer. And I also have build it in my machine.

**Comment by danielweck** [comment]
Okay so this problem seems limited to the "lite" version of the cloud reader. Strange. We need to investigate.

**Comment by hajarghaem** [comment]
I check one more time in Chrome and Firefox: 
- it works on Firefox: CloudReader

- it does not work on Firefox: CloudReaderLite

- it does not work on Chrome: CloudReader

- it does not work on Chrome: CloudReaderLite

I attached screenshots of errors:

![firefoxcloudreaderlite](https://cloud.githubusercontent.com/assets/5468274/19148580/a84cbbd2-8bbd-11e6-9958-f21ce382d125.JPG)

![chromecloudreader](https://cloud.githubusercontent.com/assets/5468274/19148584/ab595ee8-8bbd-11e6-873a-1b8271371fbf.JPG)

![chromecloudreaderlite](https://cloud.githubusercontent.com/assets/5468274/19148586/ad556db8-8bbd-11e6-84b2-5d66037038f2.JPG)

**Comment by hajarghaem** [comment]
@danielweck 
Is there other place (now I used it int he head of dist/cloud-reader-lite/index.html, and got that error) or way to add following my code fro disable copy paste in the Cloud-reader-Lite? 
<script type="text/javascript">			
		$(document).ready(function () {
				ReadiumSDK.on(ReadiumSDK.Events.READER_INITIALIZED, function()
				{
					ReadiumSDK.reader.on(ReadiumSDK.Events.CONTENT_DOCUMENT_LOADED, function($iframe,s) 
					{

						var doc = $iframe[0].contentWindow.document;

						doc.addEventListener("contextmenu", function(e)
						{
						e.preventDefault();
						}, false);
						doc.addEventListener("keydown", function(e)
						{
						e.preventDefault();
						}, false);
				});         
			}, this);
			});
</script>


Thanks in advance

**Comment by hajarghaem** [comment]
I solved it by directly adding my codes into "readium-js-viewer_all_LITE.js", where you can find "S.reader.on(ReadiumSDK.Events.CONTENT_DOCUMENT_LOADED, function($iframe,s) {". Then you do not need to add your code in Dist/Cloud-reader-lite/index.html.

**Comment by danielweck** [comment]
I would strongly advice against hacking code into already-compiled (RequireJS-optimized) JavaScript bundles, as this invalidates the source maps. The correct way to do this is to implement changes in the raw source code, and follow the simple steps to build your own version of the application (clone the Git repository / submodules, change source code, "npm run prepare", "npm run dist+sourcemap").

**Comment by danielweck** [comment]
PS: I will also get back to you with sample code for `index.html`, to save you having to compile changes into the existing RequireJS bundle(s).

**Comment by danielweck** [comment]
@hajarghaem (and others) could you please update your code and add to the `head` of your `index.html` markup (as you can see, this Javascript code snippet demonstrates how to intercept "click" events on the loaded EPUB spine item documents):

```html
<script type="text/javascript">

require(["readium_shared_js/globalsSetup", "readium_shared_js/globals"], function (GlobalsSetup, Globals) {
    require(['jquery'], function ($) {
        
        $(document).ready(function () {
            console.log(ReadiumSDK.reader);
        });

        ReadiumSDK.reader.on(ReadiumSDK.Events.CONTENT_DOCUMENT_LOADED, function ($iframe, spineItem) {
            Globals.logEvent("CONTENT_DOCUMENT_LOADED", "ON", "index.html");

             //$iframe.contents()
             
            var doc = $iframe[0].contentDocument || $iframe[0].contentWindow.document;
            $('body', doc).on("click", function(){
                alert("CLICK");
            });
        });
    });
});

</script>
```

**Comment by hajarghaem** [comment]
@danielweck thank you very much.
