### ISSUE TITLE
Setting page-progression-direction="rtl" messes the display and paging

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#523]
Almost all of my files have direction left to right, so when opening them via Readium i noticed that display isn't the same as when direction was set to default right to left and even going through pages get messed up and some pages are getting skipped.

So I tried over the epub file you provide in epub_content "moby_dick" and i altered package.opf file and replaced `<spine>` by `<spine  page-progression-direction="rtl">`
I got the same results , incorrect display and some pages are not displayed.
Can you please regenerate and help me fix this issue?

**Comment by danielweck** [comment]
Hello, is that an issue with the latest ReadiumJS code from the develop branch? I assume you are using the cloud reader / Chrome extension (not a native ReadiumSDK app).

**Comment by mahag** [comment]
Yes i am using folder cloud-reader-lite that i have cloned since i need to add readium to my existing website

**Comment by danielweck** [comment]
Okay. As long as you use the app build generated in the folder readium-js-viewer/dist/cloud-reader[-lite], then we can debug this issue. I will take a look, but probably not until next week.

**Comment by mahag** [comment]
Ok thank you 
Waiting your reply

**Comment by mahag** [comment]
I did run my tests over several browsers and operating systems.
Google chrome fails on most of Os :windows 7 ,windows 8,windows 10 ,ios(google chrome app in iphone/ipad)
IE 11and edge worked correctly under windows
Safari in IOS worked too
So this might be related to something in google chrome

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/readium-shared-js/issues/282
