### ISSUE TITLE
How can I host Readium over some website?

### ISSUE THREAD

**Issue by himanshukimni2000** [readium/readium-js-viewer#528]
Hello Everyone,

First of all I would like to thank Daniel and all the contributors to develop such a nice application.

I have been trying to upload the SDK over some other domain but it is not working. Can anyone guide me how can I host this.

I am able to run this successfully from "npm run http/http2" commands but unfortunately I am not aware how this can will work on a custom domain.

Look forward to hear from you guys.

Thanks in advance for all the help which I will be getting from you and your team.

Thanks, Himanshu

**Comment by danielweck** [comment]
hello, did you read the "distribution" and "cloud reader deployment" sections of the README?

https://github.com/readium/readium-js-viewer/blob/develop/README.md#distribution

HTTP CORS support is working fine at Readium's Surge.sh and Firebase.io test URLs, where the cloud reader is deployed by default.
http://readium.surge.sh/?epubs=http%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Fepub_library.opds
https://readium.firebaseapp.com

You can just upload the "dist" build to your own web server / domain. No special configuration required in Readium.

**Comment by himanshukimni2000** [comment]
Thanks Daniel!

While running "npm run dist" command from "Git Bash" I am getting errors due to which I am unable to generate the "dist" build. I am attaching a error log for your reference. Please help.


[errro.txt](https://github.com/readium/readium-js-viewer/files/281508/errro.txt)

**Comment by danielweck** [comment]
Please make sure to checkout the develop branch in all submodule repositories, which must be initialised correctly as per the READMe instructions.
I am personally using GitBash on Windows 10 and I have no problems building.
Let me know how it goes.

**Comment by danielweck** [comment]
Follow up: this was fixed in the develop branch, not yet merged / tagged / released into the master branch:

https://github.com/readium/readium-cfi-js/commit/bb13853a2f359d446d8ffb571ea90bc22087e6ae

**Comment by himanshukimni2000** [comment]
Thanks again! Finally I have generated the "dist" build without any error.

Now I will carefully go through with "distribution" and "cloud reader deployment" sections and try to test this on some server.

Will get back to you in case if any issue. Thanks again Daniel!

**Comment by himanshukimni2000** [comment]
Marking this close as finally I am able to integrate it to some server. Thank you so much Daniel!
