### ISSUE TITLE
How can i highlight epub content text using "rangy" in "readium-shared-js" ?

### ISSUE THREAD

**Issue by ccnucheng** [readium/readium-js-viewer#537]
How can i highlight epub content text using "rangy" in "readium-shared-js" ? I can't highlight the text in iframe,but outside the iframe,i can do it . so anyone help me?

**Comment by danielweck** [comment]
Please ignore the Rangy lib. Have a look at `plugins/highlights` instead:
https://github.com/readium/readium-shared-js/tree/develop/plugins/highlights
This uses a totally different text "selection" method (i.e. translucent div overlays) and this is an active feature in the cloud reader build, which you can try here: https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3 (for example)
