### ISSUE TITLE
Add to Library immediately loads file when selected

### ISSUE THREAD

**Issue by becka11y** [readium/readium-js-viewer#551]
When I use the add to library dialog in the Chrome Extension as soon as I select a book via Finder in OS X and press upload, the upload happens and the dialog closes.  Since the dialog has an "Add to Library" button, I expected to return to the dialog from the Choose file feature (in my case Finder) and then to select Add to Library.  This may be my misunderstanding of the how the file chooser works.

#### Expected Behavior
I expected that after selecting a file I would return to the Add to Library dialog, the "Add to Library" button would now be enabled and I would activate it (or Cancel).

#### Observed behavior
When I select the file and leave the Finder, the dialog closes, the EPUB is added to the library.  At one point I was another message dialog displayed but it flashed by too fast to read.

#### Steps to reproduce
1. Open the Chrome Readium App
2. Click the Add to Library button on the toolbar
3. Select Choose File in one of the dialogs. This opens up an operating system Finder/File manager.
4. Select the appropriate file (.epub or directory). Click the Upload or whatever confirmation button is offered by the OS.
5. The Add to Library dialog immediately closes. You may see the progress dialog for adding the file briefly displayed.

### Product
latest official version available from the Chrome Web Store - 2.23.0
Version of the Chrome browser - Version 51.0.2704.103 (64-bit)
OS and version - OS X 10.11.5

#### Additional information
I marked this as A11y because it could be confusing for some people.

**Comment by danielweck** [comment]
Fixed by https://github.com/readium/readium-js-viewer/commit/4e0b2bf2a518b54ce859c5b07d396250cfdd22a4
(as decided on today's conference call)
