### ISSUE TITLE
Install Readium web reader on ubuntu server

### ISSUE THREAD

**Issue by pervy-sage** [readium/readium-js-viewer#560]
So ive been trying for a while to install readium cloud reader. I ran into a few problems I fixed and I thought I installed it correctly but I cant seem to get any of my unzipped or zipped epubs to work.

Here are the instructions for installation I followed:

Install Node.js (details depend on your operating system)
Install the Grunt build tool using the command line:npm install -g grunt-cli
From the command line run:git clone https://github.com/readium/readium-js-viewer.git
From the command line run cd readium-js-viewer
From the command line run git submodule update --init --recursive
From the command line run npm install (in the readium-js-viewer directory)
From the command line run cd readium-js
From the command line run npm install (a second time in the readium-js directory)
After this I changed directory into the parent directory then I ran the grunt command grunt cloudReader but I get an error stating that there are no grunt files. I thought running the last npm install would also generate the grunt files from the package.json. I looked at the npm debug log but I cant see any meaningful error messages. Can anyone help?

**Comment by danielweck** [comment]
Hello, it sounds like you are referring to a very old revision of readium-js-viewer (when Grunt was used as part of the build system). Please follow the instructions in:
https://github.com/readium/readium-js-viewer/blob/develop/README.md

**Comment by pervy-sage** [comment]
Hi Daniel,

Thanks for the speedy reply. I got it to work!!! Now Im trying to add some unzipped epubs to the pub_content folder but they don’t seem to update in the library. The epub I’m adding works on the chrome app but not on the development app created on my server.

Please let me know if I have to create separate help messages.


ZAYD BHYAT 
I.T SUPPORT OFFICER
 



 
SAGE MEDIA GROUP PTY LTD
8/4 QUEEN STREET BENTLEY WA 6102 AUSTRALIA
F: +61 8 9458 1136
 
 <http://www.sagemedia.com.au/>

 
SAGE MEDIA GROUP PTY LTD
8/4 QUEEN STREET BENTLEY WA 6102 AUSTRALIA
F: +61 8 9458 1136
 
 <http://www.sagemedia.com.au/>
   <http://nationalresourcesreview.com.au/>  

This email and any files transmitted with it are confidential to the intended recipient
and may be privileged. If you have received this email inadvertently or you are not the 
intended recipient, you may not disseminate, distribute, copy or in any way rely on it.
Further, you should notify the sender immediately and delete the email from your 
computer. Whilst we have taken precautions to alert us to the presence of viruses, 
we cannot guarantee that this email and any files transmitted with it are free from viruses.
 
 <http://www.buildaustralia.com.au/>

This email and any files transmitted with it are confidential to the intended recipient
and may be privileged. If you have received this email inadvertently or you are not the 
intended recipient, you may not disseminate, distribute, copy or in any way rely on it.
Further, you should notify the sender immediately and delete the email from your 
computer. Whilst we have taken precautions to alert us to the presence of viruses, 
we cannot guarantee that this email and any files transmitted with it are free from viruses.
 
 <http://www.buildaustralia.com.au/>

**Comment by danielweck** [comment]
In the cloud reader, if you want an EPUB (unzipped, or packed) to show-up in the ebook library view, you must add an entry to `epub_content/epub_library.opds`.

**Comment by danielweck** [comment]
See https://github.com/readium/readium-js-viewer/blob/develop/README.md#cloud-reader-deployment
(sorry, the documentation is hard to read at the moment)

**Comment by pervy-sage** [comment]
Please don’t apologise, I’m an idiot for not looking at it properly. The documentation is fine, I just got to read it a little better. I thank you again for answering my questions and this won’t be the last time I ask you questions as I plan on using the android and iOS SDK to do some development.

ZAYD BHYAT 
I.T SUPPORT OFFICER
 



 
SAGE MEDIA GROUP PTY LTD
8/4 QUEEN STREET BENTLEY WA 6102 AUSTRALIA
F: +61 8 9458 1136
 
 <http://www.sagemedia.com.au/>

 
SAGE MEDIA GROUP PTY LTD
8/4 QUEEN STREET BENTLEY WA 6102 AUSTRALIA
F: +61 8 9458 1136
 
 <http://www.sagemedia.com.au/>
   <http://nationalresourcesreview.com.au/>  

This email and any files transmitted with it are confidential to the intended recipient
and may be privileged. If you have received this email inadvertently or you are not the 
intended recipient, you may not disseminate, distribute, copy or in any way rely on it.
Further, you should notify the sender immediately and delete the email from your 
computer. Whilst we have taken precautions to alert us to the presence of viruses, 
we cannot guarantee that this email and any files transmitted with it are free from viruses.
 
 <http://www.buildaustralia.com.au/>

This email and any files transmitted with it are confidential to the intended recipient
and may be privileged. If you have received this email inadvertently or you are not the 
intended recipient, you may not disseminate, distribute, copy or in any way rely on it.
Further, you should notify the sender immediately and delete the email from your 
computer. Whilst we have taken precautions to alert us to the presence of viruses, 
we cannot guarantee that this email and any files transmitted with it are free from viruses.
 
 <http://www.buildaustralia.com.au/>
