### ISSUE TITLE
Full Screen Button with embedded lite reader

### ISSUE THREAD

**Issue by pervy-sage** [readium/readium-js-viewer#561]
Hey Guys,

So after mucking around with readium and building it in different ways I cant seem to figure out how to get the full screen button working when the reader is embedded into the web page. Is this possible?

Cheers

**Comment by danielweck** [comment]
It's not guaranteed that you'll be able to switch into fullscreen mode. For example, <iframe> elements have the allowfullscreen attribute in order to opt-in to allowing their content to be displayed in fullscreen mode.

https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#When_a_fullscreen_request_fails

**Comment by danielweck** [comment]
I am closing this issue now, but please follow-up to let us know if this is actually a problem with Readium.

**Comment by pervy-sage** [comment]
Thanks for that Daniel

ZAYD BHYAT 
I.T SUPPORT OFFICER
 



 
SAGE MEDIA GROUP PTY LTD
8/4 QUEEN STREET BENTLEY WA 6102 AUSTRALIA
F: +61 8 9458 1136
 
 <http://www.sagemedia.com.au/>

 
SAGE MEDIA GROUP PTY LTD
8/4 QUEEN STREET BENTLEY WA 6102 AUSTRALIA
F: +61 8 9458 1136
 
 <http://www.sagemedia.com.au/>
   <http://nationalresourcesreview.com.au/>  

This email and any files transmitted with it are confidential to the intended recipient
and may be privileged. If you have received this email inadvertently or you are not the 
intended recipient, you may not disseminate, distribute, copy or in any way rely on it.
Further, you should notify the sender immediately and delete the email from your 
computer. Whilst we have taken precautions to alert us to the presence of viruses, 
we cannot guarantee that this email and any files transmitted with it are free from viruses.
 
 <http://www.buildaustralia.com.au/>

This email and any files transmitted with it are confidential to the intended recipient
and may be privileged. If you have received this email inadvertently or you are not the 
intended recipient, you may not disseminate, distribute, copy or in any way rely on it.
Further, you should notify the sender immediately and delete the email from your 
computer. Whilst we have taken precautions to alert us to the presence of viruses, 
we cannot guarantee that this email and any files transmitted with it are free from viruses.
 
 <http://www.buildaustralia.com.au/>
