### ISSUE TITLE
Full Screen Button with embedded lite reader

### ISSUE THREAD

**Issue by sage-IT** [readium/readium-js-viewer#562]
Hey,
I know this issue was here before but I cant seem to solve it. With an embedded iframe even if I set the allowfullscreen attribute I still cant get full screen mode. When the link to the epub is placed in the address bar i am able to set full screen etc. I thought it might have been settings on my website but I tested a youtube video with and without the allowfullscreen and this worked fine.

**Comment by danielweck** [comment]
Thanks for posting the issue again. Let's investigate this further.

**Comment by danielweck** [comment]
Usages of 'screenfull' in https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L652
Source: https://github.com/sindresorhus/screenfull.js

'iframe@allowFullScreen="true"' ?
Seems to be known bugs about iframe support: https://github.com/bdougherty/BigScreen/blob/master/src/bigscreen.js

http://stackoverflow.com/questions/19440234/how-to-make-a-whole-website-run-under-fullscreen-with-screenfull-js

**Comment by pervy-sage** [comment]
screenfull did the trick. Thanks for the help

**Comment by danielweck** [comment]
what do you mean? can you please explain how you fixed this?

**Comment by pervy-sage** [comment]
I guess I mis-worded my answer. As an alternate solution to not having the full screen button on the iframe I used the fullscreen.js script. By creating a simple button I was able to put the iframe element into full screen
ZAYD BHYAT 
I.T SUPPORT OFFICER
 



 
SAGE MEDIA GROUP PTY LTD
8/4 QUEEN STREET BENTLEY WA 6102 AUSTRALIA
F: +61 8 9458 1136
 
 <http://www.sagemedia.com.au/>

 
SAGE MEDIA GROUP PTY LTD
8/4 QUEEN STREET BENTLEY WA 6102 AUSTRALIA
F: +61 8 9458 1136
 
 <http://www.sagemedia.com.au/>
   <http://nationalresourcesreview.com.au/>  

This email and any files transmitted with it are confidential to the intended recipient
and may be privileged. If you have received this email inadvertently or you are not the 
intended recipient, you may not disseminate, distribute, copy or in any way rely on it.
Further, you should notify the sender immediately and delete the email from your 
computer. Whilst we have taken precautions to alert us to the presence of viruses, 
we cannot guarantee that this email and any files transmitted with it are free from viruses.
 
 <http://www.buildaustralia.com.au/>

This email and any files transmitted with it are confidential to the intended recipient
and may be privileged. If you have received this email inadvertently or you are not the 
intended recipient, you may not disseminate, distribute, copy or in any way rely on it.
Further, you should notify the sender immediately and delete the email from your 
computer. Whilst we have taken precautions to alert us to the presence of viruses, 
we cannot guarantee that this email and any files transmitted with it are free from viruses.
 
 <http://www.buildaustralia.com.au/>

**Comment by danielweck** [comment]
okay, so it looks like the fullscreen API requires targeting the iframe element rather then the hosted document element, when Readium is embedded inside an iframe.

**Comment by pervy-sage** [comment]
I haven’t tried targeting the hosted document or any element within the iFrame, like an image etc. 
ZAYD BHYAT 
I.T SUPPORT OFFICER
 



 
SAGE MEDIA GROUP PTY LTD
8/4 QUEEN STREET BENTLEY WA 6102 AUSTRALIA
F: +61 8 9458 1136
 
 <http://www.sagemedia.com.au/>

 
SAGE MEDIA GROUP PTY LTD
8/4 QUEEN STREET BENTLEY WA 6102 AUSTRALIA
F: +61 8 9458 1136
 
 <http://www.sagemedia.com.au/>
   <http://nationalresourcesreview.com.au/>  

This email and any files transmitted with it are confidential to the intended recipient
and may be privileged. If you have received this email inadvertently or you are not the 
intended recipient, you may not disseminate, distribute, copy or in any way rely on it.
Further, you should notify the sender immediately and delete the email from your 
computer. Whilst we have taken precautions to alert us to the presence of viruses, 
we cannot guarantee that this email and any files transmitted with it are free from viruses.
 
 <http://www.buildaustralia.com.au/>

This email and any files transmitted with it are confidential to the intended recipient
and may be privileged. If you have received this email inadvertently or you are not the 
intended recipient, you may not disseminate, distribute, copy or in any way rely on it.
Further, you should notify the sender immediately and delete the email from your 
computer. Whilst we have taken precautions to alert us to the presence of viruses, 
we cannot guarantee that this email and any files transmitted with it are free from viruses.
 
 <http://www.buildaustralia.com.au/>
