### ISSUE TITLE
event emitter error

### ISSUE THREAD

**Issue by pravid** [readium/readium-js-viewer#563]
On npm run http, 
browser opens with blank window with error on firebug

TypeError: EventEmitter is not a constructor
$.extend(Globals, new EventEmitter());

**Comment by danielweck** [comment]
Did you follow the steps in the README?
https://github.com/readium/readium-js-viewer/blob/develop/README.md

(it sound like you missed the 'npm run prepare' stage)

**Comment by pravid** [comment]
I did that, here is the error log,
Not getting what is missing


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\pravid\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prepare' ]
2 info using npm@3.5.2
3 info using node@v4.0.0
4 verbose run-script [ 'prepare' ]
5 info lifecycle readium-js-viewer@0.25.0-alpha~prepare: readium-js-viewer@0.25.0-alpha
6 verbose lifecycle readium-js-viewer@0.25.0-alpha~prepare: unsafe-perm in lifecycle true
7 verbose lifecycle readium-js-viewer@0.25.0-alpha~prepare: PATH: C:\Users\pravid\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\inetpub\wwwroot\reader\readium-js-viewer\node_modules\.bin;C:\Users\pravid\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Ruby22\bin;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby1.9.3\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Heroku\bin;C:\Program Files\git\cmd;C:\Program Files\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\nodejs\;C:\Users\pravid\AppData\Roaming\npm
8 verbose lifecycle readium-js-viewer@0.25.0-alpha~prepare: CWD: C:\inetpub\wwwroot\reader\readium-js-viewer
9 silly lifecycle readium-js-viewer@0.25.0-alpha~prepare: Args: [ '/d /s /c',
9 silly lifecycle   'npm run prepare:submodule && npm run prepare:local' ]
10 silly lifecycle readium-js-viewer@0.25.0-alpha~prepare: Returned: code: 1  signal: null
11 info lifecycle readium-js-viewer@0.25.0-alpha~prepare: Failed to exec prepare script
12 verbose stack Error: readium-js-viewer@0.25.0-alpha prepare: `npm run prepare:submodule && npm run prepare:local`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Users\pravid\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at EventEmitter.emit (events.js:172:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Users\pravid\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at ChildProcess.emit (events.js:172:7)
12 verbose stack     at maybeClose (internal/child_process.js:817:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13 verbose pkgid readium-js-viewer@0.25.0-alpha
14 verbose cwd C:\inetpub\wwwroot\reader\readium-js-viewer
15 error Windows_NT 6.1.7601
16 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pravid\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare"
17 error node v4.0.0
18 error npm  v3.5.2
19 error code ELIFECYCLE
20 error readium-js-viewer@0.25.0-alpha prepare: `npm run prepare:submodule && npm run prepare:local`
20 error Exit status 1
21 error Failed at the readium-js-viewer@0.25.0-alpha prepare script 'npm run prepare:submodule && npm run prepare:local'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the readium-js-viewer package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run prepare:submodule && npm run prepare:local
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs readium-js-viewer
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls readium-js-viewer
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by danielweck** [comment]
As per the README "prerequisites" section, you need NPM v2 (not v3), which ships with the NodeJS v4 installer (NodeJS v5 comes with NPM v3). It looks like you have got a hybrid setup NodeJS v4 + NPM v3

**Comment by pravid** [comment]
Okay, thanks. Will install NPM v2 and test.

**Comment by pravid** [comment]
Tried with npm 2, Still the same error
Here is the debug log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prepare' ]
2 info using npm@2.15.9
3 info using node@v4.0.0
4 verbose run-script [ 'prepare' ]
5 info prepare readium-shared-js@0.25.0-alpha
6 verbose unsafe-perm in lifecycle true
7 info readium-shared-js@0.25.0-alpha Failed to exec prepare script
8 verbose stack Error: readium-shared-js@0.25.0-alpha prepare: `npm run prepare:submodule && npm run prepare:local && npm run prepare:patch`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at EventEmitter.emit (events.js:172:7)
8 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at ChildProcess.emit (events.js:172:7)
8 verbose stack     at maybeClose (internal/child_process.js:817:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
9 verbose pkgid readium-shared-js@0.25.0-alpha
10 verbose cwd C:\inetpub\wwwroot\reader2\readium-js-viewer\readium-js\readium-shared-js
11 error Windows_NT 6.1.7601
12 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare"
13 error node v4.0.0
14 error npm  v2.15.9
15 error code ELIFECYCLE
16 error readium-shared-js@0.25.0-alpha prepare: `npm run prepare:submodule && npm run prepare:local && npm run prepare:patch`
16 error Exit status 1
17 error Failed at the readium-shared-js@0.25.0-alpha prepare script 'npm run prepare:submodule && npm run prepare:local && npm run prepare:patch'.
17 error This is most likely a problem with the readium-shared-js package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm run prepare:submodule && npm run prepare:local && npm run prepare:patch
17 error You can get information on how to open an issue for this project with:
17 error     npm bugs readium-shared-js
17 error Or if that isn't available, you can get their info via:
17 error
17 error     npm owner ls readium-shared-js
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]

**Comment by danielweck** [comment]
I suspect the global and local node_modules folders have to be removed and recreated from switching from v4 to v5 (or vice versa).
Can you please try? See first comment in https://github.com/readium/readium-js-viewer/issues/453

**Comment by danielweck** [comment]
NodeJS 4 is the minimum requirement, and NodeJS 6 (LTS) is now supported too.
https://nodejs.org

When switching from one major NPM version to another, the `node_modules` folders in each Readium repository / submodule, as well as the `node_modules` folder of the NodeJS installation itself, should be deleted (and subsequently re-created). Readium's Node dependencies are re-created by using the `npm run prepare` command (which automatically navigates inside each submodule repository). NodeJS's own default global modules are installed by the NodeJS installer.
