### ISSUE TITLE
Issue in importing epub on Readium Cloud Reader

### ISSUE THREAD

**Issue by dmiepub** [readium/readium-js-viewer#564]
We tried to add epub file on https://readium.firebaseapp.com/? but import progress stops on initial percentage.  see attached screenshots:
![screenshot from 2016-09-07 19-15-34](https://cloud.githubusercontent.com/assets/6203084/18314172/7dca08f0-752f-11e6-95b0-6fe37765a3bc.png)

**Comment by danielweck** [comment]
The "import EPUB" button should be disabled in the cloud reader. See existing issue: https://github.com/readium/readium-js-viewer/issues/82
