### ISSUE TITLE
Go to Page not working as expected

### ISSUE THREAD

**Issue by sage-IT** [readium/readium-js-viewer#569]
So ive created a few epubs(fixed layout) using inDesign and whenever i try and go to a specific page, by clicking a button or link, readium seems to load only one part of the page spread and at times only loads the page partially leaving the rest of the page. When using iBooks or other epub reading apps I cant emulate this problem. Ive emulated this problem on the readium chrome extension as well as the light viewer that I have embedded onto a web page. Is there a way around this problem? Should i be using a different method to navigate to different pages on my epub?

**Comment by danielweck** [comment]
it sounds like your inDesign-created scripts use window.location to link into other pages, instead of plain a@href HtML elements.

**Comment by danielweck** [comment]
see: https://github.com/readium/readium-js-viewer/issues/508#issuecomment-197804546

**Comment by pervy-sage** [comment]
I thought that might be the problem. I’ll work on this and report back ASAP
ZAYD BHYAT 
I.T SUPPORT OFFICER
 



 
SAGE MEDIA GROUP PTY LTD
8/4 QUEEN STREET BENTLEY WA 6102 AUSTRALIA
F: +61 8 9458 1136
 
 <http://www.sagemedia.com.au/>

 
SAGE MEDIA GROUP PTY LTD
8/4 QUEEN STREET BENTLEY WA 6102 AUSTRALIA
F: +61 8 9458 1136
 
 <http://www.sagemedia.com.au/>
   <http://nationalresourcesreview.com.au/>  

This email and any files transmitted with it are confidential to the intended recipient
and may be privileged. If you have received this email inadvertently or you are not the 
intended recipient, you may not disseminate, distribute, copy or in any way rely on it.
Further, you should notify the sender immediately and delete the email from your 
computer. Whilst we have taken precautions to alert us to the presence of viruses, 
we cannot guarantee that this email and any files transmitted with it are free from viruses.
 
 <http://www.buildaustralia.com.au/>

This email and any files transmitted with it are confidential to the intended recipient
and may be privileged. If you have received this email inadvertently or you are not the 
intended recipient, you may not disseminate, distribute, copy or in any way rely on it.
Further, you should notify the sender immediately and delete the email from your 
computer. Whilst we have taken precautions to alert us to the presence of viruses, 
we cannot guarantee that this email and any files transmitted with it are free from viruses.
 
 <http://www.buildaustralia.com.au/>

**Comment by rkwright** [comment]
@pervy-sage   Thanks for your help.  But can you avoid embedding email content into the issue tracker?  Thanks

**Comment by llemeurfr** [comment]
@sage-IT shouldn't this issue be close now, if the cause is found?

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/readium-shared-js/issues/275
