### ISSUE TITLE
exception thrown when mouse over a highlight

### ISSUE THREAD

**Issue by kimtuck** [readium/readium-js-viewer#576]
I have a hybrid app using the highlight module to show some highlights.  When I view a page with a highlight, and mouse over it, the event "annotationHoverIn" is emitted.  

This is done in (the hightlight plugin's) manager.js, about line 99, with the following 2 lines:

```
    originalEmit.apply(this, args);
    originalEmit.apply(proxy, args);
```

When this code is called, the "this" keyword is a reference to "Window", which of course does not have the _events property, so it always throws an exception.

Environment:
Chrome, hybrid app, with the highlight plugin enabled; running the master branch code

**Comment by tmoreno** [comment]
I have the same error:

Uncaught TypeError: Cannot read property 'annotationHoverIn' of undefined
      o.emit @ index.js:117
	p @ manager.js:99
	_ @ underscore.js:701
	n @ underscore.js:733
	onHighlightEvent @ group.js:48
	(anonymous function) @ group.js:411
	v.each.v.forEach @ underscore.js:153
	c.boundHighlightCallback @ group.js:387
	dispatch @ jquery.js:4737
	p.handle @ jquery.js:4549

On this function of eventemitter3:

EventEmitter.prototype.emit = function emit(event, a1, a2, a3, a4, a5) {
  var evt = prefix ? prefix + event : event;

  **if (!this._events[evt]) return false;   // Error on this line, _events is undefined**


This error happend on development branch and for all browsers

**Comment by danielweck** [comment]
I can reproduce in cloud reader, using Chrome on Windows 10.
For example:
https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3
`Uncaught TypeError: Cannot read property 'annotationHoverIn' of undefined(…)`

**Comment by danielweck** [comment]
PS: this was working before (the `emit()` function was this-*bound* to the `EventEmitter` object). Breaking change in underlying third-party lib?

**Comment by danielweck** [comment]
Fixed here: 
https://github.com/readium/readium-js-viewer/issues/576

Still unsure whether this is a breaking change in underscore `_.partial()` (which is used in `onHighlightEvent()` https://github.com/readium/readium-shared-js/blob/develop/plugins/highlights/models/group.js#L31 ), or in the EventEmmitter lib itself ( https://github.com/primus/eventemitter3/blob/master/index.js ), or in Readium's trigger/emit patch ( https://github.com/readium/readium-shared-js/blob/develop/plugins/highlights/manager.js#L66 )

@JCCR
