### ISSUE TITLE
Changing default font size and display format to 1 page from beginning without doing so in settings

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#577]
How can i change the default font size? I need to increase it.
And i need also to make it display 1 page of the book at a time.
How can i do that? Where do i have to change in css or javsascript to change default value?
I need it to be always like this and user can change them if he wants from settings.But i need to force them once readium opens.

**Comment by danielweck** [comment]
Hello!

Try this:
https://github.com/readium/readium-js-viewer/blob/develop/src/js/ReaderSettingsDialog.js#L3

```javascript
    // change these values to affec the default state of the application's preferences at first-run.
    var defaultSettings = {
        fontSize: 100,
        syntheticSpread: "auto",
        scroll: "auto",
        columnGap: 60,
        columnMaxWidth: 550,
        columnMinWidth: 400
    }
```

Note that the above overrides the low-level values set in `readium-shared-js`:
https://github.com/readium/readium-shared-js/blob/develop/js/models/viewer_settings.js#L32
