### ISSUE TITLE
How to use ReadiumJS in a new Web Reader project?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js-viewer#581]
I have read all the articles I can find about readium project, mainly from the ReadiumJS home page (https://readium.github.io/) and three github project page (readium-js-viewer, readium-js, readium-shared-js).

I followed the instructions on readium-viewer-js and have successfully made it runs on the local machine. Now I want to move to the next step -- build my own web eReader, that's where I cannot find enough information to go on. 

I just want to build a web app just like Cloud-Reader-Lite provided as demo. But I don't know how to do it.

Specifically, I have two major problems.

1. It is hard to figure out how you guys write the cloud-reader-lite, the "src/cloud-reader-lite" folder (under readium-js-viewer)  only has an "index.html" file. All the js files are put in the "src/js" folder. Then you build all the js file into one bundle, and the "index.html" refers this all-in-one bundle js. It is really hard to mimic it. Can you give me some instruction about how to "read the learn" the cloud-reader-lite project?

2. If I decide to write one all from scratch, even without referencing the cloud-reader-lite demo, where should I start? If this is the case, should I start at the readium-js layer or readium-shared-js layer? I have found an instruction here (https://github.com/readium/readium-js/blob/master/API.md), is this the right place to start? Are there more instructions? Thanks.

Thank you very much.

**Comment by danielweck** [comment]
Once your local clone of the `readium-js-viewer` repository is fully synchronized / up-to-date with the branch of your choice (`master` or `develop`, I recommend the latter), including the submodules `readium-js`, `readium-shared-js` and `readium-cfi-js`, you simply invoke the command line: `npm run prepare` followed by `npm run dist+sourcemap`. All the instruction are in the README:
https://github.com/readium/readium-js-viewer/blob/master/README.md#distribution

There is no documentation that explains how to replicate / create-your-own `readium-js-viewer`. My advice would be to study the code, hack the HTML / CSS, or even the Javascript source tree. This is a good way to get familiar with how the various Readium modules are assembled.
Alternatively, take a look at the `readium-js` "dev" setup, which demonstrates a minimal ReadiumJS boostrap:
https://github.com/readium/readium-js/blob/develop/dev/index.js

Le us know if this helps.

**Comment by hz0324** [comment]
Thank you very much, sir.
It indeed helps.
^_^
