### ISSUE TITLE
<epub:trigger handler does not stop propagation of event

### ISSUE THREAD

**Issue by kimtuck** [readium/readium-js-viewer#582]
This issue is a Bug

When viewing the document found here http://epubtest.org/epubs/epub30-test-0100-20160116.epub; one of the pages has a test for epub-trigger.  The first test validates if an external button can cause the audio playback to begin.

This external button is configured using <ebpub:trigger .....>

The button handler executes correctly, but the event itself is then bubbled up.  If the reader has another event handler wired to the dom tree, that event handler will also execute.

In my case, I have a click handler wired to the body element, which I use to control page navigation (click on the left side of the page, go left; click on the right side of the page, go right).  In my case, if the user clicks on the button, I want the button action to occur and not the navigation action.

Ideally, the code in trigger.js would return false, which would cause the event not to bubble up.

Using readium-js-viewer, dev branch; in a hybrid app.
(Latest Chrome, windows 7)

**Comment by danielweck** [comment]
note that the epub-testsuite files are linked from the default cloud reader library:
https://readium.firebaseapp.com/?epubs=epub_content%2Fepub_testsuite.opds

**Comment by danielweck** [comment]
here is a direct link to the trigger page:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub-testsuite%2Fmaster%2Fcontent%2F30%2Fepub30-test-0100&goto=%7B%22idref%22%3A%22xhtml-multi-003%22%2C%22elementCfi%22%3A%22%2F4%2F2%2F2%5Btrigger%5D%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D&

**Comment by danielweck** [comment]
code reference:
https://github.com/readium/readium-shared-js/blob/develop/js/models/trigger.js#L103

**Comment by danielweck** [comment]
Fixed by https://github.com/readium/readium-shared-js/pull/346
