### ISSUE TITLE
Set layout settings on load?

### ISSUE THREAD

**Issue by attilavago** [readium/readium-js-viewer#583]
Is there a way to set layout settings programmatically on load? For instance, i am trying to have a single page view instead of a 2 page spread, and I know that going into the settings can do that, but I want this to be set by default in the code. Is this possible at all?

**Comment by mahag** [comment]
Any solution?I need to apply the same too

**Comment by danielweck** [comment]
I you are using the "cloud reader" (or Chrome app) from `readium-shared-js`, then you can modify the hard-coded default settings:
https://github.com/readium/readium-js-viewer/blob/develop/src/js/ReaderSettingsDialog.js#L3
```javascript
    var defaultSettings = {
        fontSize: 100,
        syntheticSpread: "auto",
        scroll: "auto",
        columnGap: 60,
        columnMaxWidth: 550,
        columnMinWidth: 400
    }
```

...but, bear in mind that LocalStorage in users' web browsers may already contain values that override the defaults, see usage of `Settings.getMultiple(['reader', ...], function(settings){...});` and `Settings.ge(['reader'], function(settings){...});`:
https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L1048

**Comment by danielweck** [comment]
If you are not using `readium-js-viewer` (only `readium-shared-js`, then you can change the hard-coded defaults here:
https://github.com/readium/readium-shared-js/blob/develop/js/models/viewer_settings.js#L32

**Comment by danielweck** [comment]
In `readium-js-viewer`, if you want to *always* use specific settings each time a book is open, or each time the application starts, you can add a call to `Settings.put('reader', json);` in your desired event listener.
Make sure to `read` the stored settings JSON, then add / override your desired values.
Typically:
```javascript
                Settings.get('reader', function(json)
                {
                    if (!json)
                    {
                        json = {};
                    }

                    json.MY_SETTING_KEY = MY_SETTING_VALUE;

                    Settings.put('reader', json);
                });
        });
```

For example:
https://github.com/readium/readium-js-viewer/blob/develop/src/js/ReaderSettingsDialog.js#L282

**Comment by andrewgribben** [comment]
Thanks @danielweck I  was wondering about this too, that's what I needed to know.
