### ISSUE TITLE
NPM 4 breaks `npm run prepare`

### ISSUE THREAD

**Issue by JCCR** [readium/readium-js-viewer#600]
**Update:** Current workaround is to downgrade to npm 3: `npm install -g npm@latest-3`

As part of the development install step we ask users to run `npm run prepare`
This no longer works with NPM v4 due to it using the name of the script 'prepare' for a package's install lifecycle.
This is because npm runs scripts with the name `prepare` when executing `npm install`, and in our prepare script we invoke `npm install`. That probably causes an infinite loop or npm goes into an undefined state.

We need to differentiate the script name or adapt our build steps to work with the new intended 'prepare' script usage.

**Comment by danielweck** [comment]
Indeed!

https://github.com/npm/npm/releases/tag/v4.0.0

> NEW prepare SCRIPT. prepublish DEPRECATED (BREAKING)
> prepublish has been deprecated, replaced by prepare. A prepublishOnly script has been temporarily added, which will only run on npm publish.

Let's rename Readium's `prepare` script task to ... `configure`? `init`? `setup`?

**Comment by mahag** [comment]
When caaling npm install like this it works.But after it npm run build or npm run dist both fails for the same issue. 
How should i call them to get readium cloud reader?

**Comment by danielweck** [comment]
@mahag, what are your NodeJS and NPM versions, OS, and what are the error messages?

**Comment by mahag** [comment]
NodeJs is 4.5.
OS is windows7 64-bit
and for npm how can i know its version ?
This is the error i am getting when running npm run dist
![image](https://cloud.githubusercontent.com/assets/10612561/23058300/030a5946-f4fd-11e6-873d-c8913ced6c3b.png)
![image](https://cloud.githubusercontent.com/assets/10612561/23058308/0aefba20-f4fd-11e6-931b-7c4c00f7fa31.png)


![image](https://cloud.githubusercontent.com/assets/10612561/23058315/11ffcecc-f4fd-11e6-9f29-16113b15e8df.png)

**Comment by danielweck** [comment]
the error indicates that 'npm run prepare' need to be executed first.
could you please try?

**Comment by mahag** [comment]
npm run prepare fails
![image](https://cloud.githubusercontent.com/assets/10612561/23067157/9f28f840-f526-11e6-8c35-ab8895852b52.png)


and when running instead of it npm install -g npm@latest-3 i get only this
![image](https://cloud.githubusercontent.com/assets/10612561/23067124/79554f74-f526-11e6-9848-db5aa90febb1.png)

**Comment by danielweck** [comment]
Related: https://github.com/readium/readium-js/issues/178 and https://github.com/readium/readium-js-viewer/issues/622

**Comment by danielweck** [comment]
Closing this issue, all discussions / fixes now here https://github.com/readium/readium-js/issues/178
