### ISSUE TITLE
I cant run npm prepare

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#604]
When running npm prepare it is failing and showing many errors
![image](https://cloud.githubusercontent.com/assets/10612561/22970895/73cb9c08-f37c-11e6-9185-45ceb3adca5d.png)
Is there anything wrong?
I do have latest node installed v 6

**Comment by JCCR** [comment]
@mahag 
Hi thanks for your report.

We're having issues with NPM v4.
There's an issue filed for that #600 

If you are able to use npm 3 here's how you can downgrade:
$ `npm install -g npm@latest-3`

**Comment by JCCR** [comment]
Updated #600.
Closing this issue as it's a duplicate.
