### ISSUE TITLE
Black background for links, expected behavior?

### ISSUE THREAD

**Issue by chrismbf** [readium/readium-js-viewer#607]
When I view epubs on Readium, frequently links are displayed with a black background. Is this expected and intentional behavior?

![screen shot 2017-02-27 at 11 10 32 am](https://cloud.githubusercontent.com/assets/26068294/23380798/d11e1a3c-fd01-11e6-9868-bee96221e6dd.jpg)

Thanks!

**Comment by rkwright** [comment]
Check your settings to make sure you didn't inadvertently select "Night" mode or similar.  Choose "default" and see what you get.

**Comment by chrismbf** [comment]
Oh, that seems to do it! I had "Black and White" selected, and Default fixed it. Thanks!
