### ISSUE TITLE
First visible (text-)element on page spread

### ISSUE THREAD

**Issue by larsvoigt** [readium/readium-js-viewer#609]
Hi,
how can I get the first visible (text-)element on page spread (```reading-area```)? Or the spread viewport dimension?
I would like to set the focus on the first element if  page is loaded. 

Thanks Lars

**Comment by danielweck** [comment]
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L1610
`ReaderView.getFirstVisibleCfi()`
(also `ReaderView.getLastVisibleCfi()`)

**Comment by danielweck** [comment]
Then combine with `CfiNavigationLogic.getElementByCfi()` (search for usages in `readium-js-viewer` source tree):
https://github.com/readium/readium-shared-js/blob/develop/js/views/cfi_navigation_logic.js#L1139

**Comment by danielweck** [comment]
@JCCR Let us know if there is a better way :)
Thanks!

**Comment by rohitvishwakarma-sf** [comment]
@larsvoigt were you able to do that ?
