### ISSUE TITLE
scripts/readium-js-viewer_all.js" is not available.

### ISSUE THREAD

**Issue by ashishdixitmca** [readium/readium-js-viewer#610]
Hi,

We are trying to use readium-js-viewer in html for that we downloaded the code from  https://github.com/readium/readium-js-viewer as per the given instruction from develop branch.

But the "scripts/readium-js-viewer_all.js" folder and "readium-js-viewer_all.js" file is missing in our local working directory.

Can you please suggest and help us to resolve this issue.

Best Regards,
Ashish.

**Comment by danielweck** [comment]
Hello, you can either build the cloud reader app as per the instructions in the README:
https://github.com/readium/readium-js-viewer/blob/develop/README.md
...or you can download prebuilt packages from the release area:
https://github.com/readium/readium-js-viewer/releases/tag/0.25.0
