### ISSUE TITLE
Provide us repository link to clone entire build version and ready to execute from local system

### ISSUE THREAD

**Issue by ashishdixitmca** [readium/readium-js-viewer#612]
Hi,

We are trying to download using the below urls

https://github.com/readium/readium-js-viewer/releases/download/0.25.0/Readium_cloud-reader-lite.zip
https://github.com/readium/readium-js-viewer/releases/download/0.25.0/Readium_cloud-reader.zip

But it seems we are always getting incomplete build. 
Can you please give us the repository link, so that we could clone entire build version. And we could execute it from local iis with our sample epub file.

Best Regards
Ashish

**Comment by danielweck** [comment]
I have just tried the ZIP downloads `Readium_cloud-reader-lite.zip` and `Readium_cloud-reader.zip` from the official *v0.25* release:
https://github.com/readium/readium-js-viewer/releases/tag/0.25.0
...and it all works fine.

Basically:
1) unzip into a directory,
2) serve static HTTP files from that folder (or any parent folder),
3) open web browser to root URL (e.g. `http://127.0.0.1:8080/readium/cloud-reader/index.html`),
4) then try a URL with the `epubs` query string parameter to load an ebook library file (e.g. `http://127.0.0.1:8080/readium/cloud-reader/index.html?epubs=../ebooks_library.opds`, assuming the OPDS file exists inside the HTTP folder `./readium/ebooks_library.opds`)
5) then try a URL with the `epub` query string parameter to load a single ebook file (e.g. `http://127.0.0.1:8080/readium/cloud-reader/index.html?epub=../../ebook.epub`, assuming the EPUB file exists inside the HTTP folder `./ebook.epub`)

Alternatively, you can build your own version of the cloud reader by following instructions in the README:
https://github.com/readium/readium-js-viewer/blob/develop/README.md
