### ISSUE TITLE
cloud-reader not able to open epub files, where as epub files are available in the server.

### ISSUE THREAD

**Issue by ashishdixitmca** [readium/readium-js-viewer#613]
Hi,

Thx for your previous mail reply which really help us a lot.

As per your previous suggestion we are trying to load opds files and open epub files in the  cloud-reader.

The cloud-reader could successfully load the opds feed but once we are trying to open the epub file, we are getting error “Invalid content”.

Whereas the epub files are available in the server. Please refer http://uatnotabene.cloudapp.net:8080/cloud-reader/index.html?epubs=%2Fepub_content%2Fepub_library.json&
The below files are the valid and are available in the server, please refer the attach image.
•	packed EPUB
•	Accessible EPUB 3
•	navigator.epubReadingSystem (zipped)
And those files are ok we could read those files from radium-android/ios

Could you please check and suggest us.

We have another question. Could we open an epub file which available in the other server iis server. Using the query string? 
Like.

http://127.0.0.1:8080/readium/cloud-reader/index.html?epub= http://127.0.0.1:8080/fileserver/ebook.epub

Please let us know.

Best Regards,
Ashish

![iis](https://cloud.githubusercontent.com/assets/8705743/24048751/d26824c6-0b4f-11e7-8cac-2572551674d7.gif)

**Comment by danielweck** [comment]
First of all, just a quick informative note about the use of relative or absolute paths within the `epub` and `epubs` URL query parameters, when creating links to the ReadiumJS cloud/web reader:

Your JSON library file (not OPDS, by the way) is located at `{SITES}/readium/epub_content/epub_library.json` inside the filesystem of your static HTTP server, which serves the contents of the `{SITES}/readium/` folder.
This determines the full absolute URL:
http://uatnotabene.cloudapp.net:8080/epub_content/epub_library.json

Both the relative and absolute path syntaxes work into the `epubs` and `epub` query string parameters, see for example:

http://uatnotabene.cloudapp.net:8080/cloud-reader/index.html?epubs=..%2Fepub_content%2Fepub_library.json
(`../epub_content/epub_library.json` is relative to `index.html`)

http://uatnotabene.cloudapp.net:8080/cloud-reader/index.html?epubs=%2Fepub_content%2Fepub_library.json
(note the missing `..` path prefix => `/epub_content/epub_library.json` is absolute to the server root)

Or even:
http://uatnotabene.cloudapp.net:8080/cloud-reader/index.html?epubs=http:%2F%2Fuatnotabene.cloudapp.net:8080%2Fepub_content%2Fepub_library.json
(full `http[s]://` URL)

**Comment by danielweck** [comment]
Please remove the space character in `/epub_content/Calendar girl.epub` and the folder `/epub_content/Calendar girl/` (remember to update your `/epub_content/epub_library.json`).
Let me know if this works.
escaping.

**Comment by danielweck** [comment]
Note that you can always test your files with the official ReadiumJS web/cloud reader build, e.g.:
https://readium.firebaseapp.com/?epubs=https%3A%2F%2Fcrossorigin.me%2Fhttp%3A%2F%2Fuatnotabene.cloudapp.net%3A8080%2Fepub_content%2Fepub_library.json
(I use the https://crossorigin.me proxy to add HTTP CORS headers and secure HTTP)

**Comment by danielweck** [comment]
Copied from:
@ashishdixitmca 
https://github.com/readium/readium-js-viewer/issues/614
Thx again for your support.

As per your suggestion for http://uatnotabene.cloudapp.net:8080/cloud-reader/index.html?epubs=../epub_content/epub_library.json&
“Please remove the space character in /epub_content/Calendar girl.epub and the folder /epub_content/Calendar girl/ (remember to update your /epub_content/epub_library.json).”
We have removed the spaces for “packed EPUB”. But still getting the same issue.
Can you please help us to execute it.

Best Regards,
Ashish

**Comment by danielweck** [comment]
The required files do not exist:

http://uatnotabene.cloudapp.net:8080/epub_content/Calendar_girl/META-INF/container.xml

http://uatnotabene.cloudapp.net:8080/epub_content/Calendar_girl.epub

There's something wrong on your server. Can you please check your paths?

**Comment by danielweck** [comment]
This is now stale, and it seems to be an error on the user's server. Let's close the issue.

**Comment by kcs-hetal** [comment]
Hi,
Please guide for below issue.

I am using Readium_cloud-reader-lite to read epub file and I am facing below error when i am using this on live server. I have checked path of epub file, it is exist on given path. Also I have checked path of files included in index.html file all are at their place.

![selection_015](https://user-images.githubusercontent.com/39588141/40481530-5588bd1a-5f6f-11e8-80f4-c4fb17d8ea23.png)
![selection_016](https://user-images.githubusercontent.com/39588141/40481652-b1f4d0e8-5f6f-11e8-97e1-9609af284d26.png)

On another hosting server it is working, even on local environment it is working fine.

**Comment by rkwright** [comment]
@kcs-hetal Hm.  This seems like it is likely to be a path/permissions issue.  I note that the server emitting the error is being accessed via https.  Could there be some firewall issue or similar?
