### ISSUE TITLE
Not able to open epub in cloud-reader

### ISSUE THREAD

**Issue by ashishdixitmca** [readium/readium-js-viewer#614]
Thx again for your support.

As per your suggestion for http://uatnotabene.cloudapp.net:8080/cloud-reader/index.html?epubs=../epub_content/epub_library.json&
 “Please remove the space character in /epub_content/Calendar girl.epub and the folder /epub_content/Calendar girl/ (remember to update your /epub_content/epub_library.json).”
We have removed the spaces for “packed EPUB”. But still getting the same issue.
Can you please help us to execute it.

Best Regards,
Ashish

**Comment by danielweck** [comment]
Please do not open new issues, simply continue the discussion in the existing thread (I am copying your message across, and closing this issue now):

https://github.com/readium/readium-js-viewer/issues/613
