### ISSUE TITLE
TOC link not taking to right position if clicked twice in "Auto" scroll mode(single/double display)

### ISSUE THREAD

**Issue by Nalinc** [readium/readium-js-viewer#616]
I got this error while viewing _Accessible EPUB 3_ ebook on on the [firebase app](https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&).

Steps for replication:

1) Open epub Accessible EPUB 3 (in reflowable mode- double page)
2) Open Table Of Contents from the top-menu.
3) Click on a third level TOC link (Say "Language" in Chapter 2).
**Building a Better EPUB: Fundamental Accessibility > A Solid Foundation: Structure and Semantics > Language**
 You will be taken to "Language" page
4) Click on the same TOC link again. You will observe that the user is taken to first page of that same chapter instead of staying on the same page.

Now if you click the same link again then you are taken to correct page. However, it keeps toggling between the first page of that html and the actual page that the TOC refers to on successive clicks. 

Tested on Chrome Version 56.0

**Comment by Nalinc** [comment]
Hi @rkwright 

I think this is most likely related to this issue in readium-shared-js https://github.com/readium/readium-shared-js/issues/384

Could you please confirm?

**Comment by danielweck** [comment]
Fixed the regression bug ( culprit: https://github.com/readium/readium-shared-js/commit/99640b81dde92c153380bf0a57304e58279a650f ) via: https://github.com/readium/readium-shared-js/commit/9322c0afa3918db66c8e9f669377d9eca4975948
Please let us know how it goes in your tests.

**Comment by danielweck** [comment]
Please read the follow-up:
https://github.com/readium/readium-shared-js/issues/384#issuecomment-305156108
(make sure you pull the latest code from the `develop` branch, as there is a regression bugfix)
