### ISSUE TITLE
Epub Disply Issues Cloud Reader

### ISSUE THREAD

**Issue by sage-IT** [readium/readium-js-viewer#618]
#### This issue is a Bug
Having Display issues when using the cloud-reader, running the `npm run dist` does create the desired files but when I try and display an epub using the cloud-reader-lite i get this error `undefined is not a valid argument for URI` Ive used the readium frame work before and did some development 

#### Related issue(s) and/or pull request(s)
NA

#### Expected Behaviour
Using the link: `LocalServer/cloud-reader-lite/index.html?epubs=EPUBs/accessible_epub_3`
Was expecting the epub to appear

#### Observed behaviour
Instead the radium frame and library header and site is displayed with no ePub

#### Steps to reproduce
1. First, I downloaded the readium-js-viewer using git
2. Then ran the command `npm run prepare`
3. Then ran the command `npm run dist`
4. Then extracted the resulting cloud-reader-lite folder onto my local server

#### Test file(s)
I used one of the epubs that have been supplied with the readium package

### Product

Readium cloud reader app

#### Additional information
Ive tried this with both the cloud-reader and the cloud-reader-lite

**Comment by danielweck** [comment]
FYI:

The Readium cloud/web reader is currently being successfully deployed at two URLs:

https://readium.firebaseapp.com (latest 2.27-alpha build from the `develop` branch, automatically built via TravisCI)

https://readium-master.surge.sh (stable 2.26 manual build from the `master` branch)

I have also just tried the cloud-reader-lite on my local development machine (OSX). No problems.

Can we have a look at your console logs?

**Comment by sage-IT** [comment]
wow this is an old one. Im so sorry but ive been so busy since putting this issue up. This can be closed as I have a more pressing issue with preparing readium
