### ISSUE TITLE
Document the need for npm v3

### ISSUE THREAD

**Issue by JoelSanchez** [readium/readium-js-viewer#622]
It is known that `npm run prepare` fails with npm >= 4. The current workaround is to execute `npm install -g npm@latest-3` (see issue #600). I think this should be added as a note in the README while this remains unsolved. Thanks

**Comment by danielweck** [comment]
Thank you for your feedback. We really need to rename the "prepare" task, so we can support NPM >= 4.
I will look into this.
Dan

**Comment by r-a-y** [comment]
I was wondering why the build process was always failing for me!

Yes, please note the need for npm v3 in the `readme.md`.

**Comment by danielweck** [comment]
Related: https://github.com/readium/readium-js/issues/178 and https://github.com/readium/readium-js-viewer/issues/600

**Comment by danielweck** [comment]
Closing this issue, all discussions / fixes now here https://github.com/readium/readium-js/issues/178
