### ISSUE TITLE
chai-as-promised latest version dependency on chai@>= 2.1.2 < 4 breaks build

### ISSUE THREAD

**Issue by hotTea** [readium/readium-js-viewer#623]
This issue is a Bug

#### Expected Behaviour
npm run prepare:all should not give any errors

#### Observed behaviour
npm run prepare:all gives following errors:

npm ERR! Linux 4.4.0-78-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package chai@4.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer chai-as-promised@6.0.0 wants chai@>= 2.1.2 < 4

#### Steps to reproduce
1. checkout develop branch
git clone --recursive -b develop https://github.com/readium/readium-js-viewer.git readium-js-viewer
2. cd readium-js-viewer
3. git submodule update --init --recursive
4. npm run prepare:all

### Product

* Readium cloud reader app

#### Additional information
"chai" 4.0.0 was just released - https://github.com/chaijs/chai/releases/tag/4.0.0. chai-as-promised's latest version (https://github.com/domenic/chai-as-promised/blob/v6.0.0/package.json) has dependency defined as ""chai": ">= 2.1.2 < 4"". Since readium-viewers's chai dependency is "latest", above dependency chain fails.

**Comment by danielweck** [comment]
Ah, yes:
https://github.com/domenic/chai-as-promised/issues/184

I am fixing this...

**Comment by danielweck** [comment]
Issue addressed here: https://github.com/readium/readium-js-viewer/commit/4032f1e00bc34022b47cc11e6c317993c7ad9f1d

**Comment by hotTea** [comment]
Thanks !
