### ISSUE TITLE
Not able to clone latest solution of readium-js-viewer.Error on npm run prepare

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#624]
I tried the following steps on GitCMD:

1- git clone --recursive -b develop https://github.com/readium/readium-js-viewer.git readium-js-viewer
2- cd readium-js-viewer
3- git submodule update --init --recursive
4- git checkout develop && git submodule foreach --recursive "git checkout develop"
5- npm run prepare:all

At the lest step i am getting an error
`+-- jquery@2.2.4
+-- jshint@2.9.4  invalid
+-- karma@1.7.0  invalid
+-- karma-chrome-launcher@2.1.1  invalid
+-- karma-firefox-launcher@1.0.1  invalid
+-- karma-jasmine@1.1.0  invalid
+-- karma-sauce-launcher@1.1.0  invalid
+-- markdown-it@4.4.0  extraneous
+-- mdn-links@0.1.0  extraneous
+-- ncp@2.0.0  invalid
+-- npm-run-all@4.0.2  invalid
+-- pegjs@0.10.0  invalid
+-- requirejs@2.3.3  invalid
+-- underscore@1.8.3  invalid
`-- watch@1.0.2  invalid

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nwf\\AppData\\Ro
aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\nwf\readium-js-viewer\readium-js\readium-shared-js\readiu
m-cfi-js\node_modules\.staging\yui-7053ba69
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nwf\readium-js-
viewer\readium-js\readium-shared-js\readium-cfi-js\node_modules\.staging\yui-705
3ba69' -> 'C:\Users\nwf\readium-js-viewer\readium-js\readium-shared-js\readium-c
fi-js\node_modules\yui'
npm ERR!     at whenOldMovedAway (C:\Users\nwf\AppData\Roaming\npm\node_modules\
npm\lib\install\action\finalize.js:43:5)
npm ERR!     at C:\Users\nwf\AppData\Roaming\npm\node_modules\npm\lib\utils\rena
me.js:13:14
npm ERR!     at CB (C:\Users\nwf\AppData\Roaming\npm\node_modules\npm\node_modul
es\graceful-fs\polyfills.js:93:17)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nwf\readium-js-
viewer\readium-js\readium-shared-js\readium-cfi-js\node_modules\.staging\yui-705
3ba69' -> 'C:\Users\nwf\readium-js-viewer\readium-js\readium-shared-js\readium-c
fi-js\node_modules\yui'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\nwf\readium-
js-viewer\readium-js\readium-shared-js\readium-cfi-js\node_modules\.staging\yui-
7053ba69' -> 'C:\Users\nwf\readium-js-viewer\readium-js\readium-shared-js\readiu
m-cfi-js\node_modules\yui'
npm ERR!     at whenOldMovedAway (C:\Users\nwf\AppData\Roaming\npm\node_modules\
npm\lib\install\action\finalize.js:43:5)
npm ERR!     at C:\Users\nwf\AppData\Roaming\npm\node_modules\npm\lib\utils\rena
me.js:13:14
npm ERR!     at CB (C:\Users\nwf\AppData\Roaming\npm\node_modules\npm\node_modul
es\graceful-fs\polyfills.js:93:17)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nwf\readium-js-
viewer\readium-js\readium-shared-js\readium-cfi-js\node_modules\.staging\yui-705
3ba69' -> 'C:\Users\nwf\readium-js-viewer\readium-js\readium-shared-js\readium-c
fi-js\node_modules\yui'
npm ERR!     at Error (native) parent: 'readium-cfi-js' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nwf\readium-js-viewer\readium-js\readium-shared-js\readium
-cfi-js\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nwf\\AppData\\Ro
aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare:local"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! readium-cfi-js@0.27.0-alpha prepare:local: `npm outdated ; npm install
&& npm update && npm run prepare:local:common`
npm ERR! Exit status 4294963248
npm ERR!
npm ERR! Failed at the readium-cfi-js@0.27.0-alpha prepare:local script 'npm out
dated ; npm install && npm update && npm run prepare:local:common'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the readium-cfi-js packag
e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm outdated ; npm install && npm update && npm run prepare:local:c
ommon
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs readium-cfi-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls readium-cfi-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nwf\readium-js-viewer\readium-js\readium-shared-js\readium
-cfi-js\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nwf\\AppData\\Ro
aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare:all"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! readium-cfi-js@0.27.0-alpha prepare:all: `npm run prepare:local`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-cfi-js@0.27.0-alpha prepare:all script 'npm run p
repare:local'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the readium-cfi-js packag
e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run prepare:local
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs readium-cfi-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls readium-cfi-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nwf\readium-js-viewer\readium-js\readium-shared-js\readium
-cfi-js\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nwf\\AppData\\Ro
aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare:submodule"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! readium-shared-js@0.27.0-alpha prepare:submodule: `cd readium-cfi-js &&
 npm run prepare:all && cd .. && ls`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-shared-js@0.27.0-alpha prepare:submodule script '
cd readium-cfi-js && npm run prepare:all && cd .. && ls'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the readium-shared-js pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd readium-cfi-js && npm run prepare:all && cd .. && ls
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs readium-shared-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls readium-shared-js
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nwf\readium-js-viewer\readium-js\readium-shared-js\npm-deb
ug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nwf\\AppData\\Ro
aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare:all"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! readium-shared-js@0.27.0-alpha prepare:all: `npm run prepare:submodule
&& npm run prepare:local`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-shared-js@0.27.0-alpha prepare:all script 'npm ru
n prepare:submodule && npm run prepare:local'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the readium-shared-js pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run prepare:submodule && npm run prepare:local
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs readium-shared-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls readium-shared-js
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nwf\readium-js-viewer\readium-js\readium-shared-js\npm-deb
ug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nwf\\AppData\\Ro
aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare:submodule"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! readium-js@0.27.0-alpha prepare:submodule: `cd readium-shared-js && npm
 run prepare:all && cd .. && ls`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-js@0.27.0-alpha prepare:submodule script 'cd read
ium-shared-js && npm run prepare:all && cd .. && ls'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the readium-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd readium-shared-js && npm run prepare:all && cd .. && ls
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs readium-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls readium-js
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nwf\readium-js-viewer\readium-js\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nwf\\AppData\\Ro
aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare:all"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! readium-js@0.27.0-alpha prepare:all: `npm run prepare:submodule && npm
run prepare:local`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-js@0.27.0-alpha prepare:all script 'npm run prepa
re:submodule && npm run prepare:local'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the readium-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run prepare:submodule && npm run prepare:local
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs readium-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls readium-js
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nwf\readium-js-viewer\readium-js\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nwf\\AppData\\Ro
aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare:submodule"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! readium-js-viewer@0.27.0-alpha prepare:submodule: `cd readium-js && npm
 run prepare:all && cd .. && ls`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-js-viewer@0.27.0-alpha prepare:submodule script '
cd readium-js && npm run prepare:all && cd .. && ls'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the readium-js-viewer pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd readium-js && npm run prepare:all && cd .. && ls
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs readium-js-viewer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls readium-js-viewer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nwf\readium-js-viewer\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nwf\\AppData\\Ro
aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare:all"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! readium-js-viewer@0.27.0-alpha prepare:all: `npm run prepare:submodule
&& npm run prepare:local`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-js-viewer@0.27.0-alpha prepare:all script 'npm ru
n prepare:submodule && npm run prepare:local'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the readium-js-viewer pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run prepare:submodule && npm run prepare:local
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs readium-js-viewer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls readium-js-viewer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nwf\readium-js-viewer\npm-debug.log

C:\Users\nwf\readium-js-viewer>`

Running npm run prepare gives an error too
I have windows 7(x64) and node.js v 6.10.3

**Comment by danielweck** [comment]
FYI: everything works fine on my OSX machine, as well as on Travis's Continuous Integration servers (Linux).
There seems to be a filesystem problem on your machine:
`Error: EPERM: operation not permitted, rename 'C:\PATH_TO\readium-cfi-js\node_modules.staging\yui-
7053ba69' -> 'C:\PATH_TO\readiu
m-cfi-js\node_modules\yui'
Have you tried force-deleting the `node_modules` folders in each repository, and invoke `npm prepare:all` again? Perhaps it is worth upgrading to NodeJS v7 / NPM v4 to see if it helps?

**Comment by danielweck** [comment]
You could also try Yarn: `yarn prepare:yarn:all` instead of NPM.

**Comment by danielweck** [comment]
Try this: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by mahag** [comment]
Where i can find  NodeJS v7 / NPM v4?
I only have Node v6 and npm v3 or Node v7 and npm v8

**Comment by danielweck** [comment]
Good point, NodeJS v7 is not available anymore:
https://nodejs.org
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.0.0

**Comment by danielweck** [comment]
I was using NodeJS v7 and NPM v4 (no problems building ReadiumJS). TravisCI uses the same versions.
I have just upgraded to NodeJS v8 and NPM v5. All works fine.

**Comment by mahag** [comment]
We tried on 3 different machines (windows7,windows 8.1,windows 10)using NodeJS v8 and NPM v5 . 
All same result. npm run prepare:all fails as i mentioned before.
Is there anything i have to check or to set in order to make it work?

**Comment by danielweck** [comment]
Could you please update your ReadiumJS repositories (I fixed some issues in the NPM scripts, I tested on Windows 10 with NPM v5 / NodeJS v8), make sure to completely remove the `node_modules` folders in each submodule, also delete any potential `package-lock.json`, ensure you have no local changes in your `package.json` files, and invoke `npm run prepare:all` from the top-level `readium-js-viewer` directory. Thanks!
