### ISSUE TITLE
Cloud-Reader Lite Issue

### ISSUE THREAD

**Issue by sage-IT** [readium/readium-js-viewer#627]
Cloud reader lite cant seem to load any epub, showing a loading icon the whole time and indicating that the URI is undefined. See attached image.

#### Related issue(s) and/or pull request(s)
*NA

#### Expected Behaviour
Open one of the default epubs that comes with readium. In this case accessible_epub_3

#### Observed behaviour
Readiumlight reader just seems to show the loader and not do anything. Attached is an image from a screen grab from the console log of chrome

#### Steps to reproduce
1. Run the command `npm run dist`
2. Copy the lite reader from the dist folder to a 
3. Then open Chrome and navigate to local address `192.168.1.175/cloud-reader-lite/index.html?epub=EPUBs/accessible_epub_3`
![screen shot 2017-06-20 at 3 43 59 pm](https://user-images.githubusercontent.com/21095734/27322433-bbe3ba1e-55d0-11e7-9412-27eca454bed5.png)

#### Test file(s)
Ive also tried this on our public server you can find it here: `https://buildaustralia.com.au/cloud-reader-lite/index.html?epubs=EPUBs/accessible_epub_3`

### Product
* Readium cloud reader app

**Comment by sage-IT** [comment]
After much debugging and prodding I have fixed this issue This can be closed

**Comment by danielweck** [comment]
Hello, could you please share your fix? (unless of course it was specific to your deployment of the cloud reader)
