### ISSUE TITLE
Enable the Annotation

### ISSUE THREAD

**Issue by deepeshk12** [readium/readium-js-viewer#629]
How can I enable Annotation feature.

**Comment by llemeurfr** [comment]
There is an ongoing initiative with hypothesis.js (see [this post](https://www.edrlab.org/2017/03/12/a-partnership-to-bring-open-annotation-to-ebooks/)). A PR will soon be pushed by Evident Point on the Readium repo.

**Comment by danielweck** [comment]
In the interim, you can enable the "text highlighting" functionality (not a fully fledged annotation feature, but you can implement a more complete system based on this building block), by activating the plugin in `readium-shared-js`: https://github.com/readium/readium-shared-js/blob/develop/plugins/plugins.cson

Example usage:
https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L1167
```javascript
                    readium.reader.plugins.highlights.initialize({
                        annotationCSSUrl: readerOptions.annotationCSSUrl
                    });

                    readium.reader.plugins.highlights.on("annotationClicked", function(type, idref, cfi, id) {
        console.debug("ANNOTATION CLICK: " + id);
                        readium.reader.plugins.highlights.removeHighlight(id);
                    });
```

https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L851
```javascript
        $(".icon-annotations").on("click", function () {
            readium.reader.plugins.highlights.addSelectionHighlight(Math.floor((Math.random()*1000000)), "test-highlight");
        });
```

**Comment by hz0324** [comment]
@llemeurfr Hi, I have read the post you mentioned, looks like an exciting feature. The post says the annotation will be launched in summer 2007. Summer is passing half the way. When will it be ready to use? Thanks.

**Comment by hz0324** [comment]
@danielweck Can you tell me how is going with the hypothesis.js project? Thanks.

**Comment by llemeurfr** [comment]
Hi @hz0324, please follow readium/readium-shared-js#396 to get updates on this project.

**Comment by DougsAraujo** [comment]
hypothesis is working, but the highlight does not work, I already enabled it in the cson package, what to do to work?

**Comment by danielweck** [comment]
@DougsAraujo see https://github.com/readium/readium-shared-js/issues/448#issuecomment-385627644
