### ISSUE TITLE
Question: can I read book by double-clicking epub?

### ISSUE THREAD

**Issue by tonydiep** [readium/readium-js-viewer#642]
First of all, thanks for making this great program. It is the best epub reader out there.

Question: Can I read the book by double-clicking epub in the file manage? Is Readium capable of satisfying this use case?

1. User finds book in file manager (nautilus, etc)
2. User double-clicks on book
3. Readium shows book

Right now I have to Start Readium, import book, then I can read the book.

**Comment by danielweck** [comment]
I assume you are talking about the Readium Chrome app ( https://chrome.google.com/webstore/detail/readium/fepbnnnkkadjhjahcafoaglimekefifl ).
On ChromeOS, yes there is a mechanism for file associations. However this is not supported on OSX, Windows, Linux, etc.

Also note that Google is deprecating Chrome apps on platforms other than ChromeOS.
See:
https://developer.chrome.com/apps/manifest/file_handlers
