### ISSUE TITLE
Not scaling navigation bar while zooming-in browsers

### ISSUE THREAD

**Issue by texervn** [readium/readium-js-viewer#648]
While zooming in a browser on my phone, the navigation bar gets really big too.
Is there any way to keep the navigation bar with its fixed initial size whenever we scale (zoom-in) the browser? Sometimes, I just like to touch and zoom in a portion of the current reading page.
Thanks.

**Comment by danielweck** [comment]
The user interface implemented by `readium-js-viewer` for the cloud / web reader ( https://readium.firebaseapp.com ) has not been designed with small touch displays in mind, unfortunately. It really has only been tested on desktop platforms, using mouse and keyboard interaction. There are lots of issues on the "phone" form factor, such as finger occlusion, reliance on mouse-over, restrictive control sizes, incorrect zooming behaviour, etc.

I'd love to see this fixed too :)

**Comment by texervn** [comment]
Thanks Daniel for your replying and the updated information.
I am satisfied with the cloud reader so far.

Best.
