### ISSUE TITLE
Hello, I would like to my web application integrated cloud reader, how do I modify the UI reader UI UI style and UI location

### ISSUE THREAD

**Issue by liqinglei** [readium/readium-js-viewer#649]
*General Instructions*

- *Please use a short, but meaningful title.*
- *Delete everything in italics before submitting issue*
- *Make sure to fill in as much information as possible*

#### This issue is a Bug|Feature Request|Enhancement|Question|Task|Other
*(choose ONE from the above list and delete the others)*

#### Related issue(s) and/or pull request(s)
*Example: See also #NUMBER*

#### Expected Behaviour
*What you expected Readium to do...*

#### Observed behaviour
*Instead, Readium does...*

#### Steps to reproduce
1. First, do this
2. Then do this
3. etc.

#### Test file(s)
*If relevant, please indicate public EPUB URL(s), or whether you can share ebook(s) privately.  It is often next to impossible to reproduce bugs without the original file.*

### Product
*Choose one of the following (and delete the others)*

* Readium Chrome extension
  * latest official version available from the Chrome Web Store 
  * Version of the Chrome browser
  * OS and version
* Readium cloud reader app
  * latest development build uploaded at https://readium.firebaseapp.com OR a custom integration (list public deployment URL, if any)
  * Browser and version
  * OS and version
* Native application (Readium SDK C++)
  * official "launcher" sample OR propietary app
  * OS and version
* Hybrid app (ReadiumJS)
  * Electron OR Apache Cordova OR ?
  * OS and version
* Other?

#### Additional information
*Please list any additional information that might help us*

Hello, I would like to my web application integrated cloud reader, how do I modify the UI reader UI UI style and UI location

**Comment by danielweck** [comment]
First, make sure you are able to build the existing cloud reader app by following instructions from the README:
https://github.com/readium/readium-js-viewer/blob/develop/README.md

Then, modify the CSS:
https://github.com/readium/readium-js-viewer/tree/master/src/css

...and the HTML templates:
https://github.com/readium/readium-js-viewer/tree/master/src/templates

...and rebuild.

**Comment by liqinglei** [comment]
Thank you very much for your solution

**Comment by liqinglei** [comment]
I have a question as follows:
Each time the highlight is loaded, the label position is always offset, which is why 

for example:
  reader.on(Globals.Events.CONTENT_DOCUMENT_LOADED, function ($iframe, spineItem) {
            if (_initialized) {
                _highlightsManager.attachAnnotations($iframe, spineItem, reader.getLoadedSpineItems());
				if(spineItem.idref == "id-id2604743"){
					//self.redrawAnnotations();
					_highlightsManager.addHighlight(spineItem.idref,"/4/2/4,/1:361,/1:400",2,"test-highlight");
				}
            } else {
                _initializedLate = true;
            }
        });
