### ISSUE TITLE
npm run dist causing error

### ISSUE THREAD

**Issue by makehappen2017** [readium/readium-js-viewer#668]
C:\Program Files\Git\readium-js-viewer>npm run dist

> readium-js-viewer@0.29.0-alpha predist C:\Program Files\Git\readium-js-viewer
> npm run build && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/mkdirp/bin/cmd.js dist

> readium-js-viewer@0.29.0-alpha prebuild C:\Program Files\Git\readium-js-viewer
> npm run clean

> readium-js-viewer@0.29.0-alpha clean C:\Program Files\Git\readium-js-viewer
> (yarn --version || echo noyarn) && node --version && npm --version && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js build-output && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js api-docs/* && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js dist

1.3.2
v8.9.0
5.5.1

> readium-js-viewer@0.29.0-alpha build C:\Program Files\Git\readium-js-viewer
> npm run build:scripts

> readium-js-viewer@0.29.0-alpha prebuild:scripts C:\Program Files\Git\readium-js-viewer
> npm run genPluginsConfig

> readium-js-viewer@0.29.0-alpha genPluginsConfig C:\Program Files\Git\readium-js-viewer
> cd readium-js/readium-shared-js/ && node readium-cfi-js/readium-build-tools/pluginsConfigMaker.js && cd ../..

========>
========> Plugins bootstrap ...
========>
process.env.npm_package_config_RJS_PLUGINS_OVERRIDE:
undefined
process.env[RJS_PLUGINS_OVERRIDE]:
undefined
Default plugins:  []
No plugin entries to override.
Plugins to load:  []
Generated plugin config files:
C:\Program Files\Git\readium-js-viewer\readium-js\readium-shared-js\build-config\RequireJS_config_plugins.js
C:\Program Files\Git\readium-js-viewer\readium-js\readium-shared-js\build-config\RequireJS_config_plugins_multiple-bundles.js
C:\Program Files\Git\readium-js-viewer\readium-js\readium-shared-js\build-config\RequireJS_config_plugins_single-bundle.js
========> End of plugins bootstrap.

> readium-js-viewer@0.29.0-alpha build:scripts C:\Program Files\Git\readium-js-viewer
> npm run versioning && npm run build:scripts:multiple && npm run build:scripts:single && npm run build:scripts:single:LITE && npm run build:scripts:single:CHROMEAPP --readium-js-viewer:RJS_UGLY=no && npm run build:scripts:single:CHROMEAPPWORKER --readium-js-viewer:RJS_UGLY=no

> readium-js-viewer@0.29.0-alpha preversioning C:\Program Files\Git\readium-js-viewer
> node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/mkdirp/bin/cmd.js build-output

> readium-js-viewer@0.29.0-alpha versioning C:\Program Files\Git\readium-js-viewer
> node build-config/versioning.js build-output/version.json

versionsMaker.js arguments:
[ 'build-output/version.json' ]
C:\Program Files\Git\readium-js-viewer

>> Versioning: C:\Program Files\Git\readium-js-viewer
Version: 0.29.0-alpha
Chrome version: 2.29.0-alpha
SHA: 8bc5c6f099a2bdabe3a0181711a5b94ab46387c7
Clean: false
Tag: 0.29.0-alpha-0-g8bc5c6f
Branch: develop

>> Versioning: C:\Program Files\Git\readium-js-viewer\readium-js
Version: 0.29.0-alpha
SHA: 9cd2fa48854694025487cd4630a6e1a8b8e1851f
Clean: false
Tag: 0.28.0-1-g9cd2fa4
...
Branch: develop

>> Versioning: C:\Program Files\Git\readium-js-viewer\readium-js\readium-shared-js
Version: 0.29.0-alpha
SHA: 60463c27e4417102f47df9c51e9953b2b467def2
Clean: false
Tag: 0.28.0-1-g60463c2
...
Branch: develop

>> Versioning: C:\Program Files\Git\readium-js-viewer\readium-js\readium-shared-js\readium-cfi-js
Version: 0.29.0-alpha
SHA: c40864fe5122a16fb5330824365f8f5b481adca2
Clean: false
Tag: 0.28.0-1-gc40864f
...
Branch: develop

> readium-js-viewer@0.29.0-alpha prebuild:scripts:multiple C:\Program Files\Git\readium-js-viewer
> node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/mkdirp/bin/cmd.js build-output/XXX && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/ncp/bin/ncp src/templates/ build-output/XXX/templates/ && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/ncp/bin/ncp src/i18n/ build-output/XXX/i18n/ && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/cpy-cli/cli.js build-output/version.json build-output/XXX/

> readium-js-viewer@0.29.0-alpha build:scripts:multiple C:\Program Files\Git\readium-js-viewer
> node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/requirejs/bin/r.js -o ./readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/RequireJS_config.js --rjs_bundle=multiple

========>
========> RJS bootstrap ...
========>
C:\Program Files\Git\readium-js-viewer
[ './readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/RequireJS_config.js',
  '--rjs_bundle=multiple' ]
readium-js/readium-shared-js/readium-cfi-js/readium-build-tools
process.env.npm_package_config_RJS_UGLY:
undefined
process.env[RJS_UGLY]:
undefined
multiple
Plugins config:
C:\Program Files\Git\readium-js-viewer\readium-js\readium-shared-js\build-config\RequireJS_config_plugins.js
../../build-config/RequireJS_config_plugins.js
Plugins bundle config:
../../build-config/RequireJS_config_plugins_multiple-bundles.js
[ '../build-config/RequireJS_config_common.js',
  '../build-config/RequireJS_config_multiple-bundles.js',
  '../../build-config/RequireJS_config_plugins.js',
  '../../build-config/RequireJS_config_plugins_multiple-bundles.js',
  '../../build-config/RequireJS_config_common.js',
  '../../build-config/RequireJS_config_multiple-bundles.js',
  '../../../build-config/RequireJS_config_common.js',
  '../../../build-config/RequireJS_config_multiple-bundles.js',
  '../../../../build-config/RequireJS_config_multiple-bundles_external-libs.js',
  '../../../../build-config/RequireJS_config_common.js',
  '../../../../build-config/RequireJS_config_multiple-bundles.js' ]
Error: Error: ENOENT: no such file or directory, open 'C:\Program Files\Git\readium-js-viewer\readium-js\readium-shared-js\node_modules\urijs\src\URI.js'
    at Object.fs.openSync (fs.js:646:18)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! readium-js-viewer@0.29.0-alpha build:scripts:multiple: `node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/requirejs/bin/r.js -o ./readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/RequireJS_config.js --rjs_bundle=multiple`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-js-viewer@0.29.0-alpha build:scripts:multiple script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mary\AppData\Roaming\npm-cache\_logs\2017-11-09T10_08_04_625Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! readium-js-viewer@0.29.0-alpha build:scripts: `npm run versioning && npm run build:scripts:multiple && npm run build:scripts:single && npm run build:scripts:single:LITE && npm run build:scripts:single:CHROMEAPP --readium-js-viewer:RJS_UGLY=no && npm run build:scripts:single:CHROMEAPPWORKER --readium-js-viewer:RJS_UGLY=no`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-js-viewer@0.29.0-alpha build:scripts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mary\AppData\Roaming\npm-cache\_logs\2017-11-09T10_08_04_731Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! readium-js-viewer@0.29.0-alpha build: `npm run build:scripts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-js-viewer@0.29.0-alpha build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mary\AppData\Roaming\npm-cache\_logs\2017-11-09T10_08_04_829Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! readium-js-viewer@0.29.0-alpha predist: `npm run build && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/mkdirp/bin/cmd.js dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-js-viewer@0.29.0-alpha predist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mary\AppData\Roaming\npm-cache\_logs\2017-11-09T10_08_04_928Z-debug.log

error log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Mary\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:scripts:multiple' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'prebuild:scripts:multiple',
4 verbose run-script   'build:scripts:multiple',
4 verbose run-script   'postbuild:scripts:multiple' ]
5 info lifecycle readium-js-viewer@0.29.0-alpha~prebuild:scripts:multiple: readium-js-viewer@0.29.0-alpha
6 verbose lifecycle readium-js-viewer@0.29.0-alpha~prebuild:scripts:multiple: unsafe-perm in lifecycle true
7 verbose lifecycle readium-js-viewer@0.29.0-alpha~prebuild:scripts:multiple: PATH: C:\Users\Mary\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Program Files\Git\readium-js-viewer\node_modules\.bin;C:\Users\Mary\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Program Files\Git\readium-js-viewer\node_modules\.bin;C:\Users\Mary\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Program Files\Git\readium-js-viewer\node_modules\.bin;C:\Users\Mary\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Program Files\Git\readium-js-viewer\node_modules\.bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Users\Mary\AppData\Local\Microsoft\WindowsApps;C:\Users\Mary\AppData\Roaming\npm;C:\Users\Mary\AppData\Local\Yarn\bin
8 verbose lifecycle readium-js-viewer@0.29.0-alpha~prebuild:scripts:multiple: CWD: C:\Program Files\Git\readium-js-viewer
9 silly lifecycle readium-js-viewer@0.29.0-alpha~prebuild:scripts:multiple: Args: [ '/d /s /c',
9 silly lifecycle   'node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/mkdirp/bin/cmd.js build-output/XXX && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/ncp/bin/ncp src/templates/ build-output/XXX/templates/ && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/ncp/bin/ncp src/i18n/ build-output/XXX/i18n/ && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/cpy-cli/cli.js build-output/version.json build-output/XXX/' ]
10 silly lifecycle readium-js-viewer@0.29.0-alpha~prebuild:scripts:multiple: Returned: code: 0  signal: null
11 info lifecycle readium-js-viewer@0.29.0-alpha~build:scripts:multiple: readium-js-viewer@0.29.0-alpha
12 verbose lifecycle readium-js-viewer@0.29.0-alpha~build:scripts:multiple: unsafe-perm in lifecycle true
13 verbose lifecycle readium-js-viewer@0.29.0-alpha~build:scripts:multiple: PATH: C:\Users\Mary\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Program Files\Git\readium-js-viewer\node_modules\.bin;C:\Users\Mary\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Program Files\Git\readium-js-viewer\node_modules\.bin;C:\Users\Mary\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Program Files\Git\readium-js-viewer\node_modules\.bin;C:\Users\Mary\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Program Files\Git\readium-js-viewer\node_modules\.bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Users\Mary\AppData\Local\Microsoft\WindowsApps;C:\Users\Mary\AppData\Roaming\npm;C:\Users\Mary\AppData\Local\Yarn\bin
14 verbose lifecycle readium-js-viewer@0.29.0-alpha~build:scripts:multiple: CWD: C:\Program Files\Git\readium-js-viewer
15 silly lifecycle readium-js-viewer@0.29.0-alpha~build:scripts:multiple: Args: [ '/d /s /c',
15 silly lifecycle   'node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/requirejs/bin/r.js -o ./readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/RequireJS_config.js --rjs_bundle=multiple' ]
16 silly lifecycle readium-js-viewer@0.29.0-alpha~build:scripts:multiple: Returned: code: 1  signal: null
17 info lifecycle readium-js-viewer@0.29.0-alpha~build:scripts:multiple: Failed to exec build:scripts:multiple script
18 verbose stack Error: readium-js-viewer@0.29.0-alpha build:scripts:multiple: `node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/requirejs/bin/r.js -o ./readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/RequireJS_config.js --rjs_bundle=multiple`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (C:\Users\Mary\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at EventEmitter.emit (events.js:214:7)
18 verbose stack     at ChildProcess.<anonymous> (C:\Users\Mary\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at ChildProcess.emit (events.js:214:7)
18 verbose stack     at maybeClose (internal/child_process.js:925:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
19 verbose pkgid readium-js-viewer@0.29.0-alpha
20 verbose cwd C:\Program Files\Git\readium-js-viewer
21 verbose Windows_NT 10.0.15063
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mary\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:scripts:multiple"
23 verbose node v8.9.0
24 verbose npm  v5.5.1
25 error code ELIFECYCLE
26 error errno 1
27 error readium-js-viewer@0.29.0-alpha build:scripts:multiple: `node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/requirejs/bin/r.js -o ./readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/RequireJS_config.js --rjs_bundle=multiple`
27 error Exit status 1
28 error Failed at the readium-js-viewer@0.29.0-alpha build:scripts:multiple script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

**Comment by danielweck** [comment]
Same error as https://github.com/readium/readium-js-viewer/issues/667
