### ISSUE TITLE
Are there any branches or teams that have contributed PDF reading? 

### ISSUE THREAD

**Issue by brettins** [readium/readium-js-viewer#670]
Hi everyone, as part of our project we are hoping to have PDF books readable from the web app. Have there been any branches or teams that have contributed to parsing and outputting a PDF book?

**Comment by llemeurfr** [comment]
No, the motto here is EPUB, the only reflowable / accessible open format on the market. Good luck with PDF.

**Comment by danielweck** [comment]
Hi Brett, obvious reply :)
https://mozilla.github.io/pdf.js/
