### ISSUE TITLE
Ensure that fixed layout documents have no margins or padding

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#673]
#### Related issue(s) and/or pull request(s)
*https://github.com/readium/readium-shared-js/issues/423*

#### Expected Behaviour
A fixed layout document should not be styled (except possibly for themes).  No margins, padding or other styles should be injected into the document.

#### Observed behaviour
Currently, if the author of an EPUB does not specify a margin on the body element, the RS will add a margin of 8 pixels from the user-agent style sheet.

#### Steps to reproduce
1. Load the test file (see below)
2. Check page 4.  Note that the red rectangle is cut off
3. Check the margin in the browser's inspector.

#### Test file(s)
https://drive.google.com/open?id=10y7ZJKdoG2yDVfqXLRkCWrDcbRDhW_eq

### Product
* Readium Chrome extension (current)
* Readium cloud reader app
* SDKLauncher-OSX

#### Additional information
None

**Comment by danielweck** [comment]
Pull Request: https://github.com/readium/readium-shared-js/pull/424

**Comment by danielweck** [comment]
Tested with the cloud reader and Ric's original `Tiny-FXL.epub`
