### ISSUE TITLE
Cant get the newly release 0.28

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#674]
Hello
Am trying to follow the steps as usually to get the latest readium-js viewer 0.28.But am getting an error on 
npm run prepare:all
I have node version 8.0.0 and Os Windows 7 64 bit

These are the errors
![untitled1](https://user-images.githubusercontent.com/10612561/33018713-32210342-ce00-11e7-8785-16357bf126ec.png)
![untitled2](https://user-images.githubusercontent.com/10612561/33018715-3246b330-ce00-11e7-936c-db9328b374da.png)
![untitled3](https://user-images.githubusercontent.com/10612561/33018716-326b8d0e-ce00-11e7-9343-f219681d5708.png)

**Comment by danielweck** [comment]
Could you please use another terminal than MS-DOS, such as GitBash or GitShell which come with the official GiHub and Git tools for Windows.
Sorry for the inconvenience, let us know if this helps.

**Comment by mahag** [comment]
I have downloaded the git bash from here https://git-for-windows.github.io/.
_npm run prepare:all_  worked
But now it is stopping at _npm run build_.
These are the errors
![2](https://user-images.githubusercontent.com/10612561/33062269-6d79b4a0-cea7-11e7-8e7d-f42ca4acc438.png)

**Comment by danielweck** [comment]
Thank you for the update.
Could you please now try from the develop branch. A bug was recently fixed to resolve NPM dependencies issues.
Many thanks!

**Comment by tddpirate** [comment]
Could you please tag a version with the NPM dependency issues fix?

**Comment by danielweck** [comment]
The bugfix for the NPM dependencies is multi-faceted and has not been retro-fitted into the master branch as a hotfix cherry-pick. Instead, it will be incorporated into the master branch along with a history of other non-breaking improvements, at the next release point. Meanwhile, I would recommend using the source tree from the head of the develop branch, which ; as of today ; is revision `2a41a144ad75cb33058c0684a817aa2fe332f907` https://github.com/readium/readium-js-viewer/commit/2a41a144ad75cb33058c0684a817aa2fe332f907
(this commit hash will pull-in the correct chain of submodule dependencies too)
