### ISSUE TITLE
Main scrollbar should be located in right border of the window

### ISSUE THREAD

**Issue by golopot** [readium/readium-js-viewer#685]
#### Expected Behaviour
In "continuous mode", scroll bar should be located in the right border. 

#### Observed behaviour
Scroll bar is displaced by the hidden "next page" button. 
![Screeshot](https://i.imgur.com/f7dsdlV.png)

### Product
* Readium Chrome extension
  * latest official version available from the Chrome Web Store

**Comment by danielweck** [comment]
The thin vertical regions on either side of the scrolling document viewport are reserved for the left/right arrow buttons (previous/next "page", or scroll block / unit). So, this is a "feature", not a "bug" :)
Do you have suggestions to improve this UI design?

**Comment by golopot** [comment]
GitBook's UI is an good example.
![GitBook ui sample](https://i.imgur.com/V74eLvj.png)
Image taken from: https://0xax.gitbooks.io/linux-insides/content/Booting/linux-bootstrap-1.html

In the improvement, the "previous/next page buttons" still exists, but is layered on top of of the mAIN content, without taking additional space.

**Comment by danielweck** [comment]
Oh sure, there are in fact existing Readium-based apps that overlay UI controls over the content / document viewport (notably mobile / touch-oriented apps, but also desktop apps).

However, the UI of (specifically) the ReadiumJS cloud reader / Chrome app is currently designed to ensure that the application "chrome" always remains outside of the bounds of the content viewport. This way, there can be no interference with hyperlinks, or other interactive elements in EPUB documents (reflowable or fixed layout).

Although the above design choice has its merits, personally I too think that the vertical scrollbar for the doc/continuous scrolling viewport is awkwardly placed. I just don't know how to fix this without significantly refactoring the current layout system.
