### ISSUE TITLE
TravisCI scripts is out of date (readium-cfi-js is not submodule)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#691]
https://travis-ci.org/readium/readium-js-viewer/jobs/354148478#L763

https://github.com/readium/readium-js-viewer/blob/develop/.travis.yml

**Comment by danielweck** [comment]
Commits on March 22nd => TravisCI still failing:
https://github.com/readium/readium-js-viewer/commits/develop

**Comment by danielweck** [comment]
```
Tracing dependencies for: readium-cfi-js
Error: Error: ENOENT: no such file or directory, open '/home/travis/build/readium/readium-js-viewer/build-output/_multiple-bundles/readium-cfi-js.js'
    at Object.fs.openSync (fs.js:667:18)
```

**Comment by danielweck** [comment]
Related (closed duplicated issues): https://github.com/readium/readium-js-viewer/issues/692 and https://github.com/readium/readium-js-viewer/issues/694

**Comment by danielweck** [comment]
Okay, @mahag it looks like the plugin configuration breaks the build. We are looking into this right now.

**Comment by danielweck** [comment]
Fixed: https://travis-ci.org/readium/readium-js-viewer/builds/362711641

**Comment by mahag** [comment]
So what should I do now?Same steps i tried before?

**Comment by danielweck** [comment]
Yes please, update your Git repositories with the latest code from the develop branch, make sure to enable the plugin again, and attempt to build.
