### ISSUE TITLE
Readium Cloud Reader lite and Hypothesis

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#692]
I have downloaded latest readium js viewer  and tried it on my server.It is working normally.
I am using the lite version of it.
I have downloaded master branch.
How can I show hypothesis once i open a book as showing here to the right in mobidy dick example?
![untitled](https://user-images.githubusercontent.com/10612561/38193185-6694575a-3679-11e8-8a66-044ef56c0f2e.png)

**Comment by mahag** [comment]
I tried these steps
https://gist.github.com/JCCR/105b17e9d10f26722a24e1c6678f9ae4

But it is not showing the toolbar as mentioned in point number 8

**Comment by danielweck** [comment]
You must enable the Hypothesis plugin in the 'plugins.cson' file, in readium-shared-js. For example, just like the TravisCI script does it on the command line:
https://github.com/readium/readium-js-viewer/blob/develop/.travis.yml
echo "plugins:['hypothesis']" > plugins/plugins.cson

**Comment by mahag** [comment]
I tried the following commands in GIT

cd D:/readium-js-viewer
cd readium-js
cd readium-shared-js
echo "plugins:['hypothesis']" > plugins/plugins.cson
cat plugins/plugins.cson
cd ../../
npm run prepare:all
npm run build
npm run dist

At last call I got an error the dist folder wasnt there in readium-js-viewer(develop branch)

This the error
`> readium-js-viewer@0.31.0-alpha predist D:\readium-js-viewer
> npm run build && node ./readium-js/readium-shared-js/node_modules/mkdirp/bin/c                                                                                                                md.js dist


> readium-js-viewer@0.31.0-alpha prebuild D:\readium-js-viewer
> npm run clean


> readium-js-viewer@0.31.0-alpha clean D:\readium-js-viewer
> (yarn --version || echo noyarn) && node --version && npm --version && node ./r                                                                                                                eadium-js/readium-shared-js/node_modules/rimraf/bin.js build-output && node ./re                                                                                                                adium-js/readium-shared-js/node_modules/rimraf/bin.js api-docs/* && node ./readi                                                                                                                um-js/readium-shared-js/node_modules/rimraf/bin.js dist

'yarn' is not recognized as an internal or external command,
operable program or batch file.
noyarn
v8.10.0
5.6.0

> readium-js-viewer@0.31.0-alpha build D:\readium-js-viewer
> npm run build:scripts


> readium-js-viewer@0.31.0-alpha prebuild:scripts D:\readium-js-viewer
> npm run genPluginsConfig


> readium-js-viewer@0.31.0-alpha genPluginsConfig D:\readium-js-viewer
> cd readium-js/readium-shared-js/ && node readium-build-tools/pluginsConfigMake                                                                                                                r.js && cd ../..

========>
========> Plugins bootstrap ...
========>
process.env.npm_package_config_RJS_PLUGINS_OVERRIDE:
undefined
process.env[RJS_PLUGINS_OVERRIDE]:
undefined
Default plugins:  [ 'hypothesis' ]
No plugin entries to override.
Plugins to load:  [ 'hypothesis' ]
Generated plugin config files:
D:\readium-js-viewer\readium-js\readium-shared-js\build-config\RequireJS_config_                                                                                                                plugins.js
D:\readium-js-viewer\readium-js\readium-shared-js\build-config\RequireJS_config_                                                                                                                plugins_multiple-bundles.js
D:\readium-js-viewer\readium-js\readium-shared-js\build-config\RequireJS_config_                                                                                                                plugins_single-bundle.js
========> End of plugins bootstrap.

> readium-js-viewer@0.31.0-alpha build:scripts D:\readium-js-viewer
> npm run versioning && npm run build:scripts:multiple && npm run build:scripts:                                                                                                                single && npm run build:scripts:single:LITE && npm run build:scripts:single:CHRO                                                                                                                MEAPP --readium-js-viewer:RJS_UGLY=no && npm run build:scripts:single:CHROMEAPPW                                                                                                                ORKER --readium-js-viewer:RJS_UGLY=no


> readium-js-viewer@0.31.0-alpha preversioning D:\readium-js-viewer
> node ./readium-js/readium-shared-js/node_modules/mkdirp/bin/cmd.js build-outpu                                                                                                                t


> readium-js-viewer@0.31.0-alpha versioning D:\readium-js-viewer
> node build-config/versioning.js build-output/version.json

versionsMaker.js arguments:
[ 'build-output/version.json' ]
D:\readium-js-viewer


>> Versioning: D:\readium-js-viewer
Version: 0.31.0-alpha
Chrome version: 2.31.0-alpha
SHA: 0c2cc4e088cb698b338dc292e5fc4150a1f518b5
Clean: false
Tag: 0.31.0-alpha-10-g0c2cc4e
Branch: develop


>> Versioning: D:\readium-js-viewer\readium-js
Version: 0.31.0-alpha
SHA: 0fbd15145510bb68660bf6356b9e1c0771f04362
Clean: false
Tag: 0.30.0-11-g0fbd151
...
Branch: develop


>> Versioning: D:\readium-js-viewer\readium-js\readium-shared-js
Version: 0.31.0-alpha
SHA: 254c8005ed2f4aa7e79634c200e24d59ff8738a4
Clean: false
Tag: 0.30.0-44-g254c800
...
Branch: develop

> readium-js-viewer@0.31.0-alpha prebuild:scripts:multiple D:\readium-js-viewer
> node ./readium-js/readium-shared-js/node_modules/mkdirp/bin/cmd.js build-outpu                                                                                                                t/XXX && node ./readium-js/readium-shared-js/node_modules/ncp/bin/ncp src/templa                                                                                                                tes/ build-output/XXX/templates/ && node ./readium-js/readium-shared-js/node_mod                                                                                                                ules/ncp/bin/ncp src/i18n/ build-output/XXX/i18n/ && node ./readium-js/readium-s                                                                                                                hared-js/node_modules/cpy-cli/cli.js build-output/version.json build-output/XXX/


> readium-js-viewer@0.31.0-alpha build:scripts:multiple D:\readium-js-viewer
> node ./readium-js/readium-shared-js/node_modules/requirejs/bin/r.js -o ./readi                                                                                                                um-js/readium-shared-js/readium-build-tools/RequireJS_config.js --rjs_bundle=mul                                                                                                                tiple

========>
========> RJS bootstrap ...
========>
D:\readium-js-viewer
[ './readium-js/readium-shared-js/readium-build-tools/RequireJS_config.js',
  '--rjs_bundle=multiple' ]
readium-js/readium-shared-js/readium-build-tools
process.env.npm_package_config_RJS_UGLY:
undefined
process.env[RJS_UGLY]:
undefined
multiple
Plugins config:
D:\readium-js-viewer\readium-js\readium-shared-js\build-config\RequireJS_config_                                                                                                                plugins.js
../build-config/RequireJS_config_plugins.js
Plugins bundle config:
../build-config/RequireJS_config_plugins_multiple-bundles.js
[ '../build-config/RequireJS_config_plugins.js',
  '../build-config/RequireJS_config_plugins_multiple-bundles.js',
  '../build-config/RequireJS_config_common.js',
  '../build-config/RequireJS_config_multiple-bundles.js',
  '../../build-config/RequireJS_config_common.js',
  '../../build-config/RequireJS_config_multiple-bundles.js',
  '../../../build-config/RequireJS_config_multiple-bundles_external-libs.js',
  '../../../build-config/RequireJS_config_common.js',
  '../../../build-config/RequireJS_config_multiple-bundles.js' ]

Tracing dependencies for: readium-plugin-hypothesis

Tracing dependencies for: readium-shared-js

Tracing dependencies for: readium-js

Tracing dependencies for: readium-external-libs

Tracing dependencies for: readium-js-viewer

Tracing dependencies for: readium-js-viewer_LITE

Tracing dependencies for: readium-cfi-js
Error: Error: ENOENT: no such file or directory, open 'D:\readium-js-viewer\buil                                                                                                                d-output\_multiple-bundles\readium-cfi-js.js'
    at Object.fs.openSync (fs.js:646:18)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! readium-js-viewer@0.31.0-alpha build:scripts:multiple: `node ./readium-                                                                                                                js/readium-shared-js/node_modules/requirejs/bin/r.js -o ./readium-js/readium-sha                                                                                                                red-js/readium-build-tools/RequireJS_config.js --rjs_bundle=multiple`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-js-viewer@0.31.0-alpha build:scripts:multiple scr                                                                                                                ipt.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\usr110013\AppData\Roaming\npm-cache\_logs\2018-04-04T06_16                                                                                                                _34_033Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! readium-js-viewer@0.31.0-alpha build:scripts: `npm run versioning && np                                                                                                                m run build:scripts:multiple && npm run build:scripts:single && npm run build:sc                                                                                                                ripts:single:LITE && npm run build:scripts:single:CHROMEAPP --readium-js-viewer:                                                                                                                RJS_UGLY=no && npm run build:scripts:single:CHROMEAPPWORKER --readium-js-viewer:                                                                                                                RJS_UGLY=no`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-js-viewer@0.31.0-alpha build:scripts script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\usr110013\AppData\Roaming\npm-cache\_logs\2018-04-04T06_16                                                                                                                _34_048Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! readium-js-viewer@0.31.0-alpha build: `npm run build:scripts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-js-viewer@0.31.0-alpha build script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\usr110013\AppData\Roaming\npm-cache\_logs\2018-04-04T06_16                                                                                                                _34_079Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! readium-js-viewer@0.31.0-alpha predist: `npm run build && node ./readiu                                                                                                                m-js/readium-shared-js/node_modules/mkdirp/bin/cmd.js dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the readium-js-viewer@0.31.0-alpha predist script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\usr110013\AppData\Roaming\npm-cache\_logs\2018-04-04T06_16                                                                                                                _34_110Z-debug.log
`

**Comment by danielweck** [comment]
Error also reported there:
https://github.com/readium/readium-js-viewer/issues/694

```
Tracing dependencies for: readium-cfi-js
Error: Error: ENOENT: no such file or directory, open 'D:\readium-js-viewer\buil d-output_multiple-bundles\readium-cfi-js.js'
at Object.fs.openSync (fs.js:646:18)
```

**Comment by danielweck** [comment]
Closing as duplicate of: https://github.com/readium/readium-js-viewer/issues/691
