### ISSUE TITLE
error in README instructions for cloud-reader

### ISSUE THREAD

**Issue by thedirk** [readium/readium-js-viewer#693]
instructions read: "a sibling epub_content/ folder is expected to contain exploded or zipped EPUBs" 

actually, the cloud-reader folder is the *parent* folder, and Readium looks for the epub_content folder within the cloud-reader folder (not a sibling folder). 

so, would expect to see: "a child epub_content/ folder is expected to contain exploded or zipped EPUBs", or similar.

**Comment by danielweck** [comment]
Thanks for the bug report!

Reference:
https://github.com/readium/readium-js-viewer/blob/develop/README.md#cloud-reader-deployment
"
The contents of the cloud-reader distribution folder (see section above) can be uploaded to an HTTP server as-is (either in the http://domain.com/ root, or any subfolder path http://domain.com/reader/), and a sibling epub_content/ folder is expected to contain exploded or zipped EPUBs
"

**Comment by rkwright** [comment]
Corrected and clarified (I hope).  [551ba2](https://github.com/readium/readium-js-viewer/commit/551ba276d2c2b54cc4147e51ec93cf664b1bc0d0)
