### ISSUE TITLE
Means to define my own word definitions

### ISSUE THREAD

**Issue by bargri** [readium/readium-js-viewer#703]
#### This issue is a Feature Request

I wish to produce an ebook that is written in a not so common language. In turn I would like the person reading this book to be able to click on any word in the book and get the definition of this word in say English. I, as the author of this book, would like to be able to define the definition of each word as part of my epub document.

**Comment by danielweck** [comment]
I would suggest you look at how "plugins" work, here is a trivial example:
https://github.com/readium/readium-shared-js/blob/develop/plugins/example/main.js
The `CONTENT_DOCUMENT_LOADED` event gives you access to the iframe content / publication (X)HTML document (`$iframe[0].contentDocument.documentElement`), so from there you can do whatever you like.
