### ISSUE TITLE
Travis reports (apparently) non-existent errors

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#708]
*Note:  this is apparently a bug in Travis, but recording the issue here anyway*

#### Related issue(s) and/or pull request(s)
*None*

#### Expected Behaviour
*Travis should accept updated files, build the CR and update Firebase*

#### Observed behaviour
*Instead, Travis starts the builds but reports that it "errored" but does not report what the error is/was*

#### Steps to reproduce
1. Clone the readium.github.io repo, master branch
2. Modify in some safe way (e.g. change a title)  the OPDS file in the epub_content folder
3. Push the OPDS file to the readium-github.io repo, master branch
4. Wait....  Check the Travis build [here](https://travis-ci.org/readium/readium-js-viewer/builds)
5. Travis will report that it "errored" but not where.

#### Test file(s)
*None needed*

### Product
* Readium CloudReader app
  
#### Additional information
*Tested on Mac OS Sierra, 10.12.6, Chrome 67 on a MacBookPro*

**Comment by danielweck** [comment]
It looks like the Surge authentication data has been revoked. I am looking into this.

```
...
surge --project ./dist/cloud-reader --domain readium.surge.sh
...
   Login (or create surge account) by entering email & password.
          email: 
No output has been received in the last 10m0s
...
```

https://surge.sh/help/integrating-with-travis-ci

**Comment by danielweck** [comment]
Seems fixed: https://travis-ci.org/readium/readium-js-viewer/jobs/408557385#L2761
Both Surge and Firebase deployments have been updated correctly:
https://readium.firebaseapp.com
https://readium.surge.sh/?epubs=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Fepub_library.opds

**Comment by danielweck** [comment]
Fixed by generating fresh Surge tokens for TravisCI.
