### ISSUE TITLE
MathJax v2.7.4 security update 

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#709]
https://groups.google.com/forum/m/#!topic/mathjax-dev/JCa8uRe3U2o

**Comment by pkra** [comment]
Yes, it's up to date. But 2.7.5 is out as well.

**Comment by pkra** [comment]
> Yes, it's up to date. But 2.7.5 is out as well.

By which I meant it's at 2.7.4 (which fixes the issur) but not yet 2.7.5.

**Comment by pkra** [comment]
v12.0.0 is now at MathJax v2.7.5

**Comment by danielweck** [comment]
Thanks Peter, now updated to `2.7.5`
https://github.com/mathjax/MathJax/releases/tag/2.7.5
