### ISSUE TITLE
Highlights and note don't appear when I double click on  the words.

### ISSUE THREAD

**Issue by purusingh** [readium/readium-js-viewer#710]
I was able to compile and run the app after downgrading  npm.
But Highlights and not don't appear when I double click on  the words.

**Comment by danielweck** [comment]
Assuming you are using the `develop` branch, here is the configuration file where you can activate the Hypothesis plugin (uncomment the line, and re-build `readium-js-viewer` with `npm run dist+sourcemap`, then use the build in `dist/cloud-reader` ... or simply type `npm run http` to launch the development mode):
https://github.com/readium/readium-shared-js/blob/develop/plugins/plugins.cson#L6
You can test the Hypothesis feature online at:
https://readium.firebaseapp.com

PS: the old "highlight" / "annotation" plugin does not exist anymore, it was woefully out-of-date / unmaintained.

**Comment by purusingh** [comment]
I tried this on both the master and develop branches and still it is not working? And I have another question how do I run cloudreader locally? is this url
http://127.0.0.1:8080/dev/index_RequireJS_no-optimize.html? a local cloudreader?
.I have changed  on all package.json from 

 "prepare:submodule": "cd readium-shared-js && npm run prepare:all && cd .. && ls",
to 
 "prepare:submodule": "cd readium-shared-js && npm run prepare:all && cd .. && dir",
because ls is not know command on windows.

**Comment by danielweck** [comment]
From https://github.com/readium/readium-js-viewer/issues/711
> I was able to compile and run the app after downgrading npm.
> But Highlights and not don't appear when I double click on the words.

**Comment by danielweck** [comment]
Did you activate the Hypothesis plugin?

**Comment by purusingh** [comment]
Thanks for response. How do I activate it. I have uncommented all  that you told to do. Do I have to do any thing else?


Thanks
Puru

Sent from my iPhone

On Aug 22, 2018, at 11:30 AM, Daniel Weck <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you activate the Hypothesis plugin?

**Comment by danielweck** [comment]
Did you run the commands after commenting the line?
As explained in my response above ( https://github.com/readium/readium-js-viewer/issues/710#issuecomment-414372227 ).

Once you invoke `npm run http`, a local HTTP server is running, and you can open `http://127.0.0.1:8080/dev/index_RequireJS_no-optimize.html` in your web browser.

**Comment by danielweck** [comment]
Regarding replacing `ls` with `dir`: on Windows it is highly recommended to install a decent terminal / shell (not MS-DOS) to execute command line instructions. As per the "prerequisites" documentation:
https://github.com/readium/readium-js-viewer/blob/develop/README.md#prerequisites

**Comment by purusingh** [comment]
I did

npm run prepare:all
npm run http


Thanks
Puru

Sent from my iPhone

On Aug 22, 2018, at 2:16 PM, Daniel Weck <notifications@github.com<mailto:notifications@github.com>> wrote:


Regarding replacing ls with dir: on Windows it is highly recommended to install a decent terminal / shell (not MS-DOS) to execute command line instructions. As per the "prerequisites" documentation:
https://github.com/readium/readium-js-viewer/blob/develop/README.md#prerequisites

**Comment by danielweck** [comment]
Have you tested the Hypothesis feature online at:
https://readium.firebaseapp.com
?

Once you have done that, please try with your local server instance of `readium-js-viewer`, and let us know if it works.

**Comment by purusingh** [comment]
I was able to make it

Thanks
Puru

Sent from my iPhone

On Aug 30, 2018, at 7:23 AM, Daniel Weck <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you please copy/paste the entire web browser console log from your local test? Thanks.
