### ISSUE TITLE
Highlights and note don't appear when I double click on the words.

### ISSUE THREAD

**Issue by purusingh** [readium/readium-js-viewer#711]
I was able to compile and run the app after downgrading npm.
But Highlights and not don't appear when I double click on the words.

 @danielweck
 Member
danielweck commented 2 days ago
Assuming you are using the develop branch, here is the configuration file where you can activate the Hypothesis plugin (uncomment the line, and re-build readium-js-viewer with npm run dist+sourcemap, then use the build in dist/cloud-reader ... or simply type npm run http to launch the development mode):
https://github.com/readium/readium-shared-js/blob/develop/plugins/plugins.cson#L6
You can test the Hypothesis feature online at:
https://readium.firebaseapp.com

PS: the old "highlight" / "annotation" plugin does not exist anymore, it was woefully out-of-date / unmaintained.

I tried this on both the master and develop branches and still it is not working? And I have another question how do I run cloudreader locally? is this url
http://127.0.0.1:8080/dev/index_RequireJS_no-optimize.html? a local cloudreader?
.I have changed on all package.json from

"prepare:submodule": "cd readium-shared-js && npm run prepare:all && cd .. && ls",
to
"prepare:submodule": "cd readium-shared-js && npm run prepare:all && cd .. && dir",
because ls is not know command on windows.

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/readium-js-viewer/issues/710

**Comment by danielweck** [comment]
@purusingh let's continue the discussion in the existing issue:
https://github.com/readium/readium-js-viewer/issues/710
