### ISSUE TITLE
Add a new dialog that announces the EOL of the Chrome app

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#712]
#### Expected Behaviour
On launch of the app, a dialog should be shown to the user stating that 
*"As Google has deprecated Chrome apps, this app is longer actively supported, and will no longer be available after October 01, 2018.  A list of other apps that are powered by Readium can be found at Readium.org/ReadingSystems.html"*

#### Steps to reproduce
1. Launch the app
2. Verify that the dialog is shown and can be dismissed.

#### Test file(s)
*N/A*

### Product
*Choose one of the following (and delete the others)*

* Readium Chrome App
  * latest official version available from the Chrome Web Store

**Comment by danielweck** [comment]
Implemented here:
https://github.com/readium/readium-js-viewer/pull/713

**Comment by rkwright** [comment]
Released with 0.31 and pushed to the Chrome store.  Works so closing.
