### ISSUE TITLE
Integrate readium-js-viewer to angular 7

### ISSUE THREAD

**Issue by nguyenhuutuananh** [readium/readium-js-viewer#721]
Lately I tried to integrate **readium-js-viewer** to **Angular 7**. I think i have two way to integrate:

1. Load external readium-js-viewer(LITE bundles) script in reading page.
2. Load readium-js-viewer in angular.json, readium scripts will load when angular init.

Problems:
- At the first way, in the reading page I can reading epub extractly what i want, but when I go back to another page (like epub list) then **readium script** still trigger event on the page. I had tried to unload readium when browse out reading page by remove script tag and destroy readium variables with this scripts: 
```typescript
if (READIUM && READIUM.reader) {
    READIUM.reader.off();
    READIUM = undefined;
}

if (ReadiumSDK) {
    ReadiumSDK.off(ReadiumSDK.Events.PLUGINS_LOADED);
    ReadiumSDK = undefined;
}
```
`cfi_navigation_logic.js` and `scroll_view.js` script still exists
![image](https://user-images.githubusercontent.com/10586038/50953759-f495c380-14e6-11e9-9625-f54d5262b624.png)

And jquery in readium conflict with jquery in my angular project. Some jQuery script which i use in angular had been destroyed.
- With second way, when i include readium script then readium-js-viewer will see all page is the reading page.

Can  I lack something? Could you please suggest me how can I use it extractly?
Thank you very much!

**Comment by nguyenhuutuananh** [comment]
My problem has been resolved! So I will close it.
Solutions: 
- Replace jquery in readium-shared-js with this code: 
```

**Comment by nguyenhuutuananh** [comment]
My problem has been resolved! So I will close it.
Solutions:
- Replace jquery in readium-shared-js with this code:
```javascript
define( "jquery", [], function() {
    return window.jQuery;
} );
```
Because my angular project and readium-js-viewer use jquery by itself so need to combine them to one.
- Remove all element interact with Readium will resolve errors by cfi_navigation_logic.js and scroll_view.js.

**Comment by danielweck** [comment]
Thank you for the update!
The RequireJS build config could be adapted to "inject" different variants / versions of jQuery. I think @jccr did this some time ago (a long time ago) for some other reason. Maybe I am remembering this wrong :)
At any rate, thanks again for keeping us posted!

**Comment by KOSSOKO** [comment]
@nguyenhuutuananh do you have a full example of integrating readium in angular ? I'm looking for it. 
Thanks
