### ISSUE TITLE
Invalid or corrupted EPUB package

### ISSUE THREAD

**Issue by odutolaabisoye** [readium/readium-js-viewer#731]
#### This issue is a |Question
When I try to load a pdf using the cloud-reader lite. It returns invalid or Corrupted Epub Package.

Here is the screenshot of the error. It returned in the console.
![invalid](https://user-images.githubusercontent.com/53864581/74089496-ec210b00-4aa1-11ea-832e-848cc6314bec.jpg)

**Comment by llemeurfr** [comment]
... and what is the question? Isn't the target EPUB corrupted?

**Comment by odutolaabisoye** [comment]
I have fixed it. It seems it's a zip package issue. It was reference ZIPJS folder instead of zip folder.
