### ISSUE TITLE
Focus not trapped in Settings dialog in IE and Firefox 

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#74]
Tested with release 0.14 in Windows 7 with Firefox 30 and IE 11.0.9600.16428. Focus is lost if I tab beyond the Save Changes button at the bottom of the Settings dialog. 

This is not a problem in Firefox 30 on OS X 10.9.3.

**Comment by becka11y** [comment]
This was fixed a long time ago and Daniel recently fixed the related #146
