### ISSUE TITLE
image splitting into two parts in horizontal modes

### ISSUE THREAD

**Issue by mohan9000** [readium/readium-js-viewer#744]
**Issue**:
when the user selecting the horizontal layout mode(double /single) view the reader splitting the images if the image is bigger one it is splitting the image into two parts and showing the image next .
This is happening based on the window height , we need that image in single and it has to adjust the size and width into signle side

**Comment by mohan9000** [comment]
is there any solution to prevent to stop images to split in reflowable content

**Comment by mohan9000** [comment]
<img width="959" alt="cpi_img1" src="https://user-images.githubusercontent.com/72591004/95736878-73afc100-0ca4-11eb-8324-04f9f6c5faf5.PNG">
please find the attachment of screenshot for the issue

**Comment by danielweck** [comment]
Hello, in the so-called "Readium 2" project there is a standalone library to manage document styling overrides. The problem you describe was addressed using CSS constructs which you might be able to "backport" to readium-shared-js:

https://github.com/readium/readium-css/issues/55
https://github.com/readium/readium-css/issues/50

This is the code you would need to adjust accordingly:
https://github.com/readium/readium-shared-js/blob/15412a0b8b9c98d060885fa98584a8205dce6a8d/js/views/reflowable_view.js#L989-L1018

CC @JayPanoz

**Comment by mohan9000** [comment]
@danielweck  tnx for the solution it helped me to solve my issue

**Comment by llemeurfr** [comment]
And if such a solution can be proposed as a pull request to the project, this will be certainly welcome for other users of the library.

**Comment by danielweck** [comment]
I agree, could you please share your solution? (presumably, a patch to `readium-shared-js`?)
