### ISSUE TITLE
readium loader issue

### ISSUE THREAD

**Issue by mohan9000** [readium/readium-js-viewer#746]
is it possible to modify or change the loader in the reader when navigating from one page to another page

**Comment by mohan9000** [comment]
is there any possibility to remove the readium loader (spinner) from the reader

**Comment by danielweck** [comment]
Sure:
https://github.com/readium/readium-js-viewer/blob/57a5a47379acae01ad3c26ca8a31d22586f2a7be/src/js/EpubReader.js#L210-L248

https://github.com/readium/readium-js-viewer/blob/57a5a47379acae01ad3c26ca8a31d22586f2a7be/src/js/EpubReader.js#L522

https://github.com/readium/readium-js-viewer/blob/57a5a47379acae01ad3c26ca8a31d22586f2a7be/src/js/EpubReader.js#L1077

https://github.com/readium/readium-js-viewer/blob/57a5a47379acae01ad3c26ca8a31d22586f2a7be/src/js/EpubReader.js#L1370

https://github.com/readium/readium-js-viewer/blob/57a5a47379acae01ad3c26ca8a31d22586f2a7be/src/js/EpubReader.js#L435

https://github.com/readium/readium-js-viewer/blob/57a5a47379acae01ad3c26ca8a31d22586f2a7be/src/js/EpubReader.js#L170
