### ISSUE TITLE
How to achieve content protection for Epub Reader and do the Encryption Decryption 

### ISSUE THREAD

**Issue by 575755** [readium/readium-js-viewer#751]
Hi ,
In our Epub Reader we need to do encrypt/ decrypt the content (html/xhtml) for content protection. Please guide us how to achieve the content protection with the help of Readium 

Note: When user copying xhtml Http request Url and pasting it in another tab they should not able to see the content

**Comment by llemeurfr** [comment]
A protection of such type will be developed in 2021 by [Readium members](https://readium.org/membership/join/) in the scope of [Readium Web](https://github.com/readium/web); not for the older Readium JS. 

Maybe someone having developed such a protection on Readium JS will be happy to share his experience. At EDRLab, we did not study such a thing.

**Comment by danielweck** [comment]
@mohan9000 asked a similar question here: https://github.com/readium/readium-js-viewer/issues/752
