### ISSUE TITLE
content protection

### ISSUE THREAD

**Issue by mohan9000** [readium/readium-js-viewer#752]
- *content protection .*
- *how to achieve content protection by using the readium library*
- *hi, is there any way that we can achieve content protection or to load the protected content in the readium, if it is possible please let us know that how to achieve it in open source library. If we can't able to achieve that with the open source library , is there any licensed source library to achieve this *

#### Expected Behaviour
*expected behaviour is that needs to load the protected content or able to protect the content from the library side *

#### Observed behaviour
*as of now we are not sure these features are available.*

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/readium-js-viewer/issues/751
